<?php
/**
 * Created by Hidro Le
 * Project: LoveMyBubbles
 * Job Title: Magento Develop
 * Date: 22/09/2017
 * Time: 11:05
 */

namespace Forix\ImportHelper\Model\Import\RawData\ColumnValidator\Product;

class ProductType extends EmptyValidator
{
    public function customValue($value, $rawData = [])
    {
        return strtolower(parent::customValue($value, $rawData)); // TODO: Change the autogenerated stub
    }
}