<?php
/**
 * @var $block \Forix\FishPig\Block\Post\ListPost
 * @var $helper \Forix\FishPig\Helper\Data
 */
	$posts      = $block->getPosts()["post_collection"];
    $helper     = $this->helper(Forix\FishPig\Helper\Data::class);
?>

<?php if (count($posts) > 0) : ?>
	<?php foreach ($posts as $post) : ?>
		<div class="list-item-blog">
			<div class="inner">
                <div class="thumbnail">
					<?php if ($image = $post->getImage()): ?>
						<?php $imgSrc = $helper->resize($image->getFullSizeImage(),311,180); ?>
                        <a title="<?php echo $post->getName(); ?>" href="<?php echo $post->getUrl(); ?>"><img alt="<?php echo $imgSrc;  ?>" src="<?php echo $imgSrc; ?>" /></a>
					<?php else : ?>
                        <a title="<?php echo $post->getName(); ?>"  href="<?php echo $post->getUrl(); ?>"><img alt="<?php echo $helper->getMediaUrl() . 'blog/image-not-found.jpg'; ?>" src="<?php echo $helper->getMediaUrl() . 'blog/image-not-found.jpg'; ?>" /></a>
					<?php endif; ?>
                </div>
				<div class="post-info">
					<span class="post-date"><?php echo $post->getPostDate("m/d/Y"); ?></span>
                    <a title="<?php echo $post->getName(); ?>"  href="<?php echo $post->getUrl(); ?>"><h2 data-mage-init='{"forix/formattext":{}}' class="title"><?php echo $post->getName(); ?></h2></a>
				</div>
				<?php if ($categoryString = $post->getTermCollectionAsStringCategory('category')): ?>
					<div class="category">
						<ul><?php echo $categoryString; ?></ul>
					</div>
				<?php endif; ?>
			</div>
		</div>
	<?php endforeach; ?>
<?php endif; ?>