<?php
/**
 * Created by: Bruce
 * Date: 2/19/16
 * Time: 10:48
 */
namespace Forix\ReCaptcha\Block;

class Holder extends Explicit {

	public function __construct(
	    \Magento\Framework\View\Element\Template\Context $context, 
        \Forix\ReCaptcha\Helper\Data $reCaptchaHelper,
        array $data = [])
    {
        parent::__construct($context, $reCaptchaHelper, $data);
    }

    /*public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Forix\ReCaptcha\Helper\Data $helper,
        array $data) {
        parent::__construct($context, $data);
        $this->_helper = $helper;
    }*/

	protected function _beforeToHtml() {
		if($formId = $this->getFormId()) {
			$forms = $this->_reCaptchaHelper->getFormApplied();
			if(!in_array($formId,$forms)){
				$this->setTemplate("");
			}
		}
		return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
	}
}