<div class="product-social-links">
    <div class="product-addto-links" data-role="add-to-links">
        <div class="action shareto">
            <span><?php /* @escapeNotVerified */ echo __('Share') ?></span>
            <div class="share-container">
                <div class="addthis_inline_share_toolbox"></div>
                <?php echo $block->getChildHtml(); ?>
            </div>
        </div>
    </div>
</div>
