<?php echo $block->getBlockHtml('formkey'); ?>
<input type="hidden" id="ishttps_enabled" value="<?php echo $block->isFEHttpsEnable() ?>" />
<!-- ko foreach: getRegion('before') -->
<!-- ko template: getTemplate() --><!-- /ko -->
<!-- /ko -->
<div class="minilogin-scr" data-bind="mageInit:{'Forix_Minilogin/js/forix.miniscroll':{}}">
    <div class="block block-customer-login"
         data-bind="attr: {'data-label': $t('or')}">
        <div class="block-title">
            <strong id="block-customer-login-heading"
                    role="heading"
                    aria-level="2"
                    data-bind="i18n: 'Login'"></strong>
        </div>
        <!-- ko foreach: getRegion('messages') -->
        <!-- ko template: getTemplate() --><!-- /ko -->
        <!--/ko-->
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form-minilogin" data-role="login"
                  data-bind="submit:login"
                  method="post" novalidate="novalidate">
                <div class="fieldset"
                     data-bind="attr: {'data-hasrequired': $t('* Required Fields')}">
                    <div class="field field-email required">
                        <div class="control">
                            <input type="text"
                                   class="input-text"
                                   id="login-email"
                                   name="username"
                                   data-bind="attr: {autocomplete: autocomplete}"
                                   data-validate="{required:true, 'validate-email':true}" required="required"/>
                            <label class="label" for="login-email"><span data-bind="i18n: 'Email Address'"></span></label>
                        </div>
                    </div>
                    <div class="field field-password required">
                        <div class="control">
                            <input type="password"
                                   class="input-text"
                                   id="login-password"
                                   name="password"
                                   data-bind="attr: {autocomplete: autocomplete}"
                                   data-validate="{required:true, 'validate-password':true}"
                                   autocomplete="off" required="required"/>
                            <label for="login-password" class="label"><span data-bind="i18n: 'Password'"></span></label>
                        </div>
                    </div>
                    <!-- ko foreach: getRegion('additional-login-form-fields') -->
                    <!-- ko template: getTemplate() --><!-- /ko -->
                    <!-- /ko -->
                </div>
                <div class="actions-toolbar">
                    <input name="context" type="hidden" value="checkout" />
                    <div class="buttons">
                        <div>
                            <button type="submit" class="action action-login secondary" name="send" id="send22">
                                <span data-bind="i18n: 'LOGIN'"></span>
                            </button>
                        </div>
                        <div class="forgot-password-form">
                            <a class="action" data-bind="attr: {href: forgotPasswordUrl}, click: callForgotPwdForm">
                                <span data-bind="i18n: 'Forgot Password?'"></span>
                            </a>
                        </div>
                        <div class="line">
                            <span>New Here</span>
                        </div>
                        <div>
                            <a class="action action-register" data-bind="attr: {href: registerUrl}" title="create an account">
                                <span data-bind="i18n: 'create an account'"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
            <form class="form form-forgotpwd no-display" method="post" data-bind="submit:forgotpwd" id="forgotpwd-form" novalidate="novalidate">
                <div class="fieldset forgotpwd" data-bind="attr: {'data-hasrequired': $t('* Required Fields')}">
                    <div class="field title">FORGOT YOUR PASSWORD?</div>
                    <div class="field note">No worries. Enter your email and we'll email you instructions on how to reset your password.</div>
                    <div class="field email required">
                        <label for="forgotpwd-email" class="label"><span>Email</span></label>
                        <div class="control">
                            <input type="email" name="email" alt="email" id="forgotpwd-email" class="input-text" value="" data-validate="{required:true, 'validate-email':true}" required="required">
                            <label for="forgotpwd-email" class="label"><span>Email Address</span></label>
                        </div>
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="buttons">
                        <div>
                            <button type="submit" class="action" name="send" id="send3">
                                <span data-bind="i18n: 'CONTINUE'"></span>
                            </button>
                            <p class="never-mind">
                                <a class="action" data-bind="click: closeForgotPwdForm">
                                    <span data-bind="i18n: 'Never mind!'"></span>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
