<?php
$helper = $this->helper('Forix\Base\Helper\Data');
$helperCompany = $this->helper('Forix\CustomerOrder\Helper\Data');
?>
<div id="mini-login" class="block minilogin-wrapper"  data-block="mini_login" data-bind="scope: 'mini_login_content'">
    <a class="action showlogin" data-trigger="authentication" href="javascript:void(0)" title="My Account"></a>
    <div class="block-authentication swipe-minilogin"  data-bind="mageInit: {
            'forix/pushdata':{
                'type': 'form'
            }}, blockLoader: isLoading">
        <div data-bind="dynhtml: customerLoginHtml "></div>
    </div>
    <script type="text/javascript">
        window.authenticationPopup = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
        window.miniloginUrl = '<?php echo $block->getUrlCustomer()->getLoginPostUrl(); ?>';
    </script>
    <script type="text/x-magento-init">
        {
            "#mini-login": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
            },
            "*": {
                "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
            }
        }
    </script>
</div>