<section class="box-style-guide">
    <h3>Colors</h3>
    <section>
        <ul class="guide-color-swatches">
            <li><span style="background: #3C3B4B;">@sss-color-1</span><a href="#">#3C3B4B - @sss-color-1</a></li>
            <li><span style="background: #3C3B4B;">@sss-color-2</span><a href="#">#444B56 - @sss-color-2</a></li>
            <li><span style="background: #8C8B9A;">@sss-color-3</span><a href="#">#8C8B9A - @sss-color-3</a></li>
            <li><span style="background: #E0E0E0;">@sss-color-4</span><a href="#">#E0E0E0 - @sss-color-4</a></li>
            <li><span style="background: #F48D40;">@sss-color-5</span><a href="#">#F48D40 - @sss-color-5</a></li>
            <li><span style="background: #8DC63F;">@sss-color-6</span><a href="#">#8DC63F - @sss-color-6</a></li>
            <li><span style="background: #40A7F4;">@sss-color-7</span><a href="#">#40A7F4 - @sss-color-7</a></li>
            <li><span style="background: #980F0F;">@sss-color-8</span><a href="#">#980F0F - @sss-color-8</a></li>
        </ul>
    </section>

    <h3>Breadcrumbs</h3>
    <section>
        <div class="breadcrumbs">
            <ul class="items">
                <li class="item home">
                    <a href="http://m2temp.local/" title="Go to Home Page">Home</a>
                </li>
                <li class="item">
                    <a href="http://m2temp.local/" title="Go to Home Page">Category 1</a>
                </li>
                <li class="item">
                    <a href="http://m2temp.local/" title="Go to Home Page">Category 2</a>
                </li>
                <li class="item cms_page last">
                    <strong>Current page</strong>
                </li>
            </ul>
        </div>
    </section>

    <h3>Text</h3>
    <section>
        <section class="typography-heading">
            <h1>Header Level 1 <small>&:extend(.forix-abs-secondary-title-size all)</small></h1>
            <h2>Header Level 2 <small>&:extend(.forix-abs-primary-title-size all)</small></h2>
            <h3>Header Level 3 <small>&:extend(.forix-abs-three-title-size all)</small></h3>
            <h4>Header Level 4 <small>&:extend(.forix-abs-medium-title-size all)</small></h4>
        </section>
        <h3>Typography links</h3>
        <section class="typography-links">
            <ul>
                <li><a href="#">Default Link</a></li>
                <li><a href="#" class="second-link link-type1">Type 1 </a>&nbsp;<small>&:extend(.forix-abs-link1 all);</small></li>
                <li><span class="alink">Span styled as a link</span>&nbsp;<small>&:extend(.alink all);</small></li>
                <li><button class="alink" type="button"><span>Button styled as a link</span></button></li>
            </ul>
            <div class="block account-nav">
                <div class="title account-nav-title">
                    <strong>
                    </strong>
                </div>
                <div class="content account-nav-content" id="account-nav">
                    <ul class="nav items">
                        <li class="nav item current">
                            <strong>Account Dashboard
                            </strong>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/sales/order/history/">My Orders
                            </a>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/downloadable/customer/products/">My Downloadable Products
                            </a>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/wishlist/">My Wish List
                            </a>
                        </li>
                        <li class="nav item">
        <span class="delimiter">
        </span>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/customer/address/">Address Book
                            </a>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/customer/account/edit/">Account Information
                            </a>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/vault/cards/listaction/">Stored Payment Methods
                            </a>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/paypal/billing_agreement/">Billing Agreements
                            </a>
                        </li>
                        <li class="nav item">
        <span class="delimiter">
        </span>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/review/customer/">My Product Reviews
                            </a>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/newsletter/manage/">Newsletter Subscriptions
                            </a>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/aw_helpdesk/ticket/">Help Desk
                            </a>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/awgiftcard/card/">Gift Card
                            </a>
                        </li>
                        <li class="nav item">
                            <a href="http://softstarshoes/notesoncustomers/notes/">Notes from Manager
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <h3>Base typography</h3>
        <section class="typography-base">
            <p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac <small>turpis</small> egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, <em>tempor</em> sit amet, ante. Donec <sub>eu</sub> libero sit amet quam egestas semper. <code>Aenean ultricies</code> mi vitae <sup>est</sup>. Mauris placerat eleifend leo. <abbr>Quisque</abbr> sit amet est et sapien <mark>ullamcorper</mark> pharetra.</p>
            <p>Paragraph Text. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<i>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</i></p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. <small>Small Text. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</small></p>
            <hr>
            <p><dfn>Pellentesque</dfn> habitant <i>morbi</i> tristique <b>senectus</b> et netus et malesuada fames ac turpis egestas.</p>
        </section>
        <h3>Typography lists</h3>
        <section class="typography-lists">
            <ol>
                <li>Coffee</li>
                <li>Tea</li>
                <li>Milk</li>
            </ol>
            <ul>
                <li>Coffee</li>
                <li>Tea</li>
                <li>Milk</li>
            </ul>
            <ol>
                <li>Coffee</li>
                <li>Tea</li>
                <li>
                    Milk
                    <ul>
                        <li>Coffee</li>
                        <li>Tea</li>
                        <li>Milk</li>
                    </ul>
                </li>
            </ol>
            <ul>
                <li>Coffee</li>
                <li>Tea</li>
                <li>Milk
                    <ul>
                        <li>Coffee</li>
                        <li>Tea</li>
                        <li>Milk</li>
                    </ul>
                </li>
            </ul>
            <dl>
                <dt>Coffee</dt>
                <dd>Black hot drink</dd>
                <dt>Milk</dt>
                <dd>White cold drink</dd>
            </dl>
        </section>
        <h3>Typography other tag</h3>
        <section class="typography-code">
            <p>The <abbr title="World Health Organization">WHO</abbr> was founded in 1948.</p>
            <code>A piece of computer code</code>
            <kbd>Keyboard input</kbd>
            <pre>
                Text in a pre element
                is displayed in a fixed-width
                font, and it preserves
                both      spaces and
                line breaks
                <code>A piece of computer code</code>
            </pre>
        </section>
        <h3>Typography blockquote</h3>
        <section class="typography-blockquote">
            <blockquote>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. Ut a est eget ligula molestie gravida. Curabitur massa.</p>
                <small>Ut a est eget ligula molestie gravida. Curabitur massa</small>
                <a href="#">Author quotes</a>
                <ul>
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>Lorem ipsum dolor sit amet</li>
                </ul>
                <footer>
                    <p><cite>The Scream</cite> by Edward Munch. Painted in 1893.</p>
                </footer>
            </blockquote>
        </section>
        </br>
    </section>

    <h3>Buttons</h3>
    <section>
        <ul class="no-list">
            <li>
                <button class="action" type="button"><span>Type 1</span></button>
            </li>
            <li>
                <button class="action type1" type="button"><span>Type 2</span></button>
                &:extend(.forix-abs-button-type1 all);
            </li>
            <li>
                <button class="action type2" type="button"><span>Type 3</span></button>
                &:extend(.forix-abs-button-type2 all);
            </li>
            <li>
                <button class="action type3" type="button"><span>Type 4</span></button>
                &:extend(.forix-abs-button-type3 all);
            </li>
            <li>
                <button class="action type4" type="button"><span>Type 5</span></button>
                &:extend(.forix-abs-button-type4 all);
            </li>
            <li>
                <button class="action type5" type="button"><span>Type 6</span></button>
                &:extend(.forix-abs-button-type5 all);
            </li>
            <li>
                <button class="action type6" type="button"><span>small button</span></button>
                &:extend(.forix-abs-button-type6 all);
            </li>
            <li>
                <button class="action" disabled type="button"><span>Disabled</span></button>
            </li>
            <li>
                <a class="action abutton"><span>Link styled as a button</span></a>
                &:extend(.alink all);
            </li>
        </ul>
    </section>

    <h3>Form</h3>
    <section>
        <form class="form form-shipping-address" id="co-shipping-form" data-bind="attr: {'data-hasrequired': $t('* Required Fields')}" data-hasrequired="* Required Fields">
            <div id="shipping-new-address-form" class="fieldset address">
                <div class="field _required" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.firstname">
                    <label class="label" data-bind="attr: { for: element.uid }" for="ME85B0G">
                        <span data-bind="i18n: element.label">First Name</span>
                    </label>
                    <div class="control" data-bind="css: {'_with-tooltip': element.tooltip}">
                        <input class="input-text" type="text" data-bind="
                                                         value: value,
                                                         valueUpdate: 'keyup',
                                                         hasFocus: focused,
                                                         attr: {
                                                         name: inputName,
                                                         placeholder: placeholder,
                                                         'aria-describedby': getDescriptionId(),
                                                         'aria-required': required,
                                                         'aria-invalid': error() ? true : 'false',
                                                         id: uid,
                                                         disabled: disabled
                                                         }" name="firstname" aria-required="true" aria-invalid="false" id="ME85B0G" required>
                        <label class="label" data-bind="attr: { for: element.uid }" for="ME85B0G">
                            <span data-bind="i18n: element.label">First Name</span>
                        </label>
                    </div>
                </div>
                <div class="field _required" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.lastname">
                    <label class="label" data-bind="attr: { for: element.uid }" for="P0L9MUY">
                        <!-- ko if: element.label -->
                        <span data-bind="i18n: element.label">Last Name
        </span>
                        <!-- /ko -->
                    </label>
                    <div class="control" data-bind="css: {'_with-tooltip': element.tooltip}">
                        <!-- ko ifnot: element.hasAddons() -->
                        <!-- ko template: element.elementTmpl -->
                        <input class="input-text" type="text" data-bind="
                                                         value: value,
                                                         valueUpdate: 'keyup',
                                                         hasFocus: focused,
                                                         attr: {
                                                         name: inputName,
                                                         placeholder: placeholder,
                                                         'aria-describedby': getDescriptionId(),
                                                         'aria-required': required,
                                                         'aria-invalid': error() ? true : 'false',
                                                         id: uid,
                                                         disabled: disabled
                                                         }" name="lastname" aria-required="true" aria-invalid="false" id="P0L9MUY" required>
                        <!-- /ko -->
                        <!-- /ko -->
                        <!-- ko if: element.hasAddons() -->
                        <!-- /ko -->
                        <!-- ko if: element.tooltip -->
                        <!-- /ko -->
                        <!-- ko if: element.notice -->
                        <!-- /ko -->
                        <!-- ko if: element.error() -->
                        <!-- /ko -->
                        <!-- ko if: element.warn() -->
                        <!-- /ko -->
                        <label class="label" data-bind="attr: { for: element.uid }" for="P0L9MUY">
                            <!-- ko if: element.label -->
                            <span data-bind="i18n: element.label">Last Name
        </span>
                            <!-- /ko -->
                        </label>
                    </div>
                </div>
                <!-- /ko -->
                <!-- /ko -->
                <!-- /ko -->
                <!-- ko if: hasTemplate() -->
                <!-- ko template: getTemplate() -->
                <div class="field optional" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.company">
                    <label class="label" data-bind="attr: { for: element.uid }" for="TMS4R2W">
                        <!-- ko if: element.label -->
                        <span data-bind="i18n: element.label">Company
        </span>
                        <!-- /ko -->
                    </label>
                    <div class="control" data-bind="css: {'_with-tooltip': element.tooltip}">
                        <!-- ko ifnot: element.hasAddons() -->
                        <!-- ko template: element.elementTmpl -->
                        <input class="input-text" type="text" data-bind="
                                                         value: value,
                                                         valueUpdate: 'keyup',
                                                         hasFocus: focused,
                                                         attr: {
                                                         name: inputName,
                                                         placeholder: placeholder,
                                                         'aria-describedby': getDescriptionId(),
                                                         'aria-required': required,
                                                         'aria-invalid': error() ? true : 'false',
                                                         id: uid,
                                                         disabled: disabled
                                                         }" name="company" aria-invalid="false" id="TMS4R2W" required>
                        <!-- /ko -->
                        <!-- /ko -->
                        <!-- ko if: element.hasAddons() -->
                        <!-- /ko -->
                        <!-- ko if: element.tooltip -->
                        <!-- /ko -->
                        <!-- ko if: element.notice -->
                        <!-- /ko -->
                        <!-- ko if: element.error() -->
                        <!-- /ko -->
                        <!-- ko if: element.warn() -->
                        <!-- /ko -->
                        <label class="label" data-bind="attr: { for: element.uid }" for="TMS4R2W">
                            <!-- ko if: element.label -->
                            <span data-bind="i18n: element.label">Company
        </span>
                            <!-- /ko -->
                        </label>
                    </div>
                </div>
                <!-- /ko -->
                <!-- /ko -->
                <!-- /ko -->
                <!-- ko if: hasTemplate() -->
                <!-- ko template: getTemplate() -->
                <fieldset class="field street admin__control-fields required" data-bind="css: additionalClasses">
                    <legend class="label">
        <span data-bind="i18n: element.label">Street Address
        </span>
                    </legend>
                    <div class="control">
                        <!-- ko foreach: { data: elems, as: 'element' } -->
                        <!-- ko if: element.visible() -->
                        <!-- ko ifnot: (element.input_type == 'checkbox' || element.input_type == 'radio') -->
                        <!-- ko template: $parent.fieldTemplate -->
                        <div class="field _required" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.street.0">
                            <label class="label" data-bind="attr: { for: element.uid }" for="W7962LP">
                                <!-- ko if: element.label -->
                                <!-- /ko -->
                            </label>
                            <div class="control" data-bind="css: {'_with-tooltip': element.tooltip}">
                                <!-- ko ifnot: element.hasAddons() -->
                                <!-- ko template: element.elementTmpl -->
                                <input class="input-text" type="text" data-bind="
                                                             value: value,
                                                             valueUpdate: 'keyup',
                                                             hasFocus: focused,
                                                             attr: {
                                                             name: inputName,
                                                             placeholder: placeholder,
                                                             'aria-describedby': getDescriptionId(),
                                                             'aria-required': required,
                                                             'aria-invalid': error() ? true : 'false',
                                                             id: uid,
                                                             disabled: disabled
                                                             }" name="street[0]" aria-required="true" aria-invalid="false" id="W7962LP" required>
                                <label class="label" data-bind="attr: { for: element.uid }" for="W7962LP">
                                </label>
                            </div>
                        </div>
                        <div class="field additional" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.street.1">

                            <div class="control" data-bind="css: {'_with-tooltip': element.tooltip}">
                                <input class="input-text" type="text" data-bind="
                                                             value: value,
                                                             valueUpdate: 'keyup',
                                                             hasFocus: focused,
                                                             attr: {
                                                             name: inputName,
                                                             placeholder: placeholder,
                                                             'aria-describedby': getDescriptionId(),
                                                             'aria-required': required,
                                                             'aria-invalid': error() ? true : 'false',
                                                             id: uid,
                                                             disabled: disabled
                                                             }" name="street[1]" aria-invalid="false" id="A7LL1K0">
                                <label class="label" data-bind="attr: { for: element.uid }" for="A7LL1K0">
                                </label>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="field _required" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.city">
                    <label class="label" data-bind="attr: { for: element.uid }" for="KIAAOEY">
                        <span data-bind="i18n: element.label">City</span>
                    </label>
                    <div disabled class="control" data-bind="css: {'_with-tooltip': element.tooltip}">
                        <input disabled class="input-text" type="text" data-bind="
                                                         value: value,
                                                         valueUpdate: 'keyup',
                                                         hasFocus: focused,
                                                         attr: {
                                                         name: inputName,
                                                         placeholder: placeholder,
                                                         'aria-describedby': getDescriptionId(),
                                                         'aria-required': required,
                                                         'aria-invalid': error() ? true : 'false',
                                                         id: uid,
                                                         disabled: disabled
                                                         }" name="city" aria-required="true" aria-invalid="false" id="KIAAOEY" required>

                        <label class="label" data-bind="attr: { for: element.uid }" for="KIAAOEY">
                            <span data-bind="i18n: element.label">City</span>
                        </label>
                    </div>
                </div>

                <div class="field _required" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.region_id">
                    <label class="label" data-bind="attr: { for: element.uid }" for="E9ISGXO">
                        <!-- ko if: element.label -->
                        <span data-bind="i18n: element.label">State/Province
        </span>
                        <!-- /ko -->
                    </label>
                    <div class="control" data-bind="css: {'_with-tooltip': element.tooltip}">
                        <!-- ko ifnot: element.hasAddons() -->
                        <!-- ko template: element.elementTmpl -->
                        <select disabled class="select" data-bind="
                                          attr: {
                                          name: inputName,
                                          id: uid,
                                          disabled: disabled,
                                          'aria-describedby': getDescriptionId(),
                                          'aria-required': required,
                                          'aria-invalid': error() ? true : 'false',
                                          placeholder: placeholder
                                          },
                                          hasFocus: focused,
                                          optgroup: options,
                                          value: value,
                                          optionsCaption: caption,
                                          optionsValue: 'value',
                                          optionsText: 'label',
                                          optionsAfterRender: function(option, item) {
                                          if (item &amp;&amp; item.disabled) {
                                          ko.applyBindingsToNode(option, {attr: {disabled: true}}, item);
                                          }
                                          }" name="region_id" id="E9ISGXO" aria-required="true" aria-invalid="false">
                            <option value="">Please select a region, state or province.
                            </option>
                            <option data-title="Alabama" value="1">Alabama
                            </option>
                            <option data-title="Alaska" value="2">Alaska
                            </option>
                            <option data-title="American Samoa" value="3">American Samoa
                            </option>
                            <option data-title="Arizona" value="4">Arizona
                            </option>
                            <option data-title="Arkansas" value="5">Arkansas
                            </option>
                            <option data-title="Armed Forces Africa" value="6">Armed Forces Africa
                            </option>
                            <option data-title="Armed Forces Americas" value="7">Armed Forces Americas
                            </option>
                            <option data-title="Armed Forces Canada" value="8">Armed Forces Canada
                            </option>
                            <option data-title="Armed Forces Europe" value="9">Armed Forces Europe
                            </option>
                            <option data-title="Armed Forces Middle East" value="10">Armed Forces Middle East
                            </option>
                            <option data-title="Armed Forces Pacific" value="11">Armed Forces Pacific
                            </option>
                            <option data-title="California" value="12">California
                            </option>
                            <option data-title="Colorado" value="13">Colorado
                            </option>
                            <option data-title="Connecticut" value="14">Connecticut
                            </option>
                            <option data-title="Delaware" value="15">Delaware
                            </option>
                            <option data-title="District of Columbia" value="16">District of Columbia
                            </option>
                            <option data-title="Federated States Of Micronesia" value="17">Federated States Of Micronesia
                            </option>
                            <option data-title="Florida" value="18">Florida
                            </option>
                            <option data-title="Georgia" value="19">Georgia
                            </option>
                            <option data-title="Guam" value="20">Guam
                            </option>
                            <option data-title="Hawaii" value="21">Hawaii
                            </option>
                            <option data-title="Idaho" value="22">Idaho
                            </option>
                            <option data-title="Illinois" value="23">Illinois
                            </option>
                            <option data-title="Indiana" value="24">Indiana
                            </option>
                            <option data-title="Iowa" value="25">Iowa
                            </option>
                            <option data-title="Kansas" value="26">Kansas
                            </option>
                            <option data-title="Kentucky" value="27">Kentucky
                            </option>
                            <option data-title="Louisiana" value="28">Louisiana
                            </option>
                            <option data-title="Maine" value="29">Maine
                            </option>
                            <option data-title="Marshall Islands" value="30">Marshall Islands
                            </option>
                            <option data-title="Maryland" value="31">Maryland
                            </option>
                            <option data-title="Massachusetts" value="32">Massachusetts
                            </option>
                            <option data-title="Michigan" value="33">Michigan
                            </option>
                            <option data-title="Minnesota" value="34">Minnesota
                            </option>
                            <option data-title="Mississippi" value="35">Mississippi
                            </option>
                            <option data-title="Missouri" value="36">Missouri
                            </option>
                            <option data-title="Montana" value="37">Montana
                            </option>
                            <option data-title="Nebraska" value="38">Nebraska
                            </option>
                            <option data-title="Nevada" value="39">Nevada
                            </option>
                            <option data-title="New Hampshire" value="40">New Hampshire
                            </option>
                            <option data-title="New Jersey" value="41">New Jersey
                            </option>
                            <option data-title="New Mexico" value="42">New Mexico
                            </option>
                            <option data-title="New York" value="43" selected>New York
                            </option>
                            <option data-title="North Carolina" value="44">North Carolina
                            </option>
                            <option data-title="North Dakota" value="45">North Dakota
                            </option>
                            <option data-title="Northern Mariana Islands" value="46">Northern Mariana Islands
                            </option>
                            <option data-title="Ohio" value="47">Ohio
                            </option>
                            <option data-title="Oklahoma" value="48">Oklahoma
                            </option>
                            <option data-title="Oregon" value="49">Oregon
                            </option>
                            <option data-title="Palau" value="50">Palau
                            </option>
                            <option data-title="Pennsylvania" value="51">Pennsylvania
                            </option>
                            <option data-title="Puerto Rico" value="52">Puerto Rico
                            </option>
                            <option data-title="Rhode Island" value="53">Rhode Island
                            </option>
                            <option data-title="South Carolina" value="54">South Carolina
                            </option>
                            <option data-title="South Dakota" value="55">South Dakota
                            </option>
                            <option data-title="Tennessee" value="56">Tennessee
                            </option>
                            <option data-title="Texas" value="57">Texas
                            </option>
                            <option data-title="Utah" value="58">Utah
                            </option>
                            <option data-title="Vermont" value="59">Vermont
                            </option>
                            <option data-title="Virgin Islands" value="60">Virgin Islands
                            </option>
                            <option data-title="Virginia" value="61">Virginia
                            </option>
                            <option data-title="Washington" value="62">Washington
                            </option>
                            <option data-title="West Virginia" value="63">West Virginia
                            </option>
                            <option data-title="Wisconsin" value="64">Wisconsin
                            </option>
                            <option data-title="Wyoming" value="65">Wyoming
                            </option>
                        </select>
                        <!-- /ko -->
                        <!-- /ko -->
                        <!-- ko if: element.hasAddons() -->
                        <!-- /ko -->
                        <!-- ko if: element.tooltip -->
                        <!-- /ko -->
                        <!-- ko if: element.notice -->
                        <!-- /ko -->
                        <!-- ko if: element.error() -->
                        <!-- /ko -->
                        <!-- ko if: element.warn() -->
                        <!-- /ko -->
                        <label class="label" data-bind="attr: { for: element.uid }" for="E9ISGXO">
                            <!-- ko if: element.label -->
                            <span data-bind="i18n: element.label">State/Province
        </span>
                            <!-- /ko -->
                        </label>
                    </div>
                </div>
                <!-- /ko -->
                <!-- /ko -->
                <!-- /ko -->
                <!-- ko if: hasTemplate() -->
                <!-- ko template: getTemplate() -->
                <div class="field _required" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.region" style="display: none;">
                    <label class="label" data-bind="attr: { for: element.uid }" for="B8UDNT4">
                        <!-- ko if: element.label -->
                        <span data-bind="i18n: element.label">State/Province
        </span>
                        <!-- /ko -->
                    </label>
                    <div class="control" data-bind="css: {'_with-tooltip': element.tooltip}">
                        <!-- ko ifnot: element.hasAddons() -->
                        <!-- ko template: element.elementTmpl -->
                        <input class="input-text" type="text" data-bind="
                                                         value: value,
                                                         valueUpdate: 'keyup',
                                                         hasFocus: focused,
                                                         attr: {
                                                         name: inputName,
                                                         placeholder: placeholder,
                                                         'aria-describedby': getDescriptionId(),
                                                         'aria-required': required,
                                                         'aria-invalid': error() ? true : 'false',
                                                         id: uid,
                                                         disabled: disabled
                                                         }" name="region" aria-required="true" aria-invalid="false" id="B8UDNT4" required>
                        <!-- /ko -->
                        <!-- /ko -->
                        <!-- ko if: element.hasAddons() -->
                        <!-- /ko -->
                        <!-- ko if: element.tooltip -->
                        <!-- /ko -->
                        <!-- ko if: element.notice -->
                        <!-- /ko -->
                        <!-- ko if: element.error() -->
                        <!-- /ko -->
                        <!-- ko if: element.warn() -->
                        <!-- /ko -->
                        <label class="label" data-bind="attr: { for: element.uid }" for="B8UDNT4">
                            <!-- ko if: element.label -->
                            <span data-bind="i18n: element.label">State/Province
        </span>
                            <!-- /ko -->
                        </label>
                    </div>
                </div>
                <!-- /ko -->
                <!-- /ko -->
                <!-- /ko -->
                <!-- ko if: hasTemplate() -->
                <!-- ko template: getTemplate() -->
                <div class="field _required" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.postcode">
                    <label class="label" data-bind="attr: { for: element.uid }" for="OBVAL5Q">
                        <!-- ko if: element.label -->
                        <span data-bind="i18n: element.label">Zip/Postal Code
        </span>
                        <!-- /ko -->
                    </label>
                    <div class="control" data-bind="css: {'_with-tooltip': element.tooltip}">
                        <!-- ko ifnot: element.hasAddons() -->
                        <!-- ko template: element.elementTmpl -->
                        <input class="input-text" type="text" data-bind="
                                                         value: value,
                                                         valueUpdate: 'keyup',
                                                         hasFocus: focused,
                                                         attr: {
                                                         name: inputName,
                                                         placeholder: placeholder,
                                                         'aria-describedby': getDescriptionId(),
                                                         'aria-required': required,
                                                         'aria-invalid': error() ? true : 'false',
                                                         id: uid,
                                                         disabled: disabled
                                                         }" name="postcode" aria-required="true" aria-invalid="false" id="OBVAL5Q" required>
                        <!-- /ko -->
                        <!-- /ko -->
                        <!-- ko if: element.hasAddons() -->
                        <!-- /ko -->
                        <!-- ko if: element.tooltip -->
                        <!-- /ko -->
                        <!-- ko if: element.notice -->
                        <!-- /ko -->
                        <!-- ko if: element.error() -->
                        <!-- /ko -->
                        <!-- ko if: element.warn() -->
                        <!-- /ko -->
                        <label class="label" data-bind="attr: { for: element.uid }" for="OBVAL5Q">
                            <!-- ko if: element.label -->
                            <span data-bind="i18n: element.label">Zip/Postal Code
        </span>
                            <!-- /ko -->
                        </label>
                    </div>
                </div>
                <!-- /ko -->
                <!-- /ko -->
                <!-- /ko -->
                <!-- ko if: hasTemplate() -->
                <!-- ko template: getTemplate() -->
                <div class="field _required" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.country_id">
                    <label class="label" data-bind="attr: { for: element.uid }" for="TER9JNG">
                        <!-- ko if: element.label -->
                        <span data-bind="i18n: element.label">Country
        </span>
                        <!-- /ko -->
                    </label>
                    <div class="control" data-bind="css: {'_with-tooltip': element.tooltip}">
                        <!-- ko ifnot: element.hasAddons() -->
                        <!-- ko template: element.elementTmpl -->
                        <select class="select" data-bind="
                                          attr: {
                                          name: inputName,
                                          id: uid,
                                          disabled: disabled,
                                          'aria-describedby': getDescriptionId(),
                                          'aria-required': required,
                                          'aria-invalid': error() ? true : 'false',
                                          placeholder: placeholder
                                          },
                                          hasFocus: focused,
                                          optgroup: options,
                                          value: value,
                                          optionsCaption: caption,
                                          optionsValue: 'value',
                                          optionsText: 'label',
                                          optionsAfterRender: function(option, item) {
                                          if (item &amp;&amp; item.disabled) {
                                          ko.applyBindingsToNode(option, {attr: {disabled: true}}, item);
                                          }
                                          }" name="country_id" id="TER9JNG" aria-required="true" aria-invalid="false">
                            <option value="">
                            </option>
                            <option data-title="Afghanistan" value="AF">Afghanistan
                            </option>
                            <option data-title="Albania" value="AL">Albania
                            </option>
                            <option data-title="Algeria" value="DZ">Algeria
                            </option>
                            <option data-title="American Samoa" value="AS" selected>American Samoa
                            </option>
                            <option data-title="Andorra" value="AD">Andorra
                            </option>
                            <option data-title="Angola" value="AO">Angola
                            </option>
                            <option data-title="Anguilla" value="AI">Anguilla
                            </option>
                            <option data-title="Antarctica" value="AQ">Antarctica
                            </option>
                            <option data-title="Antigua and Barbuda" value="AG">Antigua and Barbuda
                            </option>
                            <option data-title="Argentina" value="AR">Argentina
                            </option>
                            <option data-title="Armenia" value="AM">Armenia
                            </option>
                            <option data-title="Aruba" value="AW">Aruba
                            </option>
                            <option data-title="Australia" value="AU">Australia
                            </option>
                            <option data-title="Austria" value="AT">Austria
                            </option>
                            <option data-title="Azerbaijan" value="AZ">Azerbaijan
                            </option>
                            <option data-title="Bahamas" value="BS">Bahamas
                            </option>
                            <option data-title="Bahrain" value="BH">Bahrain
                            </option>
                            <option data-title="Bangladesh" value="BD">Bangladesh
                            </option>
                            <option data-title="Barbados" value="BB">Barbados
                            </option>
                            <option data-title="Belarus" value="BY">Belarus
                            </option>
                            <option data-title="Belgium" value="BE">Belgium
                            </option>
                            <option data-title="Belize" value="BZ">Belize
                            </option>
                            <option data-title="Benin" value="BJ">Benin
                            </option>
                            <option data-title="Bermuda" value="BM">Bermuda
                            </option>
                            <option data-title="Bhutan" value="BT">Bhutan
                            </option>
                            <option data-title="Bolivia" value="BO">Bolivia
                            </option>
                            <option data-title="Bosnia and Herzegovina" value="BA">Bosnia and Herzegovina
                            </option>
                            <option data-title="Botswana" value="BW">Botswana
                            </option>
                            <option data-title="Bouvet Island" value="BV">Bouvet Island
                            </option>
                            <option data-title="Brazil" value="BR">Brazil
                            </option>
                            <option data-title="British Indian Ocean Territory" value="IO">British Indian Ocean Territory
                            </option>
                            <option data-title="British Virgin Islands" value="VG">British Virgin Islands
                            </option>
                            <option data-title="Brunei" value="BN">Brunei
                            </option>
                            <option data-title="Bulgaria" value="BG">Bulgaria
                            </option>
                            <option data-title="Burkina Faso" value="BF">Burkina Faso
                            </option>
                            <option data-title="Burundi" value="BI">Burundi
                            </option>
                            <option data-title="Cambodia" value="KH">Cambodia
                            </option>
                            <option data-title="Cameroon" value="CM">Cameroon
                            </option>
                            <option data-title="Canada" value="CA">Canada
                            </option>
                            <option data-title="Cape Verde" value="CV">Cape Verde
                            </option>
                            <option data-title="Cayman Islands" value="KY">Cayman Islands
                            </option>
                            <option data-title="Central African Republic" value="CF">Central African Republic
                            </option>
                            <option data-title="Chad" value="TD">Chad
                            </option>
                            <option data-title="Chile" value="CL">Chile
                            </option>
                            <option data-title="China" value="CN">China
                            </option>
                            <option data-title="Christmas Island" value="CX">Christmas Island
                            </option>
                            <option data-title="Cocos [Keeling] Islands" value="CC">Cocos [Keeling] Islands
                            </option>
                            <option data-title="Colombia" value="CO">Colombia
                            </option>
                            <option data-title="Comoros" value="KM">Comoros
                            </option>
                            <option data-title="Congo - Brazzaville" value="CG">Congo - Brazzaville
                            </option>
                            <option data-title="Congo - Kinshasa" value="CD">Congo - Kinshasa
                            </option>
                            <option data-title="Cook Islands" value="CK">Cook Islands
                            </option>
                            <option data-title="Costa Rica" value="CR">Costa Rica
                            </option>
                            <option data-title="Croatia" value="HR">Croatia
                            </option>
                            <option data-title="Cuba" value="CU">Cuba
                            </option>
                            <option data-title="Cyprus" value="CY">Cyprus
                            </option>
                            <option data-title="Czech Republic" value="CZ">Czech Republic
                            </option>
                            <option data-title="Côte d’Ivoire" value="CI">Côte d’Ivoire
                            </option>
                            <option data-title="Denmark" value="DK">Denmark
                            </option>
                            <option data-title="Djibouti" value="DJ">Djibouti
                            </option>
                            <option data-title="Dominica" value="DM">Dominica
                            </option>
                            <option data-title="Dominican Republic" value="DO">Dominican Republic
                            </option>
                            <option data-title="Ecuador" value="EC">Ecuador
                            </option>
                            <option data-title="Egypt" value="EG">Egypt
                            </option>
                            <option data-title="El Salvador" value="SV">El Salvador
                            </option>
                            <option data-title="Equatorial Guinea" value="GQ">Equatorial Guinea
                            </option>
                            <option data-title="Eritrea" value="ER">Eritrea
                            </option>
                            <option data-title="Estonia" value="EE">Estonia
                            </option>
                            <option data-title="Ethiopia" value="ET">Ethiopia
                            </option>
                            <option data-title="Falkland Islands" value="FK">Falkland Islands
                            </option>
                            <option data-title="Faroe Islands" value="FO">Faroe Islands
                            </option>
                            <option data-title="Fiji" value="FJ">Fiji
                            </option>
                            <option data-title="Finland" value="FI">Finland
                            </option>
                            <option data-title="France" value="FR">France
                            </option>
                            <option data-title="French Guiana" value="GF">French Guiana
                            </option>
                            <option data-title="French Polynesia" value="PF">French Polynesia
                            </option>
                            <option data-title="French Southern Territories" value="TF">French Southern Territories
                            </option>
                            <option data-title="Gabon" value="GA">Gabon
                            </option>
                            <option data-title="Gambia" value="GM">Gambia
                            </option>
                            <option data-title="Georgia" value="GE">Georgia
                            </option>
                            <option data-title="Germany" value="DE">Germany
                            </option>
                            <option data-title="Ghana" value="GH">Ghana
                            </option>
                            <option data-title="Gibraltar" value="GI">Gibraltar
                            </option>
                            <option data-title="Greece" value="GR">Greece
                            </option>
                            <option data-title="Greenland" value="GL">Greenland
                            </option>
                            <option data-title="Grenada" value="GD">Grenada
                            </option>
                            <option data-title="Guadeloupe" value="GP">Guadeloupe
                            </option>
                            <option data-title="Guam" value="GU">Guam
                            </option>
                            <option data-title="Guatemala" value="GT">Guatemala
                            </option>
                            <option data-title="Guernsey" value="GG">Guernsey
                            </option>
                            <option data-title="Guinea" value="GN">Guinea
                            </option>
                            <option data-title="Guinea-Bissau" value="GW">Guinea-Bissau
                            </option>
                            <option data-title="Guyana" value="GY">Guyana
                            </option>
                            <option data-title="Haiti" value="HT">Haiti
                            </option>
                            <option data-title="Heard Island and McDonald Islands" value="HM">Heard Island and McDonald Islands
                            </option>
                            <option data-title="Honduras" value="HN">Honduras
                            </option>
                            <option data-title="Hong Kong SAR China" value="HK">Hong Kong SAR China
                            </option>
                            <option data-title="Hungary" value="HU">Hungary
                            </option>
                            <option data-title="Iceland" value="IS">Iceland
                            </option>
                            <option data-title="India" value="IN">India
                            </option>
                            <option data-title="Indonesia" value="ID">Indonesia
                            </option>
                            <option data-title="Iran" value="IR">Iran
                            </option>
                            <option data-title="Iraq" value="IQ">Iraq
                            </option>
                            <option data-title="Ireland" value="IE">Ireland
                            </option>
                            <option data-title="Isle of Man" value="IM">Isle of Man
                            </option>
                            <option data-title="Israel" value="IL">Israel
                            </option>
                            <option data-title="Italy" value="IT">Italy
                            </option>
                            <option data-title="Jamaica" value="JM">Jamaica
                            </option>
                            <option data-title="Japan" value="JP">Japan
                            </option>
                            <option data-title="Jersey" value="JE">Jersey
                            </option>
                            <option data-title="Jordan" value="JO">Jordan
                            </option>
                            <option data-title="Kazakhstan" value="KZ">Kazakhstan
                            </option>
                            <option data-title="Kenya" value="KE">Kenya
                            </option>
                            <option data-title="Kiribati" value="KI">Kiribati
                            </option>
                            <option data-title="Kuwait" value="KW">Kuwait
                            </option>
                            <option data-title="Kyrgyzstan" value="KG">Kyrgyzstan
                            </option>
                            <option data-title="Laos" value="LA">Laos
                            </option>
                            <option data-title="Latvia" value="LV">Latvia
                            </option>
                            <option data-title="Lebanon" value="LB">Lebanon
                            </option>
                            <option data-title="Lesotho" value="LS">Lesotho
                            </option>
                            <option data-title="Liberia" value="LR">Liberia
                            </option>
                            <option data-title="Libya" value="LY">Libya
                            </option>
                            <option data-title="Liechtenstein" value="LI">Liechtenstein
                            </option>
                            <option data-title="Lithuania" value="LT">Lithuania
                            </option>
                            <option data-title="Luxembourg" value="LU">Luxembourg
                            </option>
                            <option data-title="Macau SAR China" value="MO">Macau SAR China
                            </option>
                            <option data-title="Macedonia" value="MK">Macedonia
                            </option>
                            <option data-title="Madagascar" value="MG">Madagascar
                            </option>
                            <option data-title="Malawi" value="MW">Malawi
                            </option>
                            <option data-title="Malaysia" value="MY">Malaysia
                            </option>
                            <option data-title="Maldives" value="MV">Maldives
                            </option>
                            <option data-title="Mali" value="ML">Mali
                            </option>
                            <option data-title="Malta" value="MT">Malta
                            </option>
                            <option data-title="Marshall Islands" value="MH">Marshall Islands
                            </option>
                            <option data-title="Martinique" value="MQ">Martinique
                            </option>
                            <option data-title="Mauritania" value="MR">Mauritania
                            </option>
                            <option data-title="Mauritius" value="MU">Mauritius
                            </option>
                            <option data-title="Mayotte" value="YT">Mayotte
                            </option>
                            <option data-title="Mexico" value="MX">Mexico
                            </option>
                            <option data-title="Micronesia" value="FM">Micronesia
                            </option>
                            <option data-title="Moldova" value="MD">Moldova
                            </option>
                            <option data-title="Monaco" value="MC">Monaco
                            </option>
                            <option data-title="Mongolia" value="MN">Mongolia
                            </option>
                            <option data-title="Montenegro" value="ME">Montenegro
                            </option>
                            <option data-title="Montserrat" value="MS">Montserrat
                            </option>
                            <option data-title="Morocco" value="MA">Morocco
                            </option>
                            <option data-title="Mozambique" value="MZ">Mozambique
                            </option>
                            <option data-title="Myanmar [Burma]" value="MM">Myanmar [Burma]
                            </option>
                            <option data-title="Namibia" value="NA">Namibia
                            </option>
                            <option data-title="Nauru" value="NR">Nauru
                            </option>
                            <option data-title="Nepal" value="NP">Nepal
                            </option>
                            <option data-title="Netherlands" value="NL">Netherlands
                            </option>
                            <option data-title="Netherlands Antilles" value="AN">Netherlands Antilles
                            </option>
                            <option data-title="New Caledonia" value="NC">New Caledonia
                            </option>
                            <option data-title="New Zealand" value="NZ">New Zealand
                            </option>
                            <option data-title="Nicaragua" value="NI">Nicaragua
                            </option>
                            <option data-title="Niger" value="NE">Niger
                            </option>
                            <option data-title="Nigeria" value="NG">Nigeria
                            </option>
                            <option data-title="Niue" value="NU">Niue
                            </option>
                            <option data-title="Norfolk Island" value="NF">Norfolk Island
                            </option>
                            <option data-title="North Korea" value="KP">North Korea
                            </option>
                            <option data-title="Northern Mariana Islands" value="MP">Northern Mariana Islands
                            </option>
                            <option data-title="Norway" value="NO">Norway
                            </option>
                            <option data-title="Oman" value="OM">Oman
                            </option>
                            <option data-title="Pakistan" value="PK">Pakistan
                            </option>
                            <option data-title="Palau" value="PW">Palau
                            </option>
                            <option data-title="Palestinian Territories" value="PS">Palestinian Territories
                            </option>
                            <option data-title="Panama" value="PA">Panama
                            </option>
                            <option data-title="Papua New Guinea" value="PG">Papua New Guinea
                            </option>
                            <option data-title="Paraguay" value="PY">Paraguay
                            </option>
                            <option data-title="Peru" value="PE">Peru
                            </option>
                            <option data-title="Philippines" value="PH">Philippines
                            </option>
                            <option data-title="Pitcairn Islands" value="PN">Pitcairn Islands
                            </option>
                            <option data-title="Poland" value="PL">Poland
                            </option>
                            <option data-title="Portugal" value="PT">Portugal
                            </option>
                            <option data-title="Qatar" value="QA">Qatar
                            </option>
                            <option data-title="Romania" value="RO">Romania
                            </option>
                            <option data-title="Russia" value="RU">Russia
                            </option>
                            <option data-title="Rwanda" value="RW">Rwanda
                            </option>
                            <option data-title="Réunion" value="RE">Réunion
                            </option>
                            <option data-title="Saint Barthélemy" value="BL">Saint Barthélemy
                            </option>
                            <option data-title="Saint Helena" value="SH">Saint Helena
                            </option>
                            <option data-title="Saint Kitts and Nevis" value="KN">Saint Kitts and Nevis
                            </option>
                            <option data-title="Saint Lucia" value="LC">Saint Lucia
                            </option>
                            <option data-title="Saint Martin" value="MF">Saint Martin
                            </option>
                            <option data-title="Saint Pierre and Miquelon" value="PM">Saint Pierre and Miquelon
                            </option>
                            <option data-title="Saint Vincent and the Grenadines" value="VC">Saint Vincent and the Grenadines
                            </option>
                            <option data-title="Samoa" value="WS">Samoa
                            </option>
                            <option data-title="San Marino" value="SM">San Marino
                            </option>
                            <option data-title="Saudi Arabia" value="SA">Saudi Arabia
                            </option>
                            <option data-title="Senegal" value="SN">Senegal
                            </option>
                            <option data-title="Serbia" value="RS">Serbia
                            </option>
                            <option data-title="Seychelles" value="SC">Seychelles
                            </option>
                            <option data-title="Sierra Leone" value="SL">Sierra Leone
                            </option>
                            <option data-title="Singapore" value="SG">Singapore
                            </option>
                            <option data-title="Slovakia" value="SK">Slovakia
                            </option>
                            <option data-title="Slovenia" value="SI">Slovenia
                            </option>
                            <option data-title="Solomon Islands" value="SB">Solomon Islands
                            </option>
                            <option data-title="Somalia" value="SO">Somalia
                            </option>
                            <option data-title="South Africa" value="ZA">South Africa
                            </option>
                            <option data-title="South Georgia and the South Sandwich Islands" value="GS">South Georgia and the South Sandwich Islands
                            </option>
                            <option data-title="South Korea" value="KR">South Korea
                            </option>
                            <option data-title="Spain" value="ES">Spain
                            </option>
                            <option data-title="Sri Lanka" value="LK">Sri Lanka
                            </option>
                            <option data-title="Sudan" value="SD">Sudan
                            </option>
                            <option data-title="Suriname" value="SR">Suriname
                            </option>
                            <option data-title="Svalbard and Jan Mayen" value="SJ">Svalbard and Jan Mayen
                            </option>
                            <option data-title="Swaziland" value="SZ">Swaziland
                            </option>
                            <option data-title="Sweden" value="SE">Sweden
                            </option>
                            <option data-title="Switzerland" value="CH">Switzerland
                            </option>
                            <option data-title="Syria" value="SY">Syria
                            </option>
                            <option data-title="São Tomé and Príncipe" value="ST">São Tomé and Príncipe
                            </option>
                            <option data-title="Taiwan" value="TW">Taiwan
                            </option>
                            <option data-title="Tajikistan" value="TJ">Tajikistan
                            </option>
                            <option data-title="Tanzania" value="TZ">Tanzania
                            </option>
                            <option data-title="Thailand" value="TH">Thailand
                            </option>
                            <option data-title="Timor-Leste" value="TL">Timor-Leste
                            </option>
                            <option data-title="Togo" value="TG">Togo
                            </option>
                            <option data-title="Tokelau" value="TK">Tokelau
                            </option>
                            <option data-title="Tonga" value="TO">Tonga
                            </option>
                            <option data-title="Trinidad and Tobago" value="TT">Trinidad and Tobago
                            </option>
                            <option data-title="Tunisia" value="TN">Tunisia
                            </option>
                            <option data-title="Turkey" value="TR">Turkey
                            </option>
                            <option data-title="Turkmenistan" value="TM">Turkmenistan
                            </option>
                            <option data-title="Turks and Caicos Islands" value="TC">Turks and Caicos Islands
                            </option>
                            <option data-title="Tuvalu" value="TV">Tuvalu
                            </option>
                            <option data-title="U.S. Outlying Islands" value="UM">U.S. Outlying Islands
                            </option>
                            <option data-title="U.S. Virgin Islands" value="VI">U.S. Virgin Islands
                            </option>
                            <option data-title="Uganda" value="UG">Uganda
                            </option>
                            <option data-title="Ukraine" value="UA">Ukraine
                            </option>
                            <option data-title="United Arab Emirates" value="AE">United Arab Emirates
                            </option>
                            <option data-title="United Kingdom" value="GB">United Kingdom
                            </option>
                            <option data-title="United States" value="US">United States
                            </option>
                            <option data-title="Uruguay" value="UY">Uruguay
                            </option>
                            <option data-title="Uzbekistan" value="UZ">Uzbekistan
                            </option>
                            <option data-title="Vanuatu" value="VU">Vanuatu
                            </option>
                            <option data-title="Vatican City" value="VA">Vatican City
                            </option>
                            <option data-title="Venezuela" value="VE">Venezuela
                            </option>
                            <option data-title="Vietnam" value="VN">Vietnam
                            </option>
                            <option data-title="Wallis and Futuna" value="WF">Wallis and Futuna
                            </option>
                            <option data-title="Western Sahara" value="EH">Western Sahara
                            </option>
                            <option data-title="Yemen" value="YE">Yemen
                            </option>
                            <option data-title="Zambia" value="ZM">Zambia
                            </option>
                            <option data-title="Zimbabwe" value="ZW">Zimbabwe
                            </option>
                            <option data-title="Åland Islands" value="AX">Åland Islands
                            </option>
                        </select>
                        <!-- /ko -->
                        <!-- /ko -->
                        <!-- ko if: element.hasAddons() -->
                        <!-- /ko -->
                        <!-- ko if: element.tooltip -->
                        <!-- /ko -->
                        <!-- ko if: element.notice -->
                        <!-- /ko -->
                        <!-- ko if: element.error() -->
                        <!-- /ko -->
                        <!-- ko if: element.warn() -->
                        <!-- /ko -->
                        <label class="label" data-bind="attr: { for: element.uid }" for="TER9JNG">
                            <!-- ko if: element.label -->
                            <span data-bind="i18n: element.label">Country
        </span>
                            <!-- /ko -->
                        </label>
                    </div>
                </div>
                <!-- /ko -->
                <!-- /ko -->
                <!-- /ko -->
                <!-- ko if: hasTemplate() -->
                <!-- ko template: getTemplate() -->
                <div class="field _required" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="shippingAddress.telephone">
                    <label class="label" data-bind="attr: { for: element.uid }" for="FYFO1XS">
                        <!-- ko if: element.label -->
                        <span data-bind="i18n: element.label">Phone Number
        </span>
                        <!-- /ko -->
                    </label>
                    <div class="control _with-tooltip" data-bind="css: {'_with-tooltip': element.tooltip}">
                        <!-- ko ifnot: element.hasAddons() -->
                        <!-- ko template: element.elementTmpl -->
                        <input class="input-text" type="text" data-bind="
                                                         value: value,
                                                         valueUpdate: 'keyup',
                                                         hasFocus: focused,
                                                         attr: {
                                                         name: inputName,
                                                         placeholder: placeholder,
                                                         'aria-describedby': getDescriptionId(),
                                                         'aria-required': required,
                                                         'aria-invalid': error() ? true : 'false',
                                                         id: uid,
                                                         disabled: disabled
                                                         }" name="telephone" aria-required="true" aria-invalid="false" id="FYFO1XS" required>
                        <!-- /ko -->
                        <!-- /ko -->
                        <!-- ko if: element.hasAddons() -->
                        <!-- /ko -->
                        <!-- ko if: element.tooltip -->
                        <!-- ko template: element.tooltipTpl -->
                        <div class="field-tooltip toggle">
                            <!-- ko if: (tooltip.link)-->
                            <!-- /ko -->
                            <!-- ko if: (!tooltip.link)-->
                            <span class="field-tooltip-action action-help" tabindex="0" data-toggle="dropdown" data-bind="mageInit: {'dropdown':{'activeClass': '_active'}}" aria-haspopup="true" aria-expanded="false" role="button">
          </span>
                            <!-- /ko -->
                            <div style="display:block;" class="field-tooltip-content" data-target="dropdown" data-bind="i18n: tooltip.description" aria-hidden="true">For delivery questions.
                            </div>
                        </div>
                        <!-- /ko -->
                        <!-- /ko -->
                        <!-- ko if: element.notice -->
                        <!-- /ko -->
                        <!-- ko if: element.error() -->
                        <!-- /ko -->
                        <!-- ko if: element.warn() -->
                        <!-- /ko -->
                        <label class="label" data-bind="attr: { for: element.uid }" for="FYFO1XS">
                            <!-- ko if: element.label -->
                            <span data-bind="i18n: element.label">Phone Number
        </span>
                            <!-- /ko -->
                        </label>
                    </div>
                </div>
                <!-- /ko -->
                <!-- /ko -->
                <!-- /ko -->
                <!-- /ko -->
                <!-- /ko -->
                <!--/ko-->
                <!-- ko if: (isCustomerLoggedIn) -->
                <!-- /ko -->



                    <label class="label">
                        <span></span>
                    </label>
                    <div class="control">
                        <input type="checkbox" name="checkbox__name" checked="checked" id="checkbox__name">
                        <label class="label" for="checkbox__name">
                            <span>Make Default</span>
                        </label>
                    </div>
                </div>
                <div class="field choice">
                    <label class="label">
                        <span></span>
                    </label>
                    <div class="control">
                        <input type="checkbox" name="checkbox__name" id="checkbox__name1">
                        <label class="label" for="checkbox__name1">
                            <span>Second Checkbox</span>
                        </label>
                    </div>
                </div>
                <div class="field choice">
                    <label class="label">
                        <span></span>
                    </label>
                    <div class="control">
                        <input type="checkbox" name="checkbox__name" disabled="disabled" id="checkbox__name3">
                        <label class="label" for="checkbox__name3">
                            <span>Checkbox Disabled</span>
                        </label>
                    </div>
                </div>
                <div class="field choice">
                    <label class="label">
                        <span></span>
                    </label>
                    <div class="control">
                        <input type="checkbox" id="checkbox__name2"  name="checkbox__name"/>
                        <label class="label" for="checkbox__name2"><span>Subscribe for Balance Updates</span></label>
                    </div>
                </div>
                <div class="field choice review-field-rating">
                    <label class="label">
                        <span></span>
                    </label>
                    <div class="control">
                        <input type="radio" class="radio" name="radio-start" id="radio-1">
                        <label class="rating-1" for="radio-1">
                            <span>1 star</span>
                        </label>
                        <input type="radio" class="radio" name="radio-start" id="radio-2">
                        <label class="rating-1" for="radio-2">
                            <span>2 star</span>
                        </label>
                        <input type="radio" class="radio" name="radio-start" id="radio-3">
                        <label class="rating-1" for="radio-3">
                            <span>3 star</span>
                        </label>

                        <input type="radio" class="radio" name="radio-start" id="radio-4" disabled="disabled">
                        <label class="rating-1" for="radio-4">
                            <span>Radio Disabled</span>
                        </label>
                    </div>
                </div>
                <div class="field type">
                    <label class="label"><span>Gift Registry Type</span></label>
                    <div class="control">
                        <select class="select">
                            <option>Select Option</option>
                            <option>Option</option>
                        </select>
                        <div class="note">For better search results, first choose a gift registry type. By default, we search all registry types.</div>
                        <label class="label"><span>Gift Registry Type</span></label>
                    </div>
                </div>
            </div>
        </form>
    </section>

    <h3>Message</h3>
    <section>
        <div class="messages">
            <div class="message-success success message">
                <div>You added Diva Gym Tee to your shopping cart.</div>
            </div>
        </div>
        <div class="messages">
            <div class="message-error error message">
                <div>
                    Error Message - Lorem ipsum dolor sit <a href="#">amet</a>, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
                </div>
            </div>
        </div>
        <div class="messages">
            <div class="message-warning warning message">
                <div>
                    Warning Message - Lorem ipsum dolor sit <a href="#">amet</a>, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
                </div>
            </div>
        </div>
        <div class="messages">
            <div class="message-notice notice message">
                <div>
                    Notice Message - Lorem ipsum dolor sit <a href="#">amet</a>, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
                </div>
            </div>
        </div>
        <div class="messages">
            <div class="message-info info message">
                <div>
                    Info Message - Lorem ipsum dolor sit <a href="#">amet</a>, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
                </div>
            </div>
        </div>

        <div class="message info empty">
            <div>You have no items to compare.</div>
        </div>

        <div class="message warning empty">
            <div>Lorem ipsum dolor sit <a href="#">amet</a>, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.</div>
        </div>

        <div class="page messages">
            <div data-placeholder="messages">
            </div>
            <div>
                <div class="messages">
                    <div class="message-success success message" >
                        <div>Eos V-Neck Hoodie has been added to your Wish List. Click <a>here</a> to continue shopping.</div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <h3>Table</h3>
    <section>
        <small>Table type 1 - without any class [&:extend(.forix-abs-table-reponsive all)]</small>
        <div class="table-wrapper">
            <table>
                <thead>
                <tr>
                    <th scope="col" class="col">Column Heading</th>
                    <th scope="col" class="col">Column Heading</th>
                    <th scope="col" class="col">Column Heading</th>
                    <th scope="col" class="col">Column Heading</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                </tr>
                <tr>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                </tr>
                <tr>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                </tr>
                </tbody>
            </table>
        </div>

        <small>Table type 2 - with class .table [&:extend(forix-abs-data-table-reponsive all)]</small>
        <div class="table-wrapper">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col" class="col">Column Heading</th>
                    <th scope="col" class="col">Column Heading</th>
                    <th scope="col" class="col">Column Heading</th>
                    <th scope="col" class="col">Column Heading</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                </tr>
                <tr>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                </tr>
                <tr>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                    <td data-th="Column Heading" class="col">Table cell content</td>
                </tr>
                </tbody>
            </table>
        </div>
        <small>Table compare</small>
        <div class="table-wrapper comparison">
            <table class="data table table-comparison" id="product-comparison">
                <caption class="table-caption">RunAmoc Style Comparison</caption>
                <thead>
                <tr>
                    <th scope="row" class="cell label"></th>
                    <td class="cell product">Primal</td>
                    <td class="cell product">Dash</td>
                    <td class="cell product">Moc3</td>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row" class="cell label product"><span>Summary</span></th>
                    <td data-th="Product" class="cell product info">
                        <a class="product-item-photo" href="#" title="LifeLong Fitness IV">
                              <span class="product-image-container" style="width:140px;">
                                <span class="product-image-wrapper" style="padding-bottom: 100%;">
                                  <img class="product-image-photo" src="http://softstarshoes/pub/media/catalog/product/cache/2f58bf1051a2f0ceba166b720ec0a490/t/h/thumb_20912_default_news_size_5.jpeg" width="165" height="165" alt="Test">
                                </span>
                              </span>
                        </a>
                        <strong class="product-item-name">
                            <a href="#" title="LifeLong Fitness IV">
                                Extra-wide toe splay for healthy, natural foot function.
                            </a>
                        </strong>
                    </td>
                    <td data-th="Product" class="cell product info">
                        <a class="product-item-photo" href="#" title="LifeLong Fitness IV">
                              <span class="product-image-container" style="width:140px;">
                                <span class="product-image-wrapper" style="padding-bottom: 100%;">
                                  <img class="product-image-photo" src="http://softstarshoes/pub/media/catalog/product/cache/2f58bf1051a2f0ceba166b720ec0a490/t/h/thumb_20912_default_news_size_5.jpeg" width="165" height="165" alt="Test">
                                </span>
                              </span>
                        </a>
                        <strong class="product-item-name">
                            <a href="#" title="LifeLong Fitness IV">
                                Extra-wide toe splay for healthy, natural foot function.
                            </a>
                        </strong>
                    </td>
                    <td data-th="Product" class="cell product info">
                        <a class="product-item-photo" href="#" title="LifeLong Fitness IV">
                              <span class="product-image-container" style="width:140px;">
                                <span class="product-image-wrapper" style="padding-bottom: 100%;">
                                  <img class="product-image-photo" src="http://softstarshoes/pub/media/catalog/product/cache/2f58bf1051a2f0ceba166b720ec0a490/t/h/thumb_20912_default_news_size_5.jpeg" width="165" height="165" alt="Test">
                                </span>
                              </span>
                        </a>
                        <strong class="product-item-name">
                            <a href="#" title="LifeLong Fitness IV">
                                Extra-wide toe splay for healthy, natural foot function.
                            </a>
                        </strong>
                    </td>
                </tr>
                </tbody>
                <tbody>
                <tr>
                    <th scope="row" class="cell label">
                        <span>Feature</span>
                    </th>
                    <td class="cell product attribute">
                        <p>Extra wide toe box. This shoe is widest at the toes, rather than the ball of the foot, and is ideal for people who want to maintain/restore natural foot shape and function.</p>
                        <p>Rubber toe cap, made from upcycled bicycle innertubes, adds durability to front of shoe--especially useful for hikers and trail runners.
                        </p>
                        <p>Extended lacing system is designed to fit snugly around instep, yet allow toes to spread out as much as possible.</p>
                    </td>
                    <td class="cell product attribute">
                        <p>A versatile minimal design that can function as an athletic shoe, a casual shoe or a formal shoe (depending on color choices).</p>
                        <p>
                            Mid-level minimal shoe option for people who do not want the extra-wide toe box of the RunAmoc, but prefer a shoe that is more traditional than the Moc3.
                        </p>
                        <p>Short lacing system allows adjustable fit around the instep while leaving the front of the foot unencumbered.</p>
                    </td>
                    <td class="cell product attribute">
                        <p>Our lightest minimal shoe, and one of the lightest in the world! Designed to be as flexible and lightweight as possible.</p>
                        <p>Easily rolls up and fits into small spaces when not in use, such as a small bag or tucked under a belt.</p>
                        <p>Slip-on design allows quick on/off when you're on the go.</p>
                        <p>Breathe-O-Prene lining hugs your foot from all sides for a snug, but ventilated fit.</p>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="cart table-wrapper">
            <table id="shopping-cart-table" class="cart items data table">
                <caption class="table-caption">Shopping Cart Items</caption>
                <thead>
                <tr>
                    <th class="col" scope="col"><span>Item</span></th>
                    <th class="col" scope="col"><span>Price</span></th>
                    <th class="col" scope="col"><span>Qty</span></th>
                    <th class="col" scope="col"><span>Subtotal</span></th>
                </tr>
                </thead>
                <tbody class="cart item">
                <tr class="item-info">
                    <td data-th="Item" class="col item">
                        <a class="product-item-photo">
                               <span class="product-image-container">
                                   <span class="product-image-wrapper">
                                      <img class="product-image-photo" src="http://softstarshoes/pub/media/catalog/product/cache/2f58bf1051a2f0ceba166b720ec0a490/t/h/thumb_20912_default_news_size_5.jpeg" width="165" height="165" alt="Test">
                                   </span>
                               </span>
                        </a>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a href="http://mage2sb.ee.local/juno-jacket.html">Juno Jacket</a>
                            </strong>
                            <dl class="item-options">
                                <dt>Color</dt>
                                <dd>Purple</dd>
                                <dt>Size</dt>
                                <dd>M</dd>
                            </dl>
                        </div>
                    </td>
                    <td class="col price" data-th="Price">
                           <span class="price-excluding-tax" data-label="Excl. Tax">
                               <span class="cart-price">
                                   <span class="price">$77.00</span>
                               </span>
                           </span>
                    </td>
                    <td class="col qty" data-th="Qty">
                        <div class="field qty">
                            <label class="label" for="cart-68-qty">
                                <span>Qty</span>
                            </label>
                            <div class="control qty">
                                <input class="input-text qty">
                            </div>
                        </div>
                    </td>
                    <td class="col subtotal" data-th="Subtotal">
                           <span class="price-excluding-tax" data-label="Excl. Tax">
                               <span class="cart-price">
                                   <span class="price">$77.00</span>
                               </span>
                           </span>
                    </td>
                </tr>
                <tr class="item-actions">
                    <td colspan="100">
                        <div class="actions-toolbar">
                            <div class="gift-options-cart-item">
                                <a class="action action-gift" >
                                    <span>Gift options</span>
                                </a>
                                <div class="gift-content">
                                    <div class="gift-options">
                                        <div class="gift-wrapping">
                                            <div class="gift-options-title">Pick a paper of your choice (optional)</div>
                                            <div class="gift-options-content">
                                                <ul class="gift-wrapping-list">
                                                    <li class="gift-wrapping-item">
                                                           <span>
                                                            <img class="product-image-photo" src="http://softstarshoes/pub/media/catalog/product/cache/2f58bf1051a2f0ceba166b720ec0a490/t/h/thumb_20912_default_news_size_5.jpeg" width="165" height="165" alt="Test">
                                                           </span>
                                                    </li>
                                                </ul>
                                                <div class="gift-wrapping-preview">
                                                       <span>
                                                       </span>
                                                </div>
                                                <div class="gift-wrapping-title">
                                                    <span class="gift-wrapping-name">Gift Name</span>
                                                    <span class="regular-price">
                                                           <span class="price">$555</span>
                                                       </span>
                                                    <button class="action action-remove">
                                                        <span>Remove</span>
                                                    </button>
                                                </div>
                                                <fieldset class="fieldset">
                                                </fieldset>
                                            </div>
                                        </div>
                                        <div class="actions-toolbar">
                                            <div class="secondary">
                                                <button type="submit" class="action secondary action-update">
                                                    <span>Update</span>
                                                </button>
                                                <button class="action action-cancel">
                                                    <span>Cancel</span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a class="use-ajax action action-towishlist">
                                <span>Move to Wishlist</span>
                            </a>
                            <a class="action action-edit">
                                <span>Edit</span>
                            </a>
                            <a class="action action-delete">
                                <span>Remove</span>
                            </a>
                        </div>
                    </td>
                </tr>
                </tbody>
                <tbody class="cart item">
                <tr class="item-info">
                    <td data-th="Item" class="col item">
                        <a class="product-item-photo">
                               <span class="product-image-container">
                                   <span class="product-image-wrapper">
                                       <img class="product-image-photo" src="http://softstarshoes/pub/media/catalog/product/cache/2f58bf1051a2f0ceba166b720ec0a490/t/h/thumb_20912_default_news_size_5.jpeg" width="165" height="165" alt="Test">
                                   </span>
                               </span>
                        </a>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a href="http://mage2sb.ee.local/juno-jacket.html">Juno Jacket</a>
                            </strong>
                            <dl class="item-options">
                                <dt>Color</dt>
                                <dd>Purple</dd>
                                <dt>Size</dt>
                                <dd>M</dd>
                                <dt>Downloads</dt>
                                <dd>Episode 1<br>Episode 2</dd>                                                            </dd>
                            </dl>
                        </div>
                    </td>
                    <td class="col price" data-th="Price">
                           <span class="price-excluding-tax">
                               <span class="cart-price">
                                   <span class="price">$77.00</span>
                               </span>
                           </span>
                    </td>
                    <td class="col qty" data-th="Qty">
                        <div class="field qty">
                            <label class="label" for="cart-68-qty">
                                <span>Qty</span>
                            </label>
                            <div class="control qty">
                                <input class="input-text qty">
                            </div>
                        </div>
                    </td>
                    <td class="col subtotal" data-th="Subtotal">
                           <span class="price-excluding-tax" data-label="Excl. Tax">
                               <span class="cart-price">
                                   <span class="price">$77.00</span>
                               </span>
                           </span>
                    </td>
                </tr>
                <tr class="item-actions">
                    <td colspan="100">
                        <div class="actions-toolbar">
                            <div class="gift-options-cart-item">
                                <a class="action action-gift" >
                                    <span>Gift options</span>
                                </a>
                            </div>
                            <a class="use-ajax action action-towishlist">
                                <span>Move to Wishlist</span>
                            </a>
                            <a class="action action-edit">
                                <span>Edit</span>
                            </a>
                            <a class="action action-delete">
                                <span>Remove</span>
                            </a>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>


        <div class="table-wrapper orders-recent">
            <table class="data table table-order-items recent" id="my-orders-table">
                <caption class="table-caption">Recent Orders</caption>
                <thead>
                <tr>
                    <th scope="col" class="col id">Order #</th>
                    <th scope="col" class="col date">Date</th>
                    <th scope="col" class="col shipping">Ship To</th>
                    <th scope="col" class="col total">Order Total</th>
                    <th scope="col" class="col status">Status</th>
                    <th scope="col" class="col actions">Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td data-th="Order #" class="col id">000004824</td>
                    <td data-th="Date" class="col date">1/29/18</td>
                    <td data-th="Ship To" class="col shipping">tester tester</td>
                    <td data-th="Order Total" class="col total"><span class="price">$139.50</span></td>
                    <td data-th="Status" class="col status">Pending</td>
                    <td data-th="Actions" class="col actions">
                        <a href="http://magento2-demo.nexcess.net/sales/order/view/order_id/4757/" class="action view">
                            <span>View Order</span>
                        </a>
                        <a href="http://magento2-demo.nexcess.net/sales/order/reorder/order_id/4757/" class="action order">
                            <span>Reorder</span>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td data-th="Order #" class="col id">000004824</td>
                    <td data-th="Date" class="col date">1/29/18</td>
                    <td data-th="Ship To" class="col shipping">tester tester</td>
                    <td data-th="Order Total" class="col total"><span class="price">$139.50</span></td>
                    <td data-th="Status" class="col status">Pending</td>
                    <td data-th="Actions" class="col actions">
                        <a href="http://magento2-demo.nexcess.net/sales/order/view/order_id/4757/" class="action view">
                            <span>View Order</span>
                        </a>
                        <a href="http://magento2-demo.nexcess.net/sales/order/reorder/order_id/4757/" class="action order">
                            <span>Reorder</span>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td data-th="Order #" class="col id">000004824</td>
                    <td data-th="Date" class="col date">1/29/18</td>
                    <td data-th="Ship To" class="col shipping">tester tester</td>
                    <td data-th="Order Total" class="col total"><span class="price">$139.50</span></td>
                    <td data-th="Status" class="col status">Pending</td>
                    <td data-th="Actions" class="col actions">
                        <a href="http://magento2-demo.nexcess.net/sales/order/view/order_id/4757/" class="action view">
                            <span>View Order</span>
                        </a>
                        <a href="http://magento2-demo.nexcess.net/sales/order/reorder/order_id/4757/" class="action order">
                            <span>Reorder</span>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="table-wrapper order-items">
            <table class="data table table-order-items" id="my-orders-table" summary="Items Ordered">
                <caption class="table-caption">Items Ordered
                </caption>
                <thead>
                <tr>
                    <th class="col name">Product Name
                    </th>
                    <th class="col sku">SKU
                    </th>
                    <th class="col price">Price
                    </th>
                    <th class="col qty">Qty
                    </th>
                    <th class="col subtotal">Subtotal
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr id="order-item-row-13166">
                    <td class="col name" data-th="Product Name">
                        <strong class="product name product-item-name">Radiant Tee
                        </strong>
                        <dl class="item-options">
                            <dt>Color
                            </dt>
                            <dd>
                                Orange
                            </dd>
                            <dt>Size
                            </dt>
                            <dd>
                                XS
                            </dd>
                        </dl>
                    </td>
                    <td class="col sku" data-th="SKU">WS12-XS-Orange
                    </td>
                    <td class="col price" data-th="Price">
          <span class="price-excluding-tax" data-label="Excl. Tax">
            <span class="cart-price">
              <span class="price">$22.00
              </span>
            </span>
          </span>
                    </td>
                    <td class="col qty" data-th="Qty">
                        <ul class="items-qty">
                            <li class="item">
              <span class="title">Ordered
              </span>
                                <span class="content">1
              </span>
                            </li>
                        </ul>
                    </td>
                    <td class="col subtotal" data-th="Subtotal">
          <span class="price-excluding-tax" data-label="Excl. Tax">
            <span class="cart-price">
              <span class="price">$22.00
              </span>
            </span>
          </span>
                    </td>
                </tr>
                </tbody>
                <tbody>
                <tr id="order-item-row-13168">
                    <td class="col name" data-th="Product Name">
                        <strong class="product name product-item-name">Breathe-Easy Tank
                        </strong>
                        <dl class="item-options">
                            <dt>Color
                            </dt>
                            <dd>
                                Yellow
                            </dd>
                            <dt>Size
                            </dt>
                            <dd>
                                M
                            </dd>
                        </dl>
                    </td>
                    <td class="col sku" data-th="SKU">WT09-M-Yellow
                    </td>
                    <td class="col price" data-th="Price">
          <span class="price-excluding-tax" data-label="Excl. Tax">
            <span class="cart-price">
              <span class="price">$34.00
              </span>
            </span>
          </span>
                    </td>
                    <td class="col qty" data-th="Qty">
                        <ul class="items-qty">
                            <li class="item">
              <span class="title">Ordered
              </span>
                                <span class="content">1
              </span>
                            </li>
                        </ul>
                    </td>
                    <td class="col subtotal" data-th="Subtotal">
          <span class="price-excluding-tax" data-label="Excl. Tax">
            <span class="cart-price">
              <span class="price">$34.00
              </span>
            </span>
          </span>
                    </td>
                </tr>
                </tbody>
                <tbody>
                <tr id="order-item-row-13170">
                    <td class="col name" data-th="Product Name">
                        <strong class="product name product-item-name">Geo Insulated Jogging Pant
                        </strong>
                        <dl class="item-options">
                            <dt>Color
                            </dt>
                            <dd>
                                Blue
                            </dd>
                            <dt>Size
                            </dt>
                            <dd>
                                32
                            </dd>
                        </dl>
                    </td>
                    <td class="col sku" data-th="SKU">MP03-32-Blue
                    </td>
                    <td class="col price" data-th="Price">
          <span class="price-excluding-tax" data-label="Excl. Tax">
            <span class="cart-price">
              <span class="price">$51.00
              </span>
            </span>
          </span>
                    </td>
                    <td class="col qty" data-th="Qty">
                        <ul class="items-qty">
                            <li class="item">
              <span class="title">Ordered
              </span>
                                <span class="content">1
              </span>
                            </li>
                        </ul>
                    </td>
                    <td class="col subtotal" data-th="Subtotal">
          <span class="price-excluding-tax" data-label="Excl. Tax">
            <span class="cart-price">
              <span class="price">$51.00
              </span>
            </span>
          </span>
                    </td>
                </tr>
                </tbody>
                <tbody>
                <tr id="order-item-row-13172">
                    <td class="col name" data-th="Product Name">
                        <strong class="product name product-item-name">Meteor Workout Short
                        </strong>
                        <dl class="item-options">
                            <dt>Color
                            </dt>
                            <dd>
                                Blue
                            </dd>
                            <dt>Size
                            </dt>
                            <dd>
                                33
                            </dd>
                        </dl>
                    </td>
                    <td class="col sku" data-th="SKU">MSH03-33-Blue
                    </td>
                    <td class="col price" data-th="Price">
          <span class="price-excluding-tax" data-label="Excl. Tax">
            <span class="cart-price">
              <span class="price">$32.50
              </span>
            </span>
          </span>
                    </td>
                    <td class="col qty" data-th="Qty">
                        <ul class="items-qty">
                            <li class="item">
              <span class="title">Ordered
              </span>
                                <span class="content">1
              </span>
                            </li>
                        </ul>
                    </td>
                    <td class="col subtotal" data-th="Subtotal">
          <span class="price-excluding-tax" data-label="Excl. Tax">
            <span class="cart-price">
              <span class="price">$32.50
              </span>
            </span>
          </span>
                    </td>
                </tr>
                </tbody>
                <tfoot>
                <tr class="subtotal">
                    <th colspan="4" class="mark" scope="row">
                        Subtotal
                    </th>
                    <td class="amount" data-th="Subtotal">
          <span class="price">$139.50
          </span>
                    </td>
                </tr>
                <tr class="shipping">
                    <th colspan="4" class="mark" scope="row">
                        Shipping &amp; Handling
                    </th>
                    <td class="amount" data-th="Shipping &amp; Handling">
          <span class="price">$0.00
          </span>
                    </td>
                </tr>
                <tr class="grand_total">
                    <th colspan="4" class="mark" scope="row">
                        <strong>Grand Total
                        </strong>
                    </th>
                    <td class="amount" data-th="Grand Total">
                        <strong>
            <span class="price">$139.50
            </span>
                        </strong>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>


    </section>

    <ul class="photo-gallery">
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-2-2"><div class="img">col 2</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-1-1"><div class="img">col 1</div></li>
        <li class="col-2-2"><div class="img">col 2</div></li>
        <li class="col-2-2"><div class="img">col 2</div></li>
    </ul>
</section>