<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Forix\QuoteLetter\Block\Adminhtml\QuoteLetter\AssignProducts  */

/** @var \Forix\QuoteLetter\Block\Adminhtml\QuoteLetter\Tab\Product $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="product_skus" id="in_quoteletter_products" data-form-part="forix_quoteletter_quoteletter_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "Forix_QuoteLetter/js/quoteletter/assign-products": {
                "selectedProducts": <?= /* @escapeNotVerified */ $block->getProductsJson() ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
