<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<div class="review-list-title">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Customer Reviews') ?></strong>
    </div>
    <?php echo $block->getReviewsSummaryHtml($block->getProduct(), false, true)?>
    <a href="javascript:void(0);" class="action add-review" title="<?php /* @escapeNotVerified */ echo __('Write a Review') ?>" data-mage-init='{"forix/toggle": {"toggleContainers": "#form-review-add", "selectorsToggleClass": "active","touchOutSite":false}}'><span><?php /* @escapeNotVerified */ echo __('Write a Review') ?></span></a>
</div>
