<?php
/**
 * @var $block Forix\ProductWizard\Block\Wizard\Steps
 * @var $group Forix\ProductWizard\Model\Group
 * @var $groupItem Forix\ProductWizard\Model\GroupItem
 * data-next: Dữ liệu để biết được step này sẽ đi tới step nào nếu default.
 */

$groupCollection = $block->getGroups();
?>
<?php if ($groupCollection): ?>
    <?php foreach ($groupCollection as $group): ?>
        <div class="group-content">
            <div class="title" data-bind='afterRender: translateText' data-text="<?php echo $block->escapeHtml(__($group->getTitle())); ?>"></div>
            <?php $groupItems = $group->getGroupItemCollection(); ?>
            <?php foreach ($groupItems as $groupItem): ?>
                <?php echo $block->getGroupItemRenderer($groupItem)->toHtml(); ?>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<div class="step-footer">
    <button class="btn-continue" data-type="next"
            data-step="<?php echo($block->getStepIndex()); ?>"
            data-current="<?php echo($block->getStepIndex() - 1); ?>"
            data-next="<?php echo ($block->getStepNext() ?: $block->getStepIndex()); ?>"
            type="button">
        <span><?php echo __('Continue'); ?></span>
    </button>
</div>