<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$useFancybox = $this->helper('Forix\Base\Helper\Data')->getConfigValue('sendfriend/email/use_fancybox');
$allowGuest = $this->helper('Forix\Base\Helper\Data')->getConfigValue('sendfriend/email/allow_guest');
?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()): ?>
    <div class="at-style-responsive at-resp-share-element at-share-btn-elements">
        <a role="button" href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
           tabindex="1" class="at-icon-wrapper at-share-btn at-svc-email action mailto at-share-btn friend<?php echo $useFancybox && $allowGuest ? ' fancybox fancybox.iframe' : '' ?>" style="background-color: rgb(132, 132, 132); border-radius: 8px;">
            <span class="at4-visually-hidden">Share to Email</span>
                    <span class="at-icon-wrapper" style="line-height: 32px; height: 32px; width: 32px;">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" style="fill: rgb(255, 255, 255); width: 32px; height: 32px;" class="at-icon at-icon-email"><g><g fill-rule="evenodd"></g>
                                <path d="M27 22.757c0 1.24-.988 2.243-2.19 2.243H7.19C5.98 25 5 23.994 5 22.757V13.67c0-.556.39-.773.855-.496l8.78 5.238c.782.467 1.95.467 2.73 0l8.78-5.238c.472-.28.855-.063.855.495v9.087z"></path><path d="M27 9.243C27 8.006 26.02 7 24.81 7H7.19C5.988 7 5 8.004 5 9.243v.465c0 .554.385 1.232.857 1.514l9.61 5.733c.267.16.8.16 1.067 0l9.61-5.733c.473-.283.856-.96.856-1.514v-.465z"></path></g>
                        </svg>
                </span>
            <span class="at-label" style="font-size: 11.4px; line-height: 32px; height: 32px; color: rgb(255, 255, 255);"><?php /* @escapeNotVerified */ echo __('Email') ?></span></a>
    </div>
    <?php if($useFancybox && $allowGuest) : ?>
        <script type="text/x-magento-init">
    {
        ".fancybox": {
            "forix/fancybox": {

            }
        }
    }
    </script>
    <?php endif; ?>
<?php endif; ?>
