<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Forix\ProductWizard\Block\Preview
 * @var $formkey \Magento\Backend\Block\Admin\Formkey
 */
$formkey = $block->getLayout()->getBlock('formkey');
?>
<div id="checkout-loader" data-role="configurator-loader" class="loading-mask" data-mage-init='{"configuratorLoader": <?php echo json_encode($block->getDefaultData(), JSON_HEX_QUOT|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS) ?>}'>
    <div class="loader">
        <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
             alt="<?= /* @escapeNotVerified */__('Loading...') ?>" style="position: absolute;">
    </div>
</div>
<script>
    if (undefined === window.checkoutConfig) {
        window.checkoutConfig = {};
    }
    window.checkoutConfig.storeCode = '<?php echo $block->getStoreCode();?>';
    window.productWizard = {
        storeCode: '<?php echo $block->getStoreCode();?>',
        addToCartAction:'<?php echo $block->getUrl('productwizard/cart/add/');?>',
        formKey: '<?php echo $formkey->getFormKey();?>'
    };
    require([
        'mage/url',
        'Magento_Ui/js/block-loader'
    ], function (url, blockLoader) {
        blockLoader("<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>");
        return url.setBaseUrl('<?= /* @escapeNotVerified */ $block->getBaseUrl() ?>');
    });
</script>
<script type="text/x-magento-init">
<?php /* @noEscape */
    echo $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode([
        '*' => $block->getJsLayout(),
    ]);
?>
</script>
