<?php


namespace Forix\ProductWizard\Model\ResourceModel\GroupItem;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{

    /**
     * Define resource model
     *
     * @return void
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    protected function _construct()
    {
        $this->_init(
            'Forix\ProductWizard\Model\GroupItem',
            'Forix\ProductWizard\Model\ResourceModel\GroupItem'
        );
        $this->_setIdFieldName($this->getResource()->getIdFieldName());
    }

    /**
     * @return array
     */
    public function toOptionHash()
    {
        return $this->_toOptionHash('group_item_id', 'title');
    }

    protected function _beforeLoad()
    {
        $this->setOrder('sort_order', self::SORT_ORDER_ASC);
        return parent::_beforeLoad(); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $groupId
     * @return $this
     */
    public function addGroupIdToFilter($groupId){
        $this->addFieldToFilter('group_id', $groupId);
        return $this;
    }
}
