<?php
/**
 * Created by Hidro Le.
 * Job Title: Magento Developer
 * Project Name: M2 - Soft Star Shoes
 * Date: 2/10/18
 * Time: 10:47 AM
 */
namespace Forix\ProductListTemplate\Model\Category\Attribute\Backend;
class Category extends \Magento\Eav\Model\Entity\Attribute\Backend\AbstractBackend
{
    protected $_collectionFactory;

    public function __construct(
        \Magento\Catalog\Model\ResourceModel\Category\CollectionFactory $collectionFactory
    )
    {
        $this->_collectionFactory = $collectionFactory;
    }

    /**
     * Before Attribute Save Process
     *
     * @param \Magento\Framework\DataObject $object
     * @return $this
     */
    public function beforeSave($object)
    {
        $attributeCode = $this->getAttribute()->getName();
        $data = $object->getData($attributeCode);
        if ($attributeCode == 'sss_category_tab_ids') {
            if (!is_array($data)) {
                $data = explode(',', $data);
            }
            $object->setData($attributeCode, implode(',', $data) ?: null);
            try {
                $categoryCollection = $this->_collectionFactory->create();
                $categoryCollection->addAttributeToFilter('sss_parent_tab_id', $object->getId());
                /**
                 * @var $item \Magento\Catalog\Model\Category;
                 * @var $resource \Magento\Catalog\Model\ResourceModel\Category;
                 */
                foreach ($categoryCollection as $item) {
                    $item->setData('sss_parent_tab_id', null);
                    $resource = $item->getResource();
                    $resource->saveAttribute($item, 'sss_parent_tab_id');
                }
            } catch (\Exception $e) {
            }
        }

        if (!$object->hasData($attributeCode)) {
            $object->setData($attributeCode, null);
        }
        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function afterSave($object)
    {

        $attributeCode = $this->getAttribute()->getName();
        $data = $object->getData($attributeCode);
        if ($attributeCode == 'sss_category_tab_ids') {
            if (!is_array($data)) {
                $data = explode(',', $data);
            }
            $object->setData($attributeCode, implode(',', $data) ?: null);
            try {
                $categoryCollection = $this->_collectionFactory->create();
                $categoryCollection->addFieldToFilter('entity_id', ['in' => $data]);
                /**
                 * @var $item \Magento\Catalog\Model\Category;
                 * @var $resource \Magento\Catalog\Model\ResourceModel\Category;
                 */
                foreach ($categoryCollection as $item) {
                    $item->setData('sss_parent_tab_id', $object->getId());
                    $resource = $item->getResource();
                    $resource->saveAttribute($item, 'sss_parent_tab_id');
                }
            } catch (\Exception $e) {
            }
        }
        return parent::afterSave($object); // TODO: Change the autogenerated stub
    }

    /**
     * After Load Attribute Process
     *
     * @param \Magento\Framework\DataObject $object
     * @return $this
     */
    public function afterLoad($object)
    {
        $attributeCode = $this->getAttribute()->getName();
        if ($attributeCode == 'sss_category_tab_ids') {
            $data = $object->getData($attributeCode);
            if ($data) {
                if (!is_array($data)) {
                    $object->setData($attributeCode, explode(',', $data));
                } else {
                    $object->setData($attributeCode, $data);
                }
            }
        }
        return $this;
    }
}