<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var $block \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable*/
$_product    = $block->getProduct();
$_attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <?php foreach ($_attributes as $_attribute): ?>
        <div class="field configurable required">
            <?php $attrCode = $_attribute->getProductAttribute()->getAttributeCode() ?>
            <label class="label" for="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>">
                <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>
            </label>
            <div class="control _with-tooltip">
                <select name="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>]"
                        data-selector="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>]"
                        data-validate="{required:true}"
                        id="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>"
                        class="super-attribute-select">
                    <option value=""><?= /* @escapeNotVerified */ __('Choose an Option...') ?></option>
                </select>
                <?php if($attrCode == 'sss_sole'): ?>
                    <?php if($_product->getSssTooltip()): ?>
                    <div class="field-tooltip toggle">
                    <span class="field-tooltip-action action-cvv"
                          tabindex="0"
                          data-toggle="dropdown"
                          data-bind="mageInit: {'dropdown':{'activeClass': '_active'}}">
                <span><!-- ko i18n: ''--><!-- /ko --></span></span>
                        <div class="field-tooltip-content"
                             data-target="dropdown">
                            <?php echo $_product->getSssTooltip(); ?>
                        </div>
                    </div>
                    <?php endif; ?>
                <?php elseif ($attrCode == 'sss_size'): ?>
                    <?php if($_product->getSssSizeGuide()): ?>
                        <a class="size-guide" href="<?php echo $_product->getProductUrl()?>#sizing.guide.tab"><?php echo __('Size Guide');?></a>
                    <?php endif; ?>
                <?php endif; ?>
                <label class="label" for="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>">
                    <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>
                </label>
            </div>
        </div>
    <?php endforeach; ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "configurable": {
                    "spConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                    "gallerySwitchStrategy": "<?php /* @escapeNotVerified */ echo $block->getVar('gallery_switch_strategy',
            'Magento_ConfigurableProduct') ?: 'replace'; ?>"
                }
            }
        }
    </script>
<?php endif;?>
