<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'" data-trigger="minicart" title="<?php /* @escapeNotVerified */ echo __('My Cart'); ?>">
        <span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number" data-bind="attr: {'data-number': getCartParam('summary_count')}">
                <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- /ko -->
                <!-- ko ifnot: getCartParam('summary_count') -->
                    <!-- ko text: 0 --><!-- /ko -->
                <!-- /ko -->
            </span>
            <span class="counter-label">
                <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                    <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->
                <!-- ko ifnot: getCartParam('summary_count') -->
                    <!-- ko text: 0 --><!-- /ko -->
                    <!-- ko i18n: 'item' --><!-- /ko -->
                <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty swipe-minicart"
             data-role="dropdownDialog" data-bind="mageInit: {
            'forix/pushdata':{
                'container': '.minicart-wrapper',
                'toggleBtn': '[data-trigger=minicart]',
                'swipeArea': '.swipe-minicart',
                'pushCloseCls':'push-close',
                'closeBtnCls':'toggle-cart-close',
                'noEffect':'#mini-login',
                'clsPush':'minicart',
                'responsive': true,
                'swiped': 'right'
            }}">
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>


