<script type="text/x-magento-init">
    {
        "*": {
            "forix/shoppingCart": {}
        }
    }
</script>
<script>
//    require([
//        'jquery',
//        "matchMedia",
//        'forix/plugins/tweenmax',
//        'forix/plugins/stickykit',
//        'domReady!'
//    ], function($) {
//        "use strict";
//        //TweenMax.delayedCall( 300, function(){
//            $('.cart-summary').stick_in_parent({
//                parent: '.cart-container',
//                offset_top: 0,
//                recalc_every: 1
//            });
//        //});
//
//    });
</script>
