<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            $(function() {
                if(jQuery('#location_id').length == 0) {
                    $("#location_status option[value=1]").attr('selected', 'selected');
                    $("#location_country option[value=US]").attr('selected', 'selected');
                }
            });
        });
</script>