<!--[[Header]]: [Homepage] featured-product -->
<div class="homepage-featured-product">
    <span class="lable">featured product</span>
    <div class="thumbnial">
        <img src="{{media url="homepage/thumbnail-featured.png"}}" alt="" />
    </div>
    <div class="block-bottom">
        <div class="title-main">
            <div class="title ">
                    The FastBack System
            </div>
            <p>Configure a pullback device to work with any Borzall bit.</p>
        </div>
    
        <a class="btn"><span>Learn more</span> </a>
        <a class="btn btn-video fancybox-video" title="Play Video" href="https://www.youtube.com/embed/7aao4IBw0OI?autoplay=1&amp;rel=0" data-fancybox=""><span>Play Video</span> </a>
        <a class="btn"><span>configure yours</span> </a>
    </div>
</div>

