<!--[[Header]]: [Common] footer-links  -->
<ul class="footer_links">
	<li>
		<h3 class="title">Company</h3>
		<ul class="content">
			<li><a title="Our Story" href="#">Our Story</a></li>
			<li><a title="About" href="#">Quanlity &amp; Innovation</a></li>
			<li><a title="Media & Press" href="#">Media &amp; Press</a></li>
			<li><a title="Community" href="#">Community</a></li>
			<li><a title="Blog" href="#">Blog</a></li>
			<li><a title="Careers" href="#">Careers</a></li>
			<li><a title="Become a Distributor" href="#">Become a Distributor</a></li>
		</ul>
	</li>
	
	<li>
		<h3 class="title">HDD RESOURCE</h3>
		<ul class="content">
			<li><a title="Returns" href="#">Guides &amp; Case Studies</a></li>
			<li><a title="Product Videos" href="#">Product Videos</a></li>
			<li><a title="Download Catalog" href="#">Download Catalog</a></li>
		</ul>
	</li>
	<li>
		<h3 class="title">HELP &amp; CONTACT</h3>
		<div class="content-half">
			<ul class="content">
				<li><a title="Contact Us" href="#">Contact Us</a></li>
				<li><a title="Shipping" href="#">Shipping</a></li>
				<li><a title="Warranty" href="#">Warranty</a></li>
				<li><a title="Returns" href="#">Returns</a></li>
			</ul>
			<ul class="content content-phone">
				<li>
					<span>TOLL FREE</span>
					<span>800.558.7500</span>
				</li>
				<li>
					<span>INTERNATIONAL</span>
					<span>805.739.0118</span>
				</li>
				<li>
					<p>Mon-Fri: 7-5PM PT<p>
					<p>Sat: 8-2PM PT</p>
				</li>
			</ul>
		</div>
		<ul class="content">
			<div class="btn-chatnow footer" onclick="parent.LC_API.open_chat_window({source:'minimized'})">
				<span id="footer-live-chat">
                    <img alt="{{media url="homepage/LiveChat-Online-Invert.png"}}" src="{{media url="homepage/LiveChat-Online-Invert.png"}}" alt="LiveChat-Online-Invert.png" />
                </span>
			</div>
		</ul>
	</li>
</ul>
