<!--[[Header]]: [Contact] left-cms-links-block -->
<div class="block block-cms">
    <div class="block-title-help"><strong>Help</strong></div>
    <div class="block-title block-title-mobile" data-mage-init="{&quot;forix/toggle&quot;: {&quot;toggleContainers&quot;: &quot;#block-cms-toggle&quot;, &quot;selectorsToggleClass&quot;: &quot;active&quot;}}"><strong>Contact us</strong></div>
    <div id="block-cms-toggle" class="block-content">
        <ul>
            <li data-link="contact"><a title="Contact Us" href="{{store url='contact'}}">Contact Us </a></li>
            <li data-link="returns"><a title="Returns Exchanges" href="{{store url='#'}}">Shipping</a></li>
            <li data-link="shipping"><a title="Shipping Info" href="{{store url='#'}}"> Warranty</a></li>
            <li data-link="faq"><a title="FAQs" href="{{store url='faq'}}">Returns</a></li>
        </ul>
    </div>
</div>