<!--[[Header]]: [Homepage] Location near you -->
<div class="homepage-location">
	<div clas="thumbnail-location">
        <img src="{{media url="homepage/Bitmap.png"}}" alt="" />
    </div>
    <div class="title-main">
        <div class="title">
            A LOCATION NEAR YOU
</div>
        <p>We know when you need the right tool you need it at the right time. Which is why we have distributors all over the US and the globe—to get you what you need as soon as you need it. Use our Find a Distributor tool to find the closest distributor to you.</p>
        <a href="#" class="action abutton"><span>find a distributor</span></a>
    </div>
</div>

