<!--[[Header]]: [SearchNoResult] Navigation Link -->
<div class="noresult-navigationlink">
    <div class="chatwithus">
        <h3 class="title"><span>Chat with us</span></h3>
        <ul class="content">
            <li>An HHD expert is online right now to answer all your questions.</li>
            <div class="btn-chatnow"  onclick="parent.LC_API.open_chat_window({source:'minimized'})">
                <img alt="{{media url="homepage/chatnow.png"}}" src="{{media url="homepage/chatnow.png"}}" alt="" />
            </div>
        </ul>
    </div>
    <div class="telephone">
        <h3 class="title"><span>GIVE US A CALL</span></h3>
        <ul class="content">
            <li><span>Toll Free</span><span class="phone"><a>800.558.7500</a></span></li>
            <li><span>International</span><span class="phone"><a>800.558.7500</a></span></li>
            <li class="time"><span>Mon-Fri: 7-5PM PT</span><span>Sat: 8-2PM PT</span></li>
        </ul>
    </div>
    <div class="emailus">
        <h3 class="title"><span>EMAIL US</span></h3>
        <ul class="content">
            <li>We love letters.</li>
        </ul>
    </div>
    <div class="findadistributor">
        <h3 class="title"><span>FIND A DISTRIBUTOR</span></h3>
        <ul class="content">
            <li>There's probably one really close by.</li>
        </ul>
    </div>
</div>

