<!--[[Header]]: [Melfredborzall] Shopping-Cart Help Block -->
<strong>NEED HELP?</strong>
<div class="text">Our HDD experts are standing by</div>
<div class="phone"> <strong>(888) 831-5817</strong> </div>
<!-- <button class="btn-chatnow" type="button" onclick="parent.LC_API.open_chat_window({source:'minimized'})">WE’RE ONLINE - CHAT NOW!</button> -->
<div class="btn-chatnow" onclick="parent.LC_API.open_chat_window({source:'minimized'})">
<img alt="{{media url="homepage/chatnow.png"}}" src="{{media url="homepage/chatnow.png"}}" alt="" />
</div>
<p>Mon-Fri: 7-5PM PT, Sat: 8-2PM PT</p>
