<!--[[Header]]: [Homepage] testimonials-slider -->
<div class="homepage-testimonials slider-partner">
	<div class="item-left">
	<div class="slider slider-nav">
		<div class="item">
			<div class="item-inner">
				<div class="title-main">
					<div class="title">
						WHAT DRILLERS ARE SAYING
					</div>
					<p>This hill is a mother-huncher, so we're still using the Iron Fist bit day in and day out. Yet another bore handled by the Iron Fist in Snowmass.</p>
					<span>Alterra Underground Solutions, Denver, CO</span>
				</div>
			</div>
		</div>
		<div class="item">
			<div class="item-inner">
				<div class="title-main">
					<div class="title">
						WHAT DRILLERS ARE SAYING
					</div>
					<p>This hill is a mother-huncher, so we're still using the Iron Fist bit day in and day out. Yet another bore handled by the Iron Fist in Snowmass.</p>
					<span>Alterra Underground Solutions, Denver, CO</span>
				</div>
			</div>
		</div>
		<div class="item">
			<div class="item-inner">
				<div class="title-main">
					<div class="title">
						WHAT DRILLERS ARE SAYING
					</div>
					<p>This hill is a mother-huncher, so we're still using the Iron Fist bit day in and day out. Yet another bore handled by the Iron Fist in Snowmass.</p>
					<span>Alterra Underground Solutions, Denver, CO</span>
				</div>
			</div>
		</div>
		<div class="item">
			<div class="item-inner">
				<div class="title-main">
					<div class="title">
						WHAT DRILLERS ARE SAYING
					</div>
					<p>This hill is a mother-huncher, so we're still using the Iron Fist bit day in and day out. Yet another bore handled by the Iron Fist in Snowmass.</p>
					<span>Alterra Underground Solutions, Denver, CO</span>
				</div>
			</div>
		</div>
	</div>

	<a class="btn btn-video fancybox-video" title="Play Video" href="https://www.youtube.com/embed/7aao4IBw0OI?autoplay=1&amp;rel=0" data-fancybox=""><span><span>Do you have the right tools?</span> watch our video</span> </a>
	</div>
	

<div class="item-right">
<div class="slider slider-for">
		<div class="item">
			<img src="{{media url="homepage/home-slide.png"}}" alt="" />
		</div>
		<div class="item">
			<img src="{{media url="homepage/driler-img-1.jpg"}}" alt="" />
		</div>
		<div class="item">
			<img src="{{media url="homepage/driler-img.jpg"}}" alt="" />
		</div>
		<div class="item">
			<img src="{{media url="homepage/home-slide.png"}}" alt="" />
		</div>
	</div>

</div>
	
	
	
</div>