<!--[[Header]]: [Common] top-nav-right -->
<ul class="nav-right-mobile">
    <li class="level-top top-link-megamenu">
        <a href="#">Info</a>
    </li>
</ul>
<ul class="top-nav-right" data-mage-init='{"forix/menu":{}}'>
	<li class="company level0 level-top nav-1 first last  parent"><a title="Company" href="#" class="level-top">
            <span>Company</span>
            <span class="ico-arrow"></span>
        </a>
        <ul class="submenu">
            <li><a title="The FastBack® System" href="#">The FastBack® System</a></li>
            <li><a title="Our Story" href="#">Our Story</a></li>
            <li><a title="Quality & Innovation" href="#">Quality & Innovation</a></li>
            <li><a title="Media & Press" href="#">Media & Press</a></li>
            <li><a title="Community" href="#">Community</a></li>
            <li><a title="Blog" href="#">Blog</a></li>
            <li><a title="Careers" href="#">Careers</a></li>
            <li><a title="Become a Distributor" href="#">Become a Distributor</a></li>
        </ul>
    </li>
	<li class="hdd-resources level0 level-top nav-1 first last  parent"><a title="HDD Resources" href="#">HDD Resources</a>
        <ul class="submenu">
            <li><a title="White Papers & Case Studies" href="#">White Papers & Case Studies</a></li>
            <li><a title="Product Videos" href="#">Product Videos</a></li>
            <li><a title="Download Catalog (PDF)" href="#">Download Catalog (PDF)</a></li>
        </ul>
    </li>
	<li class="help-contact level0 level-top nav-1 first last  parent"><a title="Help & Contact" href="#">Help &amp; Contact</a>
        <ul class="submenu">
            <li>
                <ul class="nav-list-info">
                    <li>
                        <span>Toll Free</span>
                        <span class="phone">800.558.7500</span>
                    </li>
                    <li>
                        <span>International</span>
                        <span class="phone">805.739.0118</span>
                    </li>
                    <li>
                        <span>Mon-Fri: 7-5PM PT</span>
                        <span>Sat: 8-2PM PT</span>
                    </li>
                </ul>
                <ul class="nav-contact">
                    <li><a title="Contact Us" href="#">Contact Us</a></li>
                    <li><a title="Shipping" href="#">Shipping</a></li>
                    <li><a title="Warranty" href="#">Warranty</a></li>
                    <li><a title="Returns" href="#">Returns</a></li>
                </ul>
                <ul>
                    <li>
                        <div class="btn-chatnow">
                            <img onclick="parent.LC_API.open_chat_window({source:'minimized'})" alt="{{media url="homepage/chatnow.png"}}" src="{{media url="homepage/chatnow.png"}}">
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </li>

</ul>