<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="page-title-wrapper">
    <h1 class="page-title">
        <span><?php echo $this->getCategoryName() ? $this->getCategoryName() : 'Softstar Blog' ?></span>
    </h1>
</div>
<?php $posts = $this->getPosts() ?>
<?php if (count($posts) > 0): ?>
	<div class="post-list-wrapper">
		<ol class="post-list">
			<?php foreach($posts as $post): ?>
				<?php if ($renderedPostHtml = $this->renderPost($post)): ?>
					<li class="item<?php if ($post->isSticky()): ?> featured is-sticky<?php endif; ?> <?php echo $post->getPostFormat() ?>">
						<?php echo $renderedPostHtml ?>
					</li>
				<?php endif; ?>
			<?php endforeach; ?>
		</ol>
		<?php echo $this->getPagerHtml() ?>
	</div>
<?php endif; ?>