<!--[[Header]]: [Login] Login Page-->
<div class="block-title">
    <strong id="block-new-customer-heading" role="heading" aria-level="2">Create a New Account</strong>
</div>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitetion ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

<ul class="list-background">
    <li><span>Bullet Item</span></li>
    <li><span>Lorem ipsum dolor sit amet</span></li>
</ul>