<div class="cms-fan-photo">
    <div class="fan-photo-child float">
        <p><span class="title">Child Fan<br /> Photo</span></p>
        <div><img src="{{media url="wysiwyg/photo-gallery-1.jpg"}}" width="660" height="520" /> <span class="title"><strong>JUSTIN</strong> - Annandale, Minnesota</span></div>
    </div>
    <div class="fan-photo-adult float">
        <p><span class="title">Adult Fan<br /> Photo</span></p>
        <div><img title="" src="https://smhttp-ssl-75331.nexcesscdn.net/pub/static/version1527673514/frontend/Forix/softstarshoes/en_US/images/photo-gallery-2.jpg" alt="" width="660" height="520" /> <span class="title"><strong>JEFF</strong> - Houtzdale, annsylvania</span></div>
    </div>
</div>