<!--[[Header]]: [Footer] Footer Top-->
<div class="footer-top-inner">
    <ul>
        <li class="handmade"><span>Handmade By Elves In Oregon, USA</span></li>
        <li class="freeship"><span>Enjoy Free Shipping & Easy Returns</span></li>
        <li class="leather"><span>Sustainably Sourced Leather & Sheepskin</span></li>
        <li class="guarantee"><span>Happy Feet Guarantee</span></li>
    </ul>
</div>
<img src="{{media url="wysiwyg/image.jpg"}}" alt="" />