<!--[[Header]]: [Footer] Socials Block-->
<ul class="box-socials">
    <li class="ico-twitter"><a title="Twitter" href="#">Twitter</a></li>
    <li class="ico-facebook"><a title="Facebook" href="#">Facebook</a></li>
    <li class="ico-instagram"><a title="Instagram" href="#">Instagram</a></li>
    <li class="ico-pinit"><a title="Pinit" href="#">Pinit</a></li>
    <li class="ico-youtube"><a title="Youtube" href="#">Youtube</a></li>
</ul>