<!--[[Header]]: [Footer] Links-->
<ul class="footer_links">
    <li>
        <p class="footer-logo">
            <a href="#"><img src="{{media url="wysiwyg/logo.svg"}}" alt="" /></a>
        </p>
        <h3 class="title">Healthy Shoes for Happy Feet!</h3>
        <div class="content">
            <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.</p>
            <ul class="links-content">
                <li><a title="About Softstar Shoes" href="#">About Softstar Shoes</a></li>
                <li><a title="How It’s Made" href="#">How It’s Made</a></li>
                <li><a title="Visit our Blog" href="#">Visit our Blog</a></li>
            </ul>
        </div>
    </li>
    <li>
        <h3 class="title">Explore</h3>
        <div class="content">
            <ul class="links-content">
                <li><a title="Fan Photos" href="#">Fan Photos</a></li>
                <li><a title="Video Gallery" href="#">FAQ's</a></li>
                <li><a title="Custom Shoe of the Week" href="#">Custom Shoe of the Week</a></li>
                <li><a title="Our Ambassadors" href="#">Our Ambassadors</a></li>
                <li><a title="Meet the Shoemakers (Elves)" href="#">Meet the Shoemakers (Elves)</a></li>
                <li><a title="Sustainability" href="#">Sustainability</a></li>
                <li><a title="SoftStar in the News" href="#">SoftStar in the News</a></li>
            </ul>
        </div>
    </li>
    <li>
        <h3 class="title">Help</h3>
        <div class="content">
            <ul class="links-content">
                <li><a title="Order Lookup" href="#">Order Lookup</a></li>
                <li><a title="Shipping" href="#">Shipping</a></li>
                <li><a title="Returns & Exchanges" href="#">Returns & Exchanges</a></li>
                <li><a title="FAQs" href="#">FAQs</a></li>
                <li><a title="Special Requests" href="#">Special Requests</a></li>
                <li><a title="Contact Us" href="#">Contact Us</a></li>
            </ul>
        </div>
    </li>
    <li>
        <h3 class="title">Contact us</h3>
        <div class="content">
            <p>
                <a href="tel:541-753-5845" class="tel">541-753-5845</a><br>
                <a href="mailto:elves@softstarshoes.com" class="mailto">elves@softstarshoes.com</a>
            </p>
        </div>
        <h3 class="title">Visit Our Workshop</h3>
        <div class="content">
            <p class="open-time">
                Mon: 10am–4pm<br>
                Tues–Fri: 10am–5pm<br>
                Sat: 10am–4pm<br>
                Sun: Closed
            </p>
            <p class="address">
                <span>914 Main Street</span><br>
                <span>Philomath, OR 97370 USA</span>
            </p>
        </div>
    </li>
</ul>