<!--[[Header]]: [Header] Right Second Navigation-->
<ul class="right-second-nav">
    <li class="size-guide"><a href="{{store url='sizing-guide'}}" title="Size Guide">Size Guide</a></li>
    <li class="help has-submenu parent"><a href="#" title="help">Help</a>
        <div class="block-dropdown submenu dropdown-menu">
            <ul class="content-wrap">
                <li><a title="Order Lookup" href="/sales/guest/form">Order Lookup</a></li>
                <li><a title="Shipping" href="{{store url='shipping'}}">Shipping</a></li>
                <li><a title="Returns &amp; Exchanges" href="{{store url='returns-exchanges'}}">Returns &amp; Exchanges</a></li>
                <li><a title="FAQs" href="{{store url='faq'}}">FAQ</a></li>
                <li><a title="Special Requests" href="{{store url='special-request-shoes'}}">Special Requests</a></li>
                <li><a title="Contact Us" href="{{store url='contact'}}">Contact Us</a></li>
            </ul>
        </div>
    </li>
    <li class="tel"><a title="(541) 753-5845" href="tel: 5417535845">(541) 753-5845</a></li>
</ul>