<!--[[Header]]: [Header] Left Second Navigation-->
<ul class="left-second-nav">
    <li class="minimal-shoes-handmade parent"><a href="#" title="Minimal Shoes Handmade in Oregon, USA">Minimal Shoes Handmade in Oregon, USA</a>
        <div class="block-dropdown submenu dropdown-menu">
            <div class="block-dropdown-title"><span>Crafted with Love Here in the USA</span></div>
            <div class="block-dropdown-content"><p>Every Softstar shoe is designed and handcrafted at our workshop in Philomath, Oregon. <a title="read more" href="/how-made">Learn more</a></p>
            </div>
        </div>
    </li>
    <li class="freeshipping parent"><a href="#" title="Free Shipping & Easy Returns">Free Shipping & Easy Returns</a>
        <div class="block-dropdown submenu dropdown-menu">
            <div class="block-dropdown-title"><span>Enjoy Free Shipping & Easy Returns</span></div>
            <div class="block-dropdown-content"><p>Return any brand new shoe for any reason for a full refund or exchange, even if you customize with your own special colors! Learn more about our <a title="Shipping" href="/shipping">shipping options</a> or <a title="Returns and Exchanges" href="/returns-exchanges">return policy</a>.</p>
            </div>
        </div>
    </li>
</ul>