<!--[[Header]]: [Homepage] Fan Photos-->
<span class="title">This Month’s Fan Photo<br> Contest Winners</span>
<div><img src="{{media url="wysiwyg/leathercraft-chukka-02.jpg"}}" alt="" /></div>
<p>Congratulations to Tun-Min from Sabah, Malaysia and Alex from Dillon, Colorado! Their photos were randomly selected as our November 2017 child and adult fan photo winners. </p>
<a href="#" title="More Fan Photos">More Fan Photos</a>