<!--[[Header]]: [Homepage] Video-->
<div>
    <img src="{{media url="wysiwyg/The_Softstar_Way.jpg"}}" alt="" />
    <a class="btn-play-video fancybox-video" title="Play Video" data-fancybox href="https://www.youtube.com/embed/7O1bR_mjeYg?autoplay=1&amp;rel=0">
        <span class="icon-play-video"></span>
    </a>
    <span class="title">The Softstar Way</span>
    <a class="more-videos" href="#">More Videos</a>
</div>