<!--[[Header]]:[Right][Cms] Help Links Block-->
<div class=right-contact">
    <div class="box box-phone">
        <div class="inner">
            <div class="inner-right">
                <div class="subtitle">
                    Phone:
                </div>
                <div class="list">
                    <div><strong>Call Us:</strong> 541-753-5845</div>
                    <div><strong>Toll Free:</strong> 866-763-2525</div>
                </div>
            </div>
        </div>
    </div>
    <div class="box box-email">
        <div class="inner">
            <div class="inner-right">
                <div class="subtitle">
                    Email:
                </div>
                <div><a href="#">elves@softstarshoes.com</a></div>
            </div>
        </div>
    </div>
    <div class="box box-location">
        <div class="inner">
            <div class="inner-right">
                <div class="subtitle">
                    Location:
                </div>
                <div class="title">Visit our workshop!</div>
                <address>914 Main Street <br/>
                    Philomath, OR 97370 USA</address>
                <div class="title">Showroom Hours (PT):</div>
                <ul>
                    <li>Mon: 10am–4pm</li>
                    <li>Tues–Fri: 10am–5pm</li>
                    <li>Sat: 10am–4pm</li>
                    <li>Sun: Closed</li>

                </ul>
            </div>
        </div>
    </div>
</div>


<div class="contact-socials">
<ul class="box-socials">
    <li class="ico-facebook"><a title="Facebook" href="#">Facebook</a></li>
    <li class="ico-twitter"><a title="Twitter" href="#">Twitter</a></li>
    <li class="ico-instagram"><a title="Instagram" href="#">Instagram</a></li>
    <li class="ico-pinit"><a title="Pinit" href="#">Pinit</a></li>
    <li class="ico-youtube"><a title="Youtube" href="#">Youtube</a></li>
</ul>
</div>