<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart totals template
 * @var $block \Magento\Checkout\Block\Cart\Totals
 */
?>
<div id="block-cart-totals" class="cart-totals">
    <div class="title" data-role="title">
        <strong id="block-cart-totals" role="heading" aria-level="2">
            <?= /* @escapeNotVerified */
            __('Cart Summary') ?>
        </strong>
    </div>
    <div id="cart-totals" class="cart-totals" data-bind="scope:'block-totals'">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#cart-totals": {
                    "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */
            $block->getJsLayout() ?>
                }
            }

        </script>
    </div>
</div>
