<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Forix\Distributor\Controller\Adminhtml\Customer;



class Edit extends \Magento\Customer\Controller\Adminhtml\Index\Edit
{
	const ADMIN_RESOURCE = 'Forix_Distributor::customer';



	public function execute()
	{
		$id = $this->getRequest()->getParam('id');
		if (!$id) {
			$resultForward = $this->resultForwardFactory->create();
			return $resultForward->forward('new');
		}
		return parent::execute(); // TODO: Change the autogenerated stub
	}

}
