<!--
[[PageTitle]]: About Us
[[ContentHeading]]:
[[Layout]]: 1column
[[URLKey]]: about-us
-->

<div class="homepage-video video-popup"><a class="btn-play-video fancybox-video" title="Play Video" href="https://www.youtube.com/embed/7O1bR_mjeYg?autoplay=1&amp;rel=0" data-fancybox=""> <span class="icon-play-video"></span> </a></div>
<div class="homepage-cms-container-1">
<div class="float block-text">
<h3>Softstar Shoes: Strong from the Ground Up</h3>
<p>What does Softstar do? We make minimal shoes for happy, healthy feet. Every one of our shoes is handcrafted in the USA in our workshop in Oregon. We work hard to make Softstara a socially and environmentally responsible company, as well as giving a good experience to both our employees and our customers.</p>
<h4 class="box-title">Our Core Values</h4>
<ol>
<li><strong>Share the handcrafted experience with our customers:</strong> Make unique, beautiful, comfortable and quality footwear while encouraging direct interaction via excellent customer service.</li>
<li><strong>Walk lightly on the earth:</strong> Conserve raw materials by thoughtful use. Minimize our environmental footprint with <a title="Softstar sustainable practices" href="/sustainable-practices">sustainable practices</a> that include reducing waste, reusing and recycling.</li>
<li><strong>Make our workshop a wonderful place to work:</strong> A creative, energizing and efficient workspace. An open, honest atmosphere where we work with mutual respect and dignity. A place where our families and <a title="Softstar in the Community" href="http://www.softstarshoes.com/community">community</a> are welcome and integrated.</li>
</ol></div>
<div class="float block-list"><strong class="box-title">Softstar shoes are</strong>
<ul>
<li>
<div>
<div>minimal</div>
</div>
<span> …like gloves for your feet, allowing for natural movement and healhty foot development. </span></li>
<li>
<div>
<div>leather</div>
</div>
<span> …naturally soft and breathable that feel and smells yummy. </span></li>
<li>
<div>
<div>simple</div>
</div>
<span> …by jolly master shoemakers (elves) in our workshop right here in Oregon </span></li>
<li>
<div>
<div>handcrafted</div>
</div>
<span> …by jolly master shoemakers (elves) in our workshop right here in Oregon </span></li>
<li>
<div>
<div>customizable</div>
</div>
<span> …choose from hundreds of color and pattern combinations and we’ll make it. </span></li>
</ul>
</div>
</div>
<p><a name="press"></a></p>
<div class="block-newspaper">
<div class="box-title">Softstar Shoes in the Press</div>
<div class="inner">
<div class="item">
<div class="photo-list"><a href="/press-healthy-mom-baby-2017" data-position="1"> <img title="Softstar featured in Mom and Baby Magazine 2017" src="{{media url="wysiwyg/About-us/Press-image/press-healthy-mom-baby-magazine-2017.jpg"}}" alt="softstar-mom-baby-magazine-2017" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-mom-magazine-2016" data-position="2"> <img title="Softstar featured in Mom Magazine 2016" src="{{media url="wysiwyg/About-us/Press-image/press-mom-magazine-2016.jpg"}}" alt="-softstar-mom-magazine-2016" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-oregon-1859-nov16" data-position="3"> <img title="Softstar featured in 1859 Oregon Magazine 2016" src="{{media url="wysiwyg/About-us/Press-image/press-1859-oregon-magazine-2016.jpg"}}" alt="-softstar-1859-oregon-magazine-2016" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-mary-janes-farm-2016" data-position="4"> <img title="Softstar featured in Mary Jane Farm Magazine 2016" src="{{media url="wysiwyg/About-us/Press-image/press-mary-janes-farm-magazine-2016.jpg"}}" alt="-softstar-mary-jane-farm-magazine-2016" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-project-calm-magazine-2016" data-position="5"> <img title="Softstar featured in Project Calm Magazine 2016" src="{{media url="wysiwyg/About-us/Press-image/press-project-calm-magazine-2016.jpg"}}" alt="-softstar-project-calm-magazine-2016" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-prevention-july-2017" data-position="6"> <img title="Softstar featured in Prevention Magazine 2016" src="{{media url="wysiwyg/About-us/Press-image/press-prevention-magazine-2016.jpg"}}" alt="-softstar-prevention-magazine-2016" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-oregon-business-spring2016" data-position="7"> <img title="Softstar featured in Oregon Business Magazine 2016" src="{{media url="wysiwyg/About-us/Press-image/press-oregon-business-2016.jpg"}}" alt="-softstar-oregon-business-magazine-2016" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-ultrarunning-2015" data-position="8"> <img title="Softstar featured in Ultrarunning Magazine 2015" src="{{media url="wysiwyg/About-us/Press-image/press-ultrarunning-magazine-2015.jpg"}}" alt="-softstar-ultrarunning-magazine-2015" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-paleo-magazine-2015" data-position="9"> <img title="Softstar featured in Paleo Magazine 2015" src="{{media url="wysiwyg/About-us/Press-image/press-paleo-magazine-2015.jpg"}}" alt="-softstar-paleo-magazine-2015" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-footwear-news-2015" data-position="10"> <img title="Softstar featured in Footwear News Magazine 2015" src="{{media url="wysiwyg/About-us/Press-image/press-fn-magazine-2015.jpg"}}" alt="-softstar-footwear-news-magazine-2015" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-willamette-living-2015" data-position="11"> <img title="Softstar featured in Willamette Living Magazine 2015" src="{{media url="wysiwyg/About-us/Press-image/press-willamette-living-magazine-2015.jpg"}}" alt="-softstar-willamette-living-magazine-2015" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-paleo-magazine-2014" data-position="12"> <img title="Softstar featured in Paleo Magazine 2014" src="{{media url="wysiwyg/About-us/Press-image/press-paleo-magazine-2014.jpg"}}" alt="-softstar-paleo-magazine-2014" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-green-parent-2014" data-position="13"> <img title="Softstar featured in Green Parent Magazine 2015" src="{{media url="wysiwyg/About-us/Press-image/press-green-parent-magazine-2015.jpg"}}" alt="-softstar-green-parent-magazine-2015" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-national-geographic" data-position="14"> <img title="Softstar featured on National Geographic Channel" src="{{media url="wysiwyg/About-us/Press-image/press-national-geographic-channel-2015.jpg"}}" alt="-softstar-featured-national-geographic-channel" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-healthy-living-magazine" data-position="15"> <img title="Softstar featured in Healthy Living Magazine 2015" src="{{media url="wysiwyg/About-us/Press-image/press-healthy-living-magazine-2015.jpg"}}" alt="-softstar-healthy-living-magazine-2015" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-american-baby-august2014" data-position="16"> <img title="Softstar featured in American Baby Magazine 2014" src="{{media url="wysiwyg/About-us/Press-image/press-american-baby-2014.jpg"}}" alt="-softstar-american-baby-magazine-2014" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-fitting-instyle" data-position="17"> <img title="Softstar featured in Instyle Magazine 2013" src="{{media url="wysiwyg/About-us/Press-image/press-instyle-magazine-2013.jpg"}}" alt="-softstar-instyle-magazine-2013" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-1859-oregon-nov13" data-position="18"> <img title="Softstar featured in 1859 Oregon Magazine 2013" src="{{media url="wysiwyg/About-us/Press-image/press-1859-oregon-magazine-2013.jpg"}}" alt="-softstar-1859-oregon-magazine-2013" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-stitch" data-position="19"> <img title="Softstar featured in Stitch Magazine 2013" src="{{media url="wysiwyg/About-us/Press-image/press-stitch-magazine-2013.jpg"}}" alt="-softstar-stitch-magazine-2013" width="124" height="160" /> </a></div>
</div>
<div class="item">
<div class="photo-list"><a href="/press-ultrarunning-nov12" data-position="20"> <img title="Softstar featured in Ultrarunning Magazine 2012" src="{{media url="wysiwyg/About-us/Press-image/press-ultrarunning-magazine-2012.jpg"}}" alt="-softstar-ultrarunning-magazine-2012" width="124" height="160" /> </a></div>
</div>
<!---------- item hide -->
<div class="item item-hide">
<div class="photo-list"><a href="/press-tread-lightly" data-position="21"> <img title="Softstar featured in Tread Lightly Book 2012" src="{{media url="wysiwyg/About-us/Press-image/press-tread-lightly-book-2012.jpg"}}" alt="-softstar-tread-lightly-book-2012" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-peoplesept2012" data-position="22"> <img title="Softstar featured in People Magazine 2012" src="{{media url="wysiwyg/About-us/Press-image/press-people-magazinep-2012.jpg"}}" alt="-softstar-people-magazine-2012" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-barefootrunningmovie" data-position="23"> <img title="Softstar featured in Barefoot Running DVD 2012" src="{{media url="wysiwyg/About-us/Press-image/press-barefoot-running-dvd-2012.jpg"}}" alt="-softstar-barefoot-running-dvd-2012" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-usweekly" data-position="24"> <img title="Softstar featured in US Weekly 2012" src="{{media url="wysiwyg/About-us/Press-image/press-us-weekly-2012.jpg"}}" alt="-softstar-us-weekly-2012" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-oprah" data-position="25"> <img title="Softstar featured in Oprah Magazine 2010" src="{{media url="wysiwyg/About-us/Press-image/press-oprah-magazine-2010.jpg"}}" alt="-softstar-oprah-magazine-2010" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-klcc-npr" data-position="26"> <img title="Softstar featured on NPR radio 2011" src="{{media url="wysiwyg/About-us/Press-image/press-klcc-npr-radio-2011.jpg"}}" alt="-softstar-featured-npr-radio-2011" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-barefoot-running" data-position="27"> <img title="Softstar featured in Barefoot Running Book 2010" src="{{media url="wysiwyg/About-us/Press-image/press-barefoot-running-book-2010.jpg"}}" alt="-softstar-barefoot-running-book-2010" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-idiots-guide" data-position="28"> <img title="Softstar featured in Idiots Guide to Barefoot Running 2011" src="{{media url="wysiwyg/About-us/Press-image/press-idiots-guide-barefoot-running-book-2011.jpg"}}" alt="-softstar-idiots-guide-to-barefoot-running-2011" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-sportraining" data-position="29"> <img title="Softstar featured in Sportraining Magazine 2012" src="{{media url="wysiwyg/About-us/Press-image/press-sportraining-magazine-2012.jpg"}}" alt="-softstar-sportraining-magazine-2012" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-contra-relogio" data-position="30"> <img title="Softstar featured in Contra Relogio Magazine 2010" src="{{media url="wysiwyg/About-us/Press-image/press-contra-relogio-2010.jpg"}}" alt="-softstar-contra-relogio-magazine-2010" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-parents-magazine" data-position="31"> <img title="Softstar featured in Parents Magazine 2010" src="{{media url="wysiwyg/About-us/Press-image/press-parents-magazine-2010.jpg"}}" alt="-softstar-parents-magazine-2010" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-kiwi" data-position="32"> <img title="Softstar featured in Kiwi Magazine 2009" src="{{media url="wysiwyg/About-us/Press-image/press-kiwi-magazine-2009.jpg"}}" alt="-softstar-kiwi-magazine-2009" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-people" data-position="33"> <img title="Softstar featured in People Magazine 2010" src="{{media url="wysiwyg/About-us/Press-image/press-people-magazine-2010.jpg"}}" alt="-softstar-people-magazine-2010" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-parenting-mag" data-position="34"> <img title="Softstar featured in Parenting Magazine 2008" src="{{media url="wysiwyg/About-us/Press-image/press-parenting-magazine-2008.jpg"}}" alt="-softstar-parenting-magazine-2008" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-mindful-mama" data-position="35"> <img title="Softstar featured in Mindful Mama Magazine 2008" src="{{media url="wysiwyg/About-us/Press-image/press-mindful-mama-magazine-2008.jpg"}}" alt="-softstar-mindful-mama-magazine-2008" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-parent-child" data-position="36"> <img title="Softstar featured in Parent and Child Magazine 2008" src="{{media url="wysiwyg/About-us/Press-image/press-parent-child-magazine-2008.jpg"}}" alt="-softstar-parent-child-magazine-2008" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-mom-magazine" data-position="37"> <img title="Softstar featured in Mom Magazine 2006" src="{{media url="wysiwyg/About-us/Press-image/press-mom-magazine-2006.jpg"}}" alt="-softstar-mom-magazine-2006" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-babytalk" data-position="38"> <img title="Softstar featured in Baby Talk Magazine 2006" src="{{media url="wysiwyg/About-us/Press-image/press-baby-talk-2006.jpg"}}" alt="-softstar-baby-talk-magazine-2006" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-organic-style" data-position="39"> <img title="Softstar featured in Organic Style Magazine" src="{{media url="wysiwyg/About-us/Press-image/press-organic-style-magazine.jpg"}}" alt="-softstar-organic-style-magazine" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-fit-pregnancy" data-position="40"> <img title="Softstar featured in Fit Pregnancy Magazine" src="{{media url="wysiwyg/About-us/Press-image/press-fit-pregnancy-magazine.jpg"}}" alt="-softstar-fit-pregnancy-magazine" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-bundle" data-position="41"> <img title="Softstar featured in bundle Magazine 2005" src="{{media url="wysiwyg/About-us/Press-image/press-bundle-magazine-2005.jpg"}}" alt="-softstar-bundle-magazine-2005" width="124" height="160" /> </a></div>
</div>
<div class="item item-hide">
<div class="photo-list"><a href="/press-presidential-footwear" data-position="42"> <img title="Gerald Ford busy Softstar shoes in 1985" src="{{media url="wysiwyg/About-us/Press-image/press-gerald-ford-1985.jpg"}}" alt="-gerald-ford-busy-softstar-shoes-in-1985" width="124" height="160" /> </a></div>
</div>
<!-- end item hide-->
</div>
<div class="block-click">
<div id="click-here">Select All Mentions</div>
</div>
<div class="popup-slide">
<div class="view-photo">
<div class="slider-photos slider-for">
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-healthy-mom-baby-magazine-2017.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-mom-magazine-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-1859-oregon-magazine-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-mary-janes-farm-magazine-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-project-calm-magazine-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image//press-prevention-magazine-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-oregon-business-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-ultrarunning-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-paleo-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-fn-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-willamette-living-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-paleo-magazine-2014.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-green-parent-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-national-geographic-channel-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-healthy-living-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-american-baby-2014.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-instyle-magazine-2013.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-1859-oregon-magazine-2013.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-stitch-magazine-2013.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-ultrarunning-magazine-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-tread-lightly-book-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-people-magazinep-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-barefoot-running-dvd-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-us-weekly-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-oprah-magazine-2010.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-klcc-npr-radio-2011.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-barefoot-running-book-2010.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-idiots-guide-barefoot-running-book-2011.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-sportraining-magazine-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-contra-relogio-2010.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-parents-magazine-2010.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-kiwi-magazine-2009.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-people-magazine-2010.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-parenting-magazine-2008.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-mindful-mama-magazine-2008.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-parent-child-magazine-2008.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-mom-magazine-2006.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-baby-talk-2006.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-organic-style-magazine.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-fit-pregnancy-magazine.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-bundle-magazine-2005.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-gerald-ford-1985.jpg"}}" alt="" width="124" height="160" /></div>
</div>
<div class="slider-nav">
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-healthy-mom-baby-magazine-2017.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-mom-magazine-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-1859-oregon-magazine-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-mary-janes-farm-magazine-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-project-calm-magazine-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image//press-prevention-magazine-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-oregon-business-2016.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-ultrarunning-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-paleo-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-fn-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-willamette-living-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-paleo-magazine-2014.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-green-parent-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-national-geographic-channel-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-healthy-living-magazine-2015.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-american-baby-2014.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-instyle-magazine-2013.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-1859-oregon-magazine-2013.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-stitch-magazine-2013.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-ultrarunning-magazine-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-tread-lightly-book-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-people-magazinep-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-barefoot-running-dvd-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-us-weekly-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-oprah-magazine-2010.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-klcc-npr-radio-2011.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-barefoot-running-book-2010.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-idiots-guide-barefoot-running-book-2011.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-sportraining-magazine-2012.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-contra-relogio-2010.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-parents-magazine-2010.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-kiwi-magazine-2009.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-people-magazine-2010.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-parenting-magazine-2008.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-mindful-mama-magazine-2008.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-parent-child-magazine-2008.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-mom-magazine-2006.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-baby-talk-2006.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-organic-style-magazine.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-fit-pregnancy-magazine.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-bundle-magazine-2005.jpg"}}" alt="" width="124" height="160" /></div>
<div><img src="{{media url="wysiwyg/About-us/Press-image/press-gerald-ford-1985.jpg"}}" alt="" width="124" height="160" /></div>
</div>
</div>
</div>
</div>
<div class="block-listyear-bg">
<div class="block-listyear">
<div class="block-top">
<div class="float"><img title="1985 Softstar Founders Tim and Jeanie Oliver" src="{{media url="wysiwyg/About-us/History/softstar-history-1985.jpg"}}" alt="1985-softstar-founders-tim-jeanie-oliver" width="500" height="385" /></div>
<div class="float">
<h2>History of Softstar Shoes</h2>
<p>Unable to find healthy minimal shoes for their daughter Corina, carpenter Tim Oliver and his wife Jeanie learn to sew soft leather shoes from a local artisan. The shoes are sold to friends and neighbors.</p>
</div>
</div>
<div class="block-bottom">
<div class="timeline-year-content">
<div id="div1" class="item targetDiv">
<div class="float"><img title="1985 Softstar Founders Tim and Jeanie Oliver" src="{{media url="wysiwyg/About-us/History/softstar-history-1985.jpg"}}" alt="1985-softstar-founders-tim-jeanie-oliver" width="500" height="385" /></div>
<div class="float">
<h2>1985 - Softstar Founders Tim and Jeanie Oliver</h2>
<div class="block-scroll">
<div class="block-scroll-inner">
<p>Unable to find healthy minimal shoes for their daughter Corina, carpenter Tim Oliver and his wife Jeanie learn to sew soft leather shoes from a local artisan. The shoes are sold to friends and neighbors.</p>
</div>
</div>
</div>
</div>
<div id="div2" class="item targetDiv">
<div class="float"><img title="1986 Softstar shoes at Sawdust Art Festival" src="{{media url="wysiwyg/About-us/History/softstar-history-1986.jpg"}}" alt="1986-softstar-shoes-sawdust-art-festival" width="500" height="385" /></div>
<div class="float">
<h2>1986 - Softstar shoes at Sawdust Art Festival</h2>
<div class="block-scroll">
<div class="block-scroll-inner">
<p>Tim and Jeanie bring a batch of their handmade shoes to the Sawdust Art Festival in Laguna Beach, California, where they are sold under the name Softstar for the first time.</p>
</div>
</div>
</div>
</div>
<div id="div3" class="item targetDiv">
<div class="float"><img title="1987 First Softstar workshop was a school bus" src="{{media url="wysiwyg/About-us/History/softstar-history-1987.jpg"}}" alt="1987-first-softstar-workshop-school-bus" width="500" height="385" /></div>
<div class="float">
<h2>1987 - First Softstar workshop was a school bus</h2>
<div class="block-scroll">
<div class="block-scroll-inner">
<p>The Oliver family uses their proceeds from the festival to purchase a plot of land in Wimberly, Texas for their first home—plus an old school bus to live in until it is completed. Tim builds the house himself and the family moves in as soon as the roof is up. The school bus then becomes the first official Softstar shoemaking workshop</p>
<p>Over the next few years, Softstar Shoes are sold via mail order and craft fairs as Tim and Jeanie celebrate the birth of their second daughter, Violet. The whole family helps make shoes with one strict rule: everyone must jump into the crystal clear Blanco River at the end of every work day.</p>
</div>
</div>
</div>
</div>
<div id="div4" class="item targetDiv">
<div class="float"><img title="1990 First Softstar storefront in Corvallis, Oregon" src="{{media url="wysiwyg/About-us/History/softstar-history-1990.jpg"}}" alt="1990-first-softstar-storefront" width="500" height="385" /></div>
<div class="float">
<h2>1990 - First Softstar storefront in Corvallis, Oregon</h2>
<div class="block-scroll">
<div class="block-scroll-inner">
<p>Tim and Jeanie decide a move to Oregon is best for the family. Sadly, the school bus is left behind, but they open the first brick and mortar Softstar workshop in the small town of Corvallis.</p>
</div>
</div>
</div>
</div>
<div id="div5" class="item targetDiv">
<div class="float"><img title="1995 Roo Moccasins are first Softstar shoes for adults" src="{{media url="wysiwyg/About-us/History/softstar-history-1995.jpg"}}" alt="1995-first-adult-softstar-shoes-roo-moccasins" width="500" height="385" /></div>
<div class="float">
<h2>1995 Roo Moccasins are first Softstar shoes for adults</h2>
<div class="block-scroll">
<div class="block-scroll-inner">
<p>As business grows throughout the 1990s, a radical decision is made to try making shoe patterns in adult sizes. The Roo moccasin becomes Softstar’s first adult shoe.</p>
</div>
</div>
</div>
</div>
<div id="div6" class="item targetDiv">
<div class="float"><img title="2001 First Softstar Shoes Website" src="{{media url="wysiwyg/About-us/History/softstar-history-2001.jpg"}}" alt="2001-first-softstar-website" width="500" height="385" /></div>
<div class="float">
<h2>2001 - First Softstar Shoes Website</h2>
<div class="block-scroll">
<div class="block-scroll-inner">
<p>The first Softstar website is launched featuring photos of the five available shoe styles with a printable mail order form (checks or money orders only).</p>
</div>
</div>
</div>
</div>
<div id="div7" class="item targetDiv">
<div class="float"><img title="2005 Tricia Salcido and Larkin Holavarri Buy Softstar Shoes" src="{{media url="wysiwyg/About-us/History/softstar-history-2005.jpg"}}" alt="2005-new-softstar-owners-tricia-salcido-larkin-holavarri" width="500" height="385" /></div>
<div class="float">
<h2>2005 - Tricia Salcido and Larkin Holavarri Buy Softstar Shoes</h2>
<div class="block-scroll">
<div class="block-scroll-inner">
<p>Friends and business partners Tricia Salcido and Larkin Holavarri approach Tim about purchasing Softstar Shoes. Like Tim, they want to sell products that are healthy for their families (Tricia has one child and Larkin is pregnant with her first). Tim agrees and stays on to manage shoe production while the new owners focus on growing the business. Their first priority: online checkout.</p>
<p>The new owners also explore new ways to encourage Softstar’s core value of “walking lightly on the earth,” solar panels are installed on the workshop’s roof and all power is sourced from renewable energy. Other sustainable measures include composting, reusable towels, a workshop recycling program, donating leather scraps for crafts and providing incentives for employees to bike to work.</p>
</div>
</div>
</div>
</div>
<div id="div8" class="item targetDiv">
<div class="float"><img title="2010 Softstar RunAmocs become popular minimal running shoes." src="{{media url="wysiwyg/About-us/History/softstar-history-2010.jpg"}}" alt="2010-softstar-runamoc-minimalist-running-shoes" width="500" height="385" /></div>
<div class="float">
<h2>2010 - Softstar RunAmocs become popular minimal running shoes.</h2>
<div class="block-scroll">
<div class="block-scroll-inner">
<p>As barefoot and minimal running become popular, many customers call to say they are running races in Softstar’s moccasins. After months of experimenting, the moccasin is modified into a running shoe with ankle laces and a rubber sole. Fans vote to choose the name RunAmoc for this new shoe, which exceeds all expectations for sales. Within the next 12 months, the Softstar workshop and staff double to keep up with RunAmoc orders. Softstar's designers begin to develop an entire line of minimal shoes for adults.</p>
</div>
</div>
</div>
</div>
<div id="div9" class="item targetDiv">
<div class="float"><img title="2014 Softstar benefits working mothers" src="{{media url="wysiwyg/About-us/History/softstar-history-2014.jpg"}}" alt="2014-working-mothers-at-softstar-shoes" width="500" height="385" /></div>
<div class="float">
<h2>2014 - Softstar benefits working mothers</h2>
<div class="block-scroll">
<div class="block-scroll-inner">
<p>Child and adult shoe styles continue to multiply, and so do the Softstar families! With the birth of baby Shel, Tricia and Larkin end up with three kids each and Tim has his second grandchild. Understanding the struggle of working parents, they maintain a kid-friendly policy at Softstar. In addition to family leave benefits, employees can bring children to work and schedule changes are made easy.</p>
</div>
</div>
</div>
</div>
<div id="div10" class="item targetDiv">
<div class="float"><img title="2017Softstar moves to bigger workshop in Philomath, Oregon" src="{{media url="wysiwyg/About-us/History/softstar-history-2017.jpg"}}" alt="2017-softstar-moves-to-philomath-oregon" width="500" height="385" /></div>
<div class="float">
<h2>2017 - Softstar moves to bigger workshop in Philomath, Oregon</h2>
<div class="block-scroll">
<div class="block-scroll-inner">
<p>When the Corvallis workshop ran out of growing room, Tricia and Larkin began restoration of a historic building in neighboring Philomath, Oregon to be the new home of Softstar Shoes. The new workshop and retail space officially opened in February, 2017.</p>
</div>
</div>
</div>
</div>
</div>
<div class="timeline-year"><a class="item" target="1"> <span>1985</span> </a> <a class="item" target="2"> <span>1986</span> </a> <a class="item" target="3"> <span>1987</span> </a> <a class="item" target="4"> <span>1990</span> </a> <a class="item" target="5"> <span>1995</span> </a> <a class="item" target="6"> <span>2001</span> </a> <a class="item" target="7"> <span>2005</span> </a> <a class="item" target="8"> <span>2010</span> </a> <a class="item" target="9"> <span>2014</span> </a> <a class="item" target="10"> <span>2017</span> </a></div>
</div>
</div>
</div>
<p><a name="meetus"></a></p>
<div class="block-people">
<div class="block-title">
<h2>Meet the Shoemaking Elves</h2>
<span>Our Elves are creative and talented artisans who actively participate in the shoe design process. We have 30 years of shoe-making experience at our disposal, and we are constantly working to find new ways to improve our work. Softstar is committed to helping all its team members maintain satisfying work and family lives, offering flexible scheduling, paid time off, and paid maternity/paternity leave. In an effort to encourage professional and personal growth, Softstar also provides funding for continuing education opportunities, empowering employees to expand their skills and pursue their passions. </span></div>
<div class="inner">
<div class="item">
<div class="thumbnail"><img title="Elf Tricia" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-tricia.jpg"}}" alt="softstar-staff-tricia" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Tricia</div>
<p>C.Elf.O</p>
<div>Favorite Shoe: <span>Moc3 RunAmoc</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Larkin" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-larkin.jpg"}}" alt="softstar-staff-larkin" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Larkin</div>
<p>Secret Agent Elf</p>
<div>Favorite Shoe: <span>Hawthorne Chukka</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Tim" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-tim.jpg"}}" alt="softstar-staff-Tim" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Tim</div>
<p>Founder &amp; Shoe Sherrif</p>
<div>Favorite Shoe: <span>Roo Moccasin</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Sarah" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-sarahm.jpg"}}" alt="softstar-staff-sarah" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Sarah</div>
<p>Chief People Officer</p>
<div>Favorite Shoe: <span>Ballerine</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Martin" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-martin.jpg"}}" alt="softstar-staff-martin" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Martin</div>
<p>Marketing Warlord</p>
<div>Favorite Shoe: <span>Primal RunAmoc</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Ali" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-ali.jpg"}}" alt="softstar-staff-ali" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Ali</div>
<p>Promotions Pioneer</p>
<div>Favorite Shoe: <span>Ballerine</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Tesla" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-tesla.jpg"}}" alt="softstar-staff-tesla" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Tesla</div>
<p>Lead Customer Elf</p>
<div>Favorite Shoe: <span>Ballerine</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Patty" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-patty.jpg"}}" alt="softstar-staff-patty" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Patty</div>
<p>Purchasing Elf</p>
<div>Favorite Shoe: <span>Fireside</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Keita" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-keita.jpg"}}" alt="softstar-staff-keita" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Keita</div>
<p>Efficiency Elf</p>
<div>Favorite Shoe: <span>Moc3</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Hava" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-hava.jpg"}}" alt="softstar-staff-hava" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Hava</div>
<p>Production Lead Elf</p>
<div>Favorite Shoe: <span>Roo Moccasin</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Elizabeth" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-elizabeth.jpg"}}" alt="softstar-staff-elizabeth" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Elizabeth</div>
<p>Production Lead Elf</p>
<div>Favorite Shoe: <span>Hawthorne Chukka</span></div>
</div>
</div>
</div>
<div class="item">
<div class="thumbnail"><img title="Elf Jasper" src="{{media url="wysiwyg/About-us/Staff-image/softstar-staff-jasper.jpg"}}" alt="softstar-staff-jasper" width="238" height="275" />
<div class="overflow">
<div class="name">Elf Jasper</div>
<p>Silent Partner</p>
<div>Favorite Shoe: <span>The chewy ones</span></div>
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript" xml="space">
    require([
            "jquery",
            "forix/plugins/fancybox",
            "domReady!"
        ], function($){
            $(".btn-play-video").fancybox({
                type: 'iframe',
                'margin': 9,
                'padding': 0
            });
        }

    );
</script>
<script type="text/javascript" xml="space"> 
    require([
        "jquery"
    ], function($){
        $('.targetDiv').hide();
        $('.timeline-year .item').click(function(event){
            $('.targetDiv').hide();
            $('#div'+$(this).attr('target')).show();
            $('.block-listyear .block-top').css('visibility','hidden');
            event.stopPropagation();
        });
        $(document).click(function(event) {
            if(!$(event.target).closest('.targetDiv').length) {
                if($('.targetDiv').is(":visible")) {
                    $('.targetDiv').hide();
                    $('.block-listyear .block-top').css('visibility','visible');
                }
            }
        });
    });
</script>
<script type="text/javascript" xml="space">
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'jquery/ui',
            'jquery/validate',
            'mage/translate',
            'slick'
        ],
        function ($, modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                clickableOverlay: false,
                modalClass: 'custom-modal',
                buttons: false
            };
            var popup2 = modal(options, $('.view-photo'));
            $(".photo-item").on('click', function () {
                position = $(this).attr('data-position');
                $('.slider-for').slick('slickGoTo', position);
                $(".view-photo").modal("openModal");
            });
        },
    );

</script>
<script type="text/javascript" xml="space">
    require(
        [
            'jquery'
        ],
        function ($) {
            $("#click-here").on('click', function () {
                $('.block-newspaper').addClass('show-item');

            });
        },
    );
</script>
<script type="text/javascript" xml="space"> 
    require(['jquery', 'slick'], function($){
        $(function(){
            $('.slider-for').slick({
                slidesToShow: 1,
                slidesToScroll: 1,
                arrows: true,
                fade: true,
                asNavFor: '.slider-nav'
            });
            $('.slider-nav').slick({
                slidesToShow: 11,
                slidesToScroll: 1,
                asNavFor: '.slider-for',
                dots: false,
                centerMode: true,
                focusOnSelect: true,
                arrows: false,
                variableWidth: true
            });
        });
    });
</script>