<!--
[[PageTitle]]: How It is Made
[[ContentHeading]]:
[[Layout]]: 1column
[[URLKey]]: how-made
-->

<div class="homepage-video video-popup">
    <img src="{{media url="wysiwyg/adult-sizeguide.jpg"}}" width="886" height="545" />
    <a class="btn-play-video fancybox-video" title="Play Video" href="https://www.youtube.com/embed/7O1bR_mjeYg?autoplay=1&amp;rel=0" data-fancybox="">
    <span class="icon-play-video"></span> </a>
</div>

<div class="block-text">
    <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.</p>
</div>
<div class="block-timeline block-point">
    <div class="block-title">
        <h1 class="number">
            1
        </h1>
        <div class="title">
            <span>Leather Selection and Di-Cutting</span>
        </div>
    </div>
</div>
<div id="made-product" class="banner-slider">

    <div class="owl-made-product owl-carousel">
        <div class="item"><img src="{{media url="wysiwyg/slide.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/sizeguide-1.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/sizeguide-2.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/slide.jpg"}}" alt="" /></div>
    </div>
</div>

<div class="block-timeline">
    <div class="box-item ">
       <div class="box-item-left point">
           <div class="inner">
        A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am the charm of existence in this spot, which was created for the bliss of souls like mine. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.
           </div>
       </div>
    </div>
    <div class="box-item">
        <div class="box-item-right point">
            <div class="inner">
        Talk about your leather and other materials, a <wonde></wonde>rful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the.
                <a href="#">More about our leather.</a>
            </div>
        </div>
    </div>
    <div class="box-item">
        <div class="box-item-left point">
            <div class="inner text-sort">
        We don’t use chemicals! Something
            </div>
        </div>
    </div>
    <div class="block-title">
        <h1 class="number">
            2
        </h1>
        <div class="title">
            <span>Piece Matching & Something</span>
        </div>
    </div>
</div>
<div id="made-product" class="banner-slider">
    <div class="owl-made-product owl-carousel">
        <div class="item"><img src="{{media url="wysiwyg/slide.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/sizeguide-1.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/sizeguide-2.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/slide.jpg"}}" alt="" /></div>
    </div>
</div>
<div class="block-timeline">
    <div class="box-item ">
        <div class="box-item-left point">
            <div class="inner">
                A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am the charm of existence in this spot, which was created for the bliss of souls like mine. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.
            </div>
        </div>
    </div>
    <div class="box-item">
        <div class="box-item-right point">
            <div class="inner">
                We actively stay on top of opportunities for improvements in our production processes and raw materials. In our workshop we use no dangerous chemicals or dyes in our manufacturing processes. We reuse, recycle and reduce whenever possible...
                <a href="#">More on our sustainable production methods.</a>
            </div>
        </div>
    </div>
    <div class="box-item">
        <div class="box-item-left point">
            <div class="inner text-sort">
                We don’t use Alast! Something here
            </div>
        </div>
    </div>
    <div class="block-title">
        <h1 class="number">
            3
        </h1>
        <div class="title">
            <span>Stitching & Trimming</span>
        </div>
    </div>
</div>
<div id="made-product" class="banner-slider">
    <div class="owl-made-product owl-carousel">
        <div class="item"><img src="{{media url="wysiwyg/slide.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/sizeguide-1.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/sizeguide-2.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/slide.jpg"}}" alt="" /></div>
    </div>
</div>
<div class="block-timeline">
    <div class="box-item ">
        <div class="box-item-left point">
            <div class="inner">
                A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am the charm of existence in this spot, which was created for the bliss of souls like mine. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.
            </div>
        </div>
    </div>
    <div class="box-item">
        <div class="box-item-right point">
            <div class="inner">
                Our team consists of experts who live and breath the art of sewing. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.
                <a href="#"> Meet the (shoemaking) elves.</a>
            </div>
        </div>
    </div>

    <div class="block-title">
        <h1 class="number">
            4
        </h1>
        <div class="title">
            <span>Sole Adhesion & Precision Trimming</span>
        </div>
    </div>
</div>

<div id="made-product" class="banner-slider">
    <div class="owl-made-product owl-carousel">
        <div class="item"><img src="{{media url="wysiwyg/slide.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/sizeguide-1.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/sizeguide-2.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/slide.jpg"}}" alt="" /></div>
    </div>
</div>
<div class="block-timeline">
    <div class="box-item ">
        <div class="box-item-left point">
            <div class="inner">
                A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am the charm of existence in this spot, which was created for the bliss of souls like mine. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.
            </div>
        </div>
    </div>
    <div class="box-item">
        <div class="box-item-right point">
            <div class="inner">
                Talk about your Vibram soles. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.
                <a href="#"> Meet the (shoemaking) elves.</a>
            </div>
        </div>
    </div>
    <div class="box-item ">
        <div class="box-item-left point">
            <div class="inner">
                We use the same rubber trimmers on our shoe soles as we did 30 years ago. Operated by hand, these machines allow us to achieve the highest level of hand-crafted precision.
            </div>
        </div>
    </div>
    <div class="block-title">
        <h1 class="number">
            5
        </h1>
        <div class="title">
            <span>Perfecting & Packing</span>
        </div>
    </div>
</div>


<div id="made-product" class="banner-slider">
    <div class="owl-made-product owl-carousel">
        <div class="item"><img src="{{media url="wysiwyg/slide.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/sizeguide-1.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/sizeguide-2.jpg"}}" alt="" /></div>
        <div class="item"><img src="{{media url="wysiwyg/slide.jpg"}}" alt="" /></div>
    </div>
</div>
<div class="block-timeline">
    <div class="box-item ">
        <div class="box-item-left point">
            <div class="inner">
                A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am the charm of existence in this spot, which was created for the bliss of souls like mine. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.
            </div>
        </div>
    </div>
    <div class="box-item">
        <div class="box-item-right point">
            <div class="inner">
                We use minimal packaging to ship our products...just enough to keep them looking great. When possible, we ship our shoes using recycled/recyclable poly mailers. Our more structured shoes are shipped in recyclable boxes, wrapped with tissue paper made from 100% recycled materials and packed with paper we reuse from other local businesses. We take pride in our substainabliity.
            </div>
        </div>
    </div>
    <div class="box-bottom">
        <div class="inner">
        <span>Something about receiving shoes and becoming a happy Softstar user.</span>

        <a href="#">What to know more about us? Read on.</a>
        </div>
    </div>

</div>


<script type="text/javascript" xml="space">
    require([
        'jquery',
        'owl'
    ], function ($) {
        $(".owl-made-product").owlCarousel({
            navigation: true,
            items : 2,
            stagePadding: 50,
            mouseDrag: true,
            loop:true,
            margin:0,
            touchDrag: true,
            pullDrag: true,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:2
                },
                1000:{
                    items:2
                },
                1440:{
                    items:3
                }
            }
        });
        $(document).ready(function() {
            $('#play-video').on('click', function(ev) {

                $("#video")[0].src += "&autoplay=1";
                ev.preventDefault();

            });
        });
    });
</script>

<script type="text/javascript" xml="space">
    require([
        "jquery",
        "forix/plugins/fancybox",
        "domReady!"
    ], function($){
        $(".btn-play-video").fancybox({
            type: 'iframe',
            'margin': 9,
            'padding': 0
        });
    });
</script>