<!--
[[PageTitle]]: Sizing Guide
[[ContentHeading]]:
[[Layout]]: 1column
[[URLKey]]: sizing-guide
-->
<div>
<div class="home-tab-container">
<ul class="tabs">
<li>
<h2><a class="category-link category-link-autoload" href="#tab-parent-3" data-cid="3">Adult &amp; Youth Sizing</a></h2>
</li>
<li>
<h2><a class="category-link" href="#tab-parent-9" data-cid="9">Child Sizing</a></h2>
</li>
</ul>
<div id="tab-parent-3" class="tab_content">
<div class="content">
<div class="homepage-cms-container-1">
<h2 class="title-main">Adult &amp; Youth Sizing</h2>
<!-- end -->
<div class="block-line">
<div class="homepage-introduce float">
<h4>How To Measure Your Foot Size</h4>
<p>You can measure feet at home using a book, a ruler and a wall (this method is also shown in our sizing videos above). You can then scroll down and see where your measurement fits on our sizing charts to find the recommended shoe size.</p>
<p>Note: we do not recommend tracing your feet because doing so usually gives a larger measurement. Our sizing charts work in accordance with the following method.</p>
<p>To measure your feet:</p>
<!-- end --><section class="block-feet">
<div class="block-images">
<div><span class="number"> 1 </span> <img title="Sizing guide" src="{{media url="wysiwyg/sizeguide-1.jpg"}}" alt="Sizing guide" width="321" height="233" /></div>
<div class="block-content">Remove shoes and socks and place the bare foot so that the heel is barely touching a wall.</div>
</div>
<div class="block-images">
<div><span class="number"> 2 </span> <img title="Sizing guide" src="{{media url="wysiwyg/sizeguide-2.jpg"}}" alt="Sizing guide" width="321" height="233" /></div>
<div class="block-content">Remove shoes and socks and place the bare foot so that the heel is barely touching a wall.</div>
</div>
<div class="block-images">
<div><span class="number"> 3 </span> <img title="Sizing guide" src="{{media url="wysiwyg/CMS/sizeguide-3.jpg"}}" alt="Sizing guide" width="321" height="233" /></div>
<div class="block-content">Remove shoes and socks and place the bare foot so that the heel is barely touching a wall.</div>
</div>
</section><!-- end --></div>
<div class="homepage-introduce float">
<h4>Size Charts</h4>
<section class="tab-sizing">
<div class="tabClick"><a>Youth Size Chart </a><span></span></div>
<div id="div1" class="targetDiv"><ol>
<li>Wiggle/growing room is already taken into account.</li>
<li>If your child is on the border between two sizes then we recommend the larger size.</li>
<li>We recommend using the metric (cm) column with your measurement, since it is more precise.</li>
</ol>
<div class="table-wrapper guide">
<table class="data table table-guide table-guide-type-2">
<thead>
<tr><th class="cell product">Soft Star Youth Size</th><th class="cell product">Approx Age R</th><th class="cell product">Length in Centimeters</th><th class="cell product">Length in Inches</th></tr>
</thead>
<tbody>
<tr>
<td colspan="" rowspan="" headers="">1Y</td>
<td colspan="" rowspan="" headers="">4 - 6 Years</td>
<td colspan="" rowspan="" headers="">18.5 - 19.4 cm</td>
<td colspan="" rowspan="" headers="">7 ¼” - 7 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">2Y</td>
<td colspan="" rowspan="" headers="">5 - 8 Years</td>
<td colspan="" rowspan="" headers="">19.4 - 20.2 cm</td>
<td colspan="" rowspan="" headers="">7 ⅝” - 7 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">3Y</td>
<td colspan="" rowspan="" headers="">5 - 8 Years</td>
<td colspan="" rowspan="" headers="">20.2 - 21.0 cm</td>
<td colspan="" rowspan="" headers="">7 ⅞” - 8 ¼”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">4Y</td>
<td colspan="" rowspan="" headers="">6 - 10 Years</td>
<td colspan="" rowspan="" headers="">21.0 - 21.9 cm</td>
<td colspan="" rowspan="" headers="">8 ¼” - 8 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">5Y</td>
<td colspan="" rowspan="" headers="">6 - 10 Years</td>
<td colspan="" rowspan="" headers="">21.9 - 22.7 cm</td>
<td colspan="" rowspan="" headers="">8 ⅝” - 8 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">6Y</td>
<td colspan="" rowspan="" headers="">8 - 12 Years</td>
<td colspan="" rowspan="" headers="">22.7 - 23.6 cm</td>
<td colspan="" rowspan="" headers="">8 ⅞” - 9 ¼”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">7Y</td>
<td colspan="" rowspan="" headers="">8 - 12 Years</td>
<td colspan="" rowspan="" headers="">23.6 - 24.4 cm</td>
<td colspan="" rowspan="" headers="">9 ¼” - 9 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">8Y</td>
<td colspan="" rowspan="" headers="">12+ Years</td>
<td colspan="" rowspan="" headers="">24.4 - 25.3 cm</td>
<td colspan="" rowspan="" headers="">9 ⅝” - 9 ⅞”</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tabClick"><a>Adult Size Chart</a><span></span></div>
<div id="div2" class="targetDiv"><ol>
<li>If you are on the border between two sizes then we recommend the larger size.</li>
<li>When possible, we recommend using the metric (cm) column with your measurement, since it is more precise.</li>
<li>Wide or narrow? If you have never found you needed wide or narrow shoes in the past then we suggest sticking with our regular width. If you think your feet need wide or narrow shoes then please consult the width chart below.</li>
</ol>
<div class="table-wrapper guide">
<table class="data table table-guide table-guide-type-2">
<thead>
<tr><th class="cell product">Soft Star Adult Size</th><th class="cell product">Regular US Shoes Size</th><th class="cell product">Length in Centimeters</th><th class="cell product">Length in Inches</th></tr>
</thead>
<tbody>
<tr>
<td colspan="" rowspan="" headers="">4U</td>
<td colspan="" rowspan="" headers="">4.4 - 5 Womens</td>
<td colspan="" rowspan="" headers="">20.7 - 22.2 cm</td>
<td colspan="" rowspan="" headers="">8 ⅜” - 8 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">5U</td>
<td colspan="" rowspan="" headers="">5.5 - 6 Womens</td>
<td colspan="" rowspan="" headers="">22.2 - 23.0 cm</td>
<td colspan="" rowspan="" headers="">8 ¾” - 9 ”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">6U</td>
<td colspan="" rowspan="" headers="">6.5 - 7 Womens</td>
<td colspan="" rowspan="" headers="">23.0 - 23.9 cm</td>
<td colspan="" rowspan="" headers="">9” - 9 ⅜”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">7U</td>
<td colspan="" rowspan="" headers="">6.5 - 7 Mens<br />7.8 - 8 Womens</td>
<td colspan="" rowspan="" headers="">23.9 - 24.7 cm</td>
<td colspan="" rowspan="" headers="">9 ⅜” - 9 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">8U</td>
<td colspan="" rowspan="" headers="">7.5 - 8 Mens<br />8.5 - 9 Womens</td>
<td colspan="" rowspan="" headers="">24.7 - 25.8 cm</td>
<td colspan="" rowspan="" headers="">9 ¾” - 10”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">9U</td>
<td colspan="" rowspan="" headers="">8.5 - 9 Womens</td>
<td colspan="" rowspan="" headers="">25.6 - 26.4 cm</td>
<td colspan="" rowspan="" headers="">10” - 10 ⅜”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">10U</td>
<td colspan="" rowspan="" headers="">9.5 - 10 Womens</td>
<td colspan="" rowspan="" headers="">26.4 - 27.3 cm</td>
<td colspan="" rowspan="" headers="">10 ⅜” - 10 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">11U</td>
<td colspan="" rowspan="" headers="">10.5 - 11 Womens</td>
<td colspan="" rowspan="" headers="">27.3 - 28.1 cm</td>
<td colspan="" rowspan="" headers="">10 ¾” - 11”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">12U</td>
<td colspan="" rowspan="" headers="">11.5 - 12 Mens</td>
<td colspan="" rowspan="" headers="">28.1 - 28.9 cm</td>
<td colspan="" rowspan="" headers="">11” - 11 ⅜”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">13U</td>
<td colspan="" rowspan="" headers="">12.5 - 13 Mens</td>
<td colspan="" rowspan="" headers="">28.9 - 29.8 cm</td>
<td colspan="" rowspan="" headers="">11 ¾” - 11 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">14U</td>
<td colspan="" rowspan="" headers="">13.5 - 14 Mens</td>
<td colspan="" rowspan="" headers="">29.8 - 30.5 cm</td>
<td colspan="" rowspan="" headers="">11 ¾” - 12”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">15U</td>
<td colspan="" rowspan="" headers="">14.5 - 15 Mens</td>
<td colspan="" rowspan="" headers="">30.5 - 31.4 cm</td>
<td colspan="" rowspan="" headers="">12” - 12 ⅜”</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tabClick"><a>Width Chart (All Ages)</a><span></span></div>
<div id="div3" class="targetDiv">
<p>Consult the chart below to determine your recommended width. Please note that this chart shows average measurements, but the height of your instep and the shape of your foot can also affect the width that fits best so these recommendations may not work for everyone. If you have never needed wide or narrow shoes in the past then a regular width will likely work best. If you normally need a wide shoe in other brands then we recommend ordering a wide width, even if you fall in to the regular width range on this chart.</p>
<p><strong>Using the Width Chart:</strong></p>
<ol>
<li>To measure your width, use the method described above in the "No Printer, No Problem" section. Just turn your foot so it is parallel to the wall and use a book to mark and measure the distance. Only the outside edge of the ball of your foot should be touching the wall (don't press your heel against the wall—just let it sit between the wall and the book).</li>
<li>If the width of your foot is below the range listed for your size then a narrow shoe is recommended. If your width is above the range then a wide shoe is recommended.</li>
<li>When possible, we recommend using the metric (cm) column with your measurement, since it is more precise.</li>
</ol>
<div class="table-wrapper guide">
<table class="data table table-guide table-guide-type-2">
<thead>
<tr><th class="cell product">Child Size</th><th class="cell product">Approx Age R</th><th class="cell product">Range of Regular Width (cm)</th><th class="cell product">Range of Regular Width (inches)</th></tr>
</thead>
<tbody>
<tr>
<td colspan="" rowspan="" headers="">2</td>
<td colspan="" rowspan="" headers="">0 - 6 months</td>
<td colspan="" rowspan="" headers="">4.3 - 5.9 cm</td>
<td colspan="" rowspan="" headers="">1 ⅝” - 2 ¼”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">3</td>
<td colspan="" rowspan="" headers="">6 - 12 months</td>
<td colspan="" rowspan="" headers="">4.6 - 6.2 cm</td>
<td colspan="" rowspan="" headers="">1 ¾” - 2 ½”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">4</td>
<td colspan="" rowspan="" headers="">12 - 18 months</td>
<td colspan="" rowspan="" headers="">5.0 - 6.6 cm</td>
<td colspan="" rowspan="" headers="">2” - 2 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">5</td>
<td colspan="" rowspan="" headers="">18 months</td>
<td colspan="" rowspan="" headers="">5.3 - 6.9 cm</td>
<td colspan="" rowspan="" headers="">2 ⅛” - 2 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">6</td>
<td colspan="" rowspan="" headers="">18 - 24 months</td>
<td colspan="" rowspan="" headers="">5.6 - 7.2 cm</td>
<td colspan="" rowspan="" headers="">2 ¼” - 2 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">7</td>
<td colspan="" rowspan="" headers="">2 years</td>
<td colspan="" rowspan="" headers="">5.7 - 7.3 cm</td>
<td colspan="" rowspan="" headers="">2⅜” - 2 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">8</td>
<td colspan="" rowspan="" headers="">2 - 3 years</td>
<td colspan="" rowspan="" headers="">6.0 - 7.6 cm</td>
<td colspan="" rowspan="" headers="">2 ⅜” - 3”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">9</td>
<td colspan="" rowspan="" headers="">3 years</td>
<td colspan="" rowspan="" headers="">6.4 - 8.0 cm</td>
<td colspan="" rowspan="" headers="">2 ½” - 3 ⅛”</td>
</tr>
</tbody>
</table>
</div>
<div class="table-wrapper guide">
<table class="data table table-guide table-guide-type-2">
<thead>
<tr><th class="cell product">Youth Size</th><th class="cell product">Approx Age R</th><th class="cell product">Length in Centimeters</th><th class="cell product">Length in Inches</th></tr>
</thead>
<tbody>
<tr>
<td colspan="" rowspan="" headers="">1Y</td>
<td colspan="" rowspan="" headers="">4 - 6 Years</td>
<td colspan="" rowspan="" headers="">18.5 - 19.4 cm</td>
<td colspan="" rowspan="" headers="">7 ¼” - 7 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">2Y</td>
<td colspan="" rowspan="" headers="">5 - 8 Years</td>
<td colspan="" rowspan="" headers="">19.4 - 20.2 cm</td>
<td colspan="" rowspan="" headers="">7 ⅝” - 7 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">3Y</td>
<td colspan="" rowspan="" headers="">5 - 8 Years</td>
<td colspan="" rowspan="" headers="">20.2 - 21.0 cm</td>
<td colspan="" rowspan="" headers="">7 ⅞” - 8 ¼”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">4Y</td>
<td colspan="" rowspan="" headers="">6 - 10 Years</td>
<td colspan="" rowspan="" headers="">21.0 - 21.9 cm</td>
<td colspan="" rowspan="" headers="">8 ¼” - 8 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">5Y</td>
<td colspan="" rowspan="" headers="">6 - 10 Years</td>
<td colspan="" rowspan="" headers="">21.9 - 22.7 cm</td>
<td colspan="" rowspan="" headers="">8 ⅝” - 8 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">6Y</td>
<td colspan="" rowspan="" headers="">8 - 12 Years</td>
<td colspan="" rowspan="" headers="">22.7 - 23.6 cm</td>
<td colspan="" rowspan="" headers="">8 ⅞” - 9 ¼”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">7Y</td>
<td colspan="" rowspan="" headers="">8 - 12 Years</td>
<td colspan="" rowspan="" headers="">23.6 - 24.4 cm</td>
<td colspan="" rowspan="" headers="">9 ¼” - 9 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">8Y</td>
<td colspan="" rowspan="" headers="">12+ Years</td>
<td colspan="" rowspan="" headers="">24.4 - 25.3 cm</td>
<td colspan="" rowspan="" headers="">9 ⅝” - 9 ⅞”</td>
</tr>
</tbody>
</table>
</div>
<div class="table-wrapper guide">
<table class="data table table-guide table-guide-type-2">
<thead>
<tr><th class="cell product">Adult Size</th><th class="cell product">Regular US Shoes Size</th><th class="cell product">Length in Centimeters</th><th class="cell product">Length in Inches</th></tr>
</thead>
<tbody>
<tr>
<td colspan="" rowspan="" headers="">4U</td>
<td colspan="" rowspan="" headers="">4.4 - 5 Womens</td>
<td colspan="" rowspan="" headers="">20.7 - 22.2 cm</td>
<td colspan="" rowspan="" headers="">8 ⅜” - 8 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">5U</td>
<td colspan="" rowspan="" headers="">5.5 - 6 Womens</td>
<td colspan="" rowspan="" headers="">22.2 - 23.0 cm</td>
<td colspan="" rowspan="" headers="">8 ¾” - 9 ”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">6U</td>
<td colspan="" rowspan="" headers="">6.5 - 7 Womens</td>
<td colspan="" rowspan="" headers="">23.0 - 23.9 cm</td>
<td colspan="" rowspan="" headers="">9” - 9 ⅜”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">7U</td>
<td colspan="" rowspan="" headers="">6.5 - 7 Mens<br />7.8 - 8 Womens</td>
<td colspan="" rowspan="" headers="">23.9 - 24.7 cm</td>
<td colspan="" rowspan="" headers="">9 ⅜” - 9 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">8U</td>
<td colspan="" rowspan="" headers="">7.5 - 8 Mens<br />8.5 - 9 Womens</td>
<td colspan="" rowspan="" headers="">24.7 - 25.8 cm</td>
<td colspan="" rowspan="" headers="">9 ¾” - 10”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">9U</td>
<td colspan="" rowspan="" headers="">8.5 - 9 Womens</td>
<td colspan="" rowspan="" headers="">25.6 - 26.4 cm</td>
<td colspan="" rowspan="" headers="">10” - 10 ⅜”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">10U</td>
<td colspan="" rowspan="" headers="">9.5 - 10 Womens</td>
<td colspan="" rowspan="" headers="">26.4 - 27.3 cm</td>
<td colspan="" rowspan="" headers="">10 ⅜” - 10 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">11U</td>
<td colspan="" rowspan="" headers="">10.5 - 11 Womens</td>
<td colspan="" rowspan="" headers="">27.3 - 28.1 cm</td>
<td colspan="" rowspan="" headers="">10 ¾” - 11”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">12U</td>
<td colspan="" rowspan="" headers="">11.5 - 12 Mens</td>
<td colspan="" rowspan="" headers="">28.1 - 28.9 cm</td>
<td colspan="" rowspan="" headers="">11” - 11 ⅜”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">13U</td>
<td colspan="" rowspan="" headers="">12.5 - 13 Mens</td>
<td colspan="" rowspan="" headers="">28.9 - 29.8 cm</td>
<td colspan="" rowspan="" headers="">11 ¾” - 11 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">14U</td>
<td colspan="" rowspan="" headers="">13.5 - 14 Mens</td>
<td colspan="" rowspan="" headers="">29.8 - 30.5 cm</td>
<td colspan="" rowspan="" headers="">11 ¾” - 12”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">15U</td>
<td colspan="" rowspan="" headers="">14.5 - 15 Mens</td>
<td colspan="" rowspan="" headers="">30.5 - 31.4 cm</td>
<td colspan="" rowspan="" headers="">12” - 12 ⅜”</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section class="homepage-video">
<div><img title="sizeguide" src="{{media url="wysiwyg/CMS/adult-sizeguide.jpg"}}" alt="sizeguide" width="886" height="545" /> <a class="btn-play-video fancybox-video" title="Play Video" href="https://www.youtube.com/embed/7O1bR_mjeYg?autoplay=1&amp;rel=0" data-fancybox=""> <span class="icon-play-video"></span> </a></div>
</section>
<h4>Difficulty Taking Your Measurement? Try Our Print-Out</h4>
<p>Unsure about your size? Our printable guides will help you find the best fit for your feet! Just print the guide for the appropriate age group below and follow the instructions on the page (if you don't have access to a printer then click here or scroll down for another option).</p>
<p>Note: before you print these guides, make sure your printer settings will not shrink or scale the page. Uncheck any boxes labeled "Fit to Printable Area" and/or set scaling options to "None."</p>
<p>Want more details? Check out our videos for more sizing tips and visual step-by-step instructions:</p>
<div class="thumbnail float">
<div class="box-img"><img title="The Pulpit Rock" src="{{media url="wysiwyg/CMS/sizing-3.jpg"}}" alt="The Pulpit Rock" width="299" height="340" /></div>
<span class="img-caption">Download: <a href="{{media url="wysiwyg/CMS/Find_Your_Size_Adult.pdf"}}" target="_blank"><span>Adult Sizing Guide</span></a></span></div>
<div class="thumbnail float">
<div class="box-img"><img title="The Pulpit Rock" src="{{media url="wysiwyg/CMS/sizing_4.jpg"}}" alt="The Pulpit Rock" width="299" height="340" /></div>
<span class="img-caption">Download: <a href="{{media url="wysiwyg/CMS/Find_Your_Size_Adult.pdf"}}" target="_blank"><span>Youth Sizing Guide</span></a></span></div>
</div>
</div>
</div>
<!-- end homepage-cms-container-1 --></div>
</div>
<div id="tab-parent-9" class="tab_content" style="display: block;">
<div class="content">
<div class="homepage-cms-container-1">
<h2 class="title-main">Child Sizing</h2>
<!-- end -->
<div class="block-line">
<div class="homepage-introduce float">
<h4>How To Measure Your Foot Size</h4>
<p>You can measure feet at home using a book, a ruler and a wall (this method is also shown in our sizing videos above). You can then scroll down and see where your measurement fits on our sizing charts to find the recommended shoe size.</p>
<p>Note: we do not recommend tracing your feet because doing so usually gives a larger measurement. Our sizing charts work in accordance with the following method.</p>
<p>To measure your feet:</p>
<!-- end --><section class="block-feet">
<div class="block-images">
<div><span class="number"> 1 </span> <img title="Sizing guide" src="{{media url="wysiwyg/sizeguide-1.jpg"}}" alt="Sizing guide" width="321" height="233" /></div>
<div class="block-content">Remove shoes and socks and place the bare foot so that the heel is barely touching a wall.</div>
</div>
<div class="block-images">
<div><span class="number"> 2 </span> <img title="Sizing guide" src="{{media url="wysiwyg/sizeguide-2.jpg"}}" alt="Sizing guide" width="321" height="233" /></div>
<div class="block-content">Remove shoes and socks and place the bare foot so that the heel is barely touching a wall.</div>
</div>
<div class="block-images">
<div><span class="number"> 3 </span> <img title="Sizing guide" src="{{media url="wysiwyg/CMS/sizeguide-3.jpg"}}" alt="Sizing guide" width="321" height="233" /></div>
<div class="block-content">Remove shoes and socks and place the bare foot so that the heel is barely touching a wall.</div>
</div>
</section><!-- end --></div>
<div class="homepage-introduce float">
<h4>Size Charts</h4>
<section class="tab-sizing">
<div class="tabClick"><a>Child Size Chart </a><span></span></div>
<div id="div4" class="targetDiv"><ol>
<li>Wiggle/growing room is already taken into account.</li>
<li>If your child is on the border between two sizes then we recommend the larger size.</li>
<li>We recommend using the metric (cm) column with your measurement, since it is more precise.</li>
</ol>
<div class="table-wrapper guide">
<table class="data table table-guide table-guide-type-2">
<thead>
<tr><th class="cell product">Child Size</th><th class="cell product">Approx Age R</th><th class="cell product">Range of Regular Width (cm)</th><th class="cell product">Range of Regular Width (inches)</th></tr>
</thead>
<tbody>
<tr>
<td colspan="" rowspan="" headers="">2</td>
<td colspan="" rowspan="" headers="">0 - 6 months</td>
<td colspan="" rowspan="" headers="">4.3 - 5.9 cm</td>
<td colspan="" rowspan="" headers="">1 ⅝” - 2 ¼”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">3</td>
<td colspan="" rowspan="" headers="">6 - 12 months</td>
<td colspan="" rowspan="" headers="">4.6 - 6.2 cm</td>
<td colspan="" rowspan="" headers="">1 ¾” - 2 ½”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">4</td>
<td colspan="" rowspan="" headers="">12 - 18 months</td>
<td colspan="" rowspan="" headers="">5.0 - 6.6 cm</td>
<td colspan="" rowspan="" headers="">2” - 2 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">5</td>
<td colspan="" rowspan="" headers="">18 months</td>
<td colspan="" rowspan="" headers="">5.3 - 6.9 cm</td>
<td colspan="" rowspan="" headers="">2 ⅛” - 2 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">6</td>
<td colspan="" rowspan="" headers="">18 - 24 months</td>
<td colspan="" rowspan="" headers="">5.6 - 7.2 cm</td>
<td colspan="" rowspan="" headers="">2 ¼” - 2 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">7</td>
<td colspan="" rowspan="" headers="">2 years</td>
<td colspan="" rowspan="" headers="">5.7 - 7.3 cm</td>
<td colspan="" rowspan="" headers="">2⅜” - 2 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">8</td>
<td colspan="" rowspan="" headers="">2 - 3 years</td>
<td colspan="" rowspan="" headers="">6.0 - 7.6 cm</td>
<td colspan="" rowspan="" headers="">2 ⅜” - 3”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">9</td>
<td colspan="" rowspan="" headers="">3 years</td>
<td colspan="" rowspan="" headers="">6.4 - 8.0 cm</td>
<td colspan="" rowspan="" headers="">2 ½” - 3 ⅛”</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tabClick"><a>Width Chart (All Ages)</a><span></span></div>
<div id="div5" class="targetDiv">
<p>Consult the chart below to determine your recommended width. Please note that this chart shows average measurements, but the height of your instep and the shape of your foot can also affect the width that fits best so these recommendations may not work for everyone. If you have never needed wide or narrow shoes in the past then a regular width will likely work best. If you normally need a wide shoe in other brands then we recommend ordering a wide width, even if you fall in to the regular width range on this chart.</p>
<p><strong>Using the Width Chart:</strong></p>
<ol>
<li>To measure your width, use the method described above in the "No Printer, No Problem" section. Just turn your foot so it is parallel to the wall and use a book to mark and measure the distance. Only the outside edge of the ball of your foot should be touching the wall (don't press your heel against the wall—just let it sit between the wall and the book).</li>
<li>If the width of your foot is below the range listed for your size then a narrow shoe is recommended. If your width is above the range then a wide shoe is recommended.</li>
<li>When possible, we recommend using the metric (cm) column with your measurement, since it is more precise.</li>
</ol>
<div class="table-wrapper guide">
<table class="data table table-guide table-guide-type-2">
<thead>
<tr><th class="cell product">Child Size</th><th class="cell product">Approx Age R</th><th class="cell product">Range of Regular Width (cm)</th><th class="cell product">Range of Regular Width (inches)</th></tr>
</thead>
<tbody>
<tr>
<td colspan="" rowspan="" headers="">2</td>
<td colspan="" rowspan="" headers="">0 - 6 months</td>
<td colspan="" rowspan="" headers="">4.3 - 5.9 cm</td>
<td colspan="" rowspan="" headers="">1 ⅝” - 2 ¼”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">3</td>
<td colspan="" rowspan="" headers="">6 - 12 months</td>
<td colspan="" rowspan="" headers="">4.6 - 6.2 cm</td>
<td colspan="" rowspan="" headers="">1 ¾” - 2 ½”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">4</td>
<td colspan="" rowspan="" headers="">12 - 18 months</td>
<td colspan="" rowspan="" headers="">5.0 - 6.6 cm</td>
<td colspan="" rowspan="" headers="">2” - 2 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">5</td>
<td colspan="" rowspan="" headers="">18 months</td>
<td colspan="" rowspan="" headers="">5.3 - 6.9 cm</td>
<td colspan="" rowspan="" headers="">2 ⅛” - 2 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">6</td>
<td colspan="" rowspan="" headers="">18 - 24 months</td>
<td colspan="" rowspan="" headers="">5.6 - 7.2 cm</td>
<td colspan="" rowspan="" headers="">2 ¼” - 2 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">7</td>
<td colspan="" rowspan="" headers="">2 years</td>
<td colspan="" rowspan="" headers="">5.7 - 7.3 cm</td>
<td colspan="" rowspan="" headers="">2⅜” - 2 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">8</td>
<td colspan="" rowspan="" headers="">2 - 3 years</td>
<td colspan="" rowspan="" headers="">6.0 - 7.6 cm</td>
<td colspan="" rowspan="" headers="">2 ⅜” - 3”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">9</td>
<td colspan="" rowspan="" headers="">3 years</td>
<td colspan="" rowspan="" headers="">6.4 - 8.0 cm</td>
<td colspan="" rowspan="" headers="">2 ½” - 3 ⅛”</td>
</tr>
</tbody>
</table>
</div>
<div class="table-wrapper guide">
<table class="data table table-guide table-guide-type-2">
<thead>
<tr><th class="cell product">Youth Size</th><th class="cell product">Approx Age R</th><th class="cell product">Length in Centimeters</th><th class="cell product">Length in Inches</th></tr>
</thead>
<tbody>
<tr>
<td colspan="" rowspan="" headers="">1Y</td>
<td colspan="" rowspan="" headers="">4 - 6 Years</td>
<td colspan="" rowspan="" headers="">18.5 - 19.4 cm</td>
<td colspan="" rowspan="" headers="">7 ¼” - 7 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">2Y</td>
<td colspan="" rowspan="" headers="">5 - 8 Years</td>
<td colspan="" rowspan="" headers="">19.4 - 20.2 cm</td>
<td colspan="" rowspan="" headers="">7 ⅝” - 7 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">3Y</td>
<td colspan="" rowspan="" headers="">5 - 8 Years</td>
<td colspan="" rowspan="" headers="">20.2 - 21.0 cm</td>
<td colspan="" rowspan="" headers="">7 ⅞” - 8 ¼”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">4Y</td>
<td colspan="" rowspan="" headers="">6 - 10 Years</td>
<td colspan="" rowspan="" headers="">21.0 - 21.9 cm</td>
<td colspan="" rowspan="" headers="">8 ¼” - 8 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">5Y</td>
<td colspan="" rowspan="" headers="">6 - 10 Years</td>
<td colspan="" rowspan="" headers="">21.9 - 22.7 cm</td>
<td colspan="" rowspan="" headers="">8 ⅝” - 8 ⅞”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">6Y</td>
<td colspan="" rowspan="" headers="">8 - 12 Years</td>
<td colspan="" rowspan="" headers="">22.7 - 23.6 cm</td>
<td colspan="" rowspan="" headers="">8 ⅞” - 9 ¼”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">7Y</td>
<td colspan="" rowspan="" headers="">8 - 12 Years</td>
<td colspan="" rowspan="" headers="">23.6 - 24.4 cm</td>
<td colspan="" rowspan="" headers="">9 ¼” - 9 ⅝”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">8Y</td>
<td colspan="" rowspan="" headers="">12+ Years</td>
<td colspan="" rowspan="" headers="">24.4 - 25.3 cm</td>
<td colspan="" rowspan="" headers="">9 ⅝” - 9 ⅞”</td>
</tr>
</tbody>
</table>
</div>
<div class="table-wrapper guide">
<table class="data table table-guide table-guide-type-2">
<thead>
<tr><th class="cell product">Adult Size</th><th class="cell product">Regular US Shoes Size</th><th class="cell product">Length in Centimeters</th><th class="cell product">Length in Inches</th></tr>
</thead>
<tbody>
<tr>
<td colspan="" rowspan="" headers="">4U</td>
<td colspan="" rowspan="" headers="">4.4 - 5 Womens</td>
<td colspan="" rowspan="" headers="">20.7 - 22.2 cm</td>
<td colspan="" rowspan="" headers="">8 ⅜” - 8 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">5U</td>
<td colspan="" rowspan="" headers="">5.5 - 6 Womens</td>
<td colspan="" rowspan="" headers="">22.2 - 23.0 cm</td>
<td colspan="" rowspan="" headers="">8 ¾” - 9 ”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">6U</td>
<td colspan="" rowspan="" headers="">6.5 - 7 Womens</td>
<td colspan="" rowspan="" headers="">23.0 - 23.9 cm</td>
<td colspan="" rowspan="" headers="">9” - 9 ⅜”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">7U</td>
<td colspan="" rowspan="" headers="">6.5 - 7 Mens<br />7.8 - 8 Womens</td>
<td colspan="" rowspan="" headers="">23.9 - 24.7 cm</td>
<td colspan="" rowspan="" headers="">9 ⅜” - 9 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">8U</td>
<td colspan="" rowspan="" headers="">7.5 - 8 Mens<br />8.5 - 9 Womens</td>
<td colspan="" rowspan="" headers="">24.7 - 25.8 cm</td>
<td colspan="" rowspan="" headers="">9 ¾” - 10”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">9U</td>
<td colspan="" rowspan="" headers="">8.5 - 9 Womens</td>
<td colspan="" rowspan="" headers="">25.6 - 26.4 cm</td>
<td colspan="" rowspan="" headers="">10” - 10 ⅜”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">10U</td>
<td colspan="" rowspan="" headers="">9.5 - 10 Womens</td>
<td colspan="" rowspan="" headers="">26.4 - 27.3 cm</td>
<td colspan="" rowspan="" headers="">10 ⅜” - 10 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">11U</td>
<td colspan="" rowspan="" headers="">10.5 - 11 Womens</td>
<td colspan="" rowspan="" headers="">27.3 - 28.1 cm</td>
<td colspan="" rowspan="" headers="">10 ¾” - 11”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">12U</td>
<td colspan="" rowspan="" headers="">11.5 - 12 Mens</td>
<td colspan="" rowspan="" headers="">28.1 - 28.9 cm</td>
<td colspan="" rowspan="" headers="">11” - 11 ⅜”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">13U</td>
<td colspan="" rowspan="" headers="">12.5 - 13 Mens</td>
<td colspan="" rowspan="" headers="">28.9 - 29.8 cm</td>
<td colspan="" rowspan="" headers="">11 ¾” - 11 ¾”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">14U</td>
<td colspan="" rowspan="" headers="">13.5 - 14 Mens</td>
<td colspan="" rowspan="" headers="">29.8 - 30.5 cm</td>
<td colspan="" rowspan="" headers="">11 ¾” - 12”</td>
</tr>
<tr>
<td colspan="" rowspan="" headers="">15U</td>
<td colspan="" rowspan="" headers="">14.5 - 15 Mens</td>
<td colspan="" rowspan="" headers="">30.5 - 31.4 cm</td>
<td colspan="" rowspan="" headers="">12” - 12 ⅜”</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section class="homepage-video">
<div><img title="sizeguide" src="{{media url="wysiwyg/CMS/child_image.jpg"}}" alt="sizeguide" width="886" height="545" /> <a class="btn-play-video fancybox-video" title="Play Video" href="https://www.youtube.com/embed/7O1bR_mjeYg?autoplay=1&amp;rel=0" data-fancybox=""> <span class="icon-play-video"></span> </a></div>
</section>
<h4>Difficulty Taking Your Measurement? Try Our Print-Out</h4>
<p>Unsure about your size? Our printable guides will help you find the best fit for your feet! Just print the guide for the appropriate age group below and follow the instructions on the page (if you don't have access to a printer then click here or scroll down for another option).</p>
<p>Note: before you print these guides, make sure your printer settings will not shrink or scale the page. Uncheck any boxes labeled "Fit to Printable Area" and/or set scaling options to "None."</p>
<p>Want more details? Check out our videos for more sizing tips and visual step-by-step instructions:</p>
<div class="thumbnail">
<div class="box-img"><img title="The Pulpit Rock" src="{{media url="wysiwyg/CMS/minimal-barefoot-kids-shoes_1.png"}}" alt="The Pulpit Rock" /></div>
<span class="img-caption">Download: <a href="{{media url="wysiwyg/Child_Find_Your_Size.pdf"}}" target="_blank"><span>Child Sizing Guide</span></a></span></div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript" xml="space">
    require([
        "jquery"
    ], function($){
        $('ul.tabs').each(function() {

            var $active, $content, $links = $(this).find('a');
            $active = $($links.filter('[href="' + location.hash + '"]')[0] || $links[0]);
            $active.addClass('active');
            $content = $($active[0].hash);
            $links.not($active).each(function() {
                $(this.hash).hide();
            });
            $(this).on('click', 'a', function(e) {
                $active.removeClass('active');
                $content.hide();
                $active = $(this);
                $content = $(this.hash);
                $active.addClass('active');
                $content.show();
                e.preventDefault();
            });
        });
    });
</script>
<script type="text/javascript" xml="space">
    require([
        "jquery"
    ], function($){
        $('.targetDiv').hide();
        $('.tabClick').click(function(){
            $(this).next(".targetDiv").slideToggle();
            $(this).toggleClass('icon');
        });

    });
    
</script>