<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
//    $swatchBlock = $block->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable');
//    $swatchHelper = $this->helper('Forix\CatalogSwatchWidget\Helper\Data');
/*    if($this->helper('Forix\Base\Helper\Data')->isModuleEnabled('Forix_ProductLabel')) {
        $labelBlock = $block->getLayout()->createBlock("Forix\ProductLabel\Block\Product\Label")
            ->setTemplate("Forix_ProductLabel::product/label.phtml");
    }*/
?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?php echo $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content widget-slider-wrapper">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?> widget-slider" data-action="widget-slider">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                    <?php if ($iterator++ != 1): ?></li><?php endif ?>
                    <li class="product-item">
                        <div class="product-outer">
                            <div class="product-item-info">
                                <a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>" title="<?php echo $block->escapeHtml($_item->getName()) ?>" class="product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product-item-details">
                                    <label class="product attribute product-item-sku" data-mage-init='{"forix/formattext":{}}'>Sku <?php echo $_item->getSku() ?></label>
                                    <strong class="product-item-name">
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                           class="product-item-link" data-mage-init='{"forix/formattext":{}}'>
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>

                                    <?php
                                    echo $block->getProductPriceHtml($_item, $type);
                                    ?>

                                    <?php if ($templateType): ?>
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?>
                                    <?php endif; ?>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product-item-inner">
                                            <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                            <button class="action tocart primary" data-mage-init='{"redirectUrl":{"url":"<?php echo $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <?php
                                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <button class="action tocart primary" data-post='<?php /* @noEscape */ echo $postData ?>' type="button" title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available"><span><?php echo $block->escapeHtml(__('In stock')) ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?php /* @noEscape */ echo $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?php echo $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?php echo $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                        <a href="#" class="action tocompare" data-post='<?php /* @noEscape */ echo $compareHelper->getPostDataParams($_item) ?>' title="<?php echo $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <span><?php echo $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php echo ($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "[data-action='widget-slider']": {
                "forix/slick": {
                    "appendArrows": ".widget-slider-wrapper",
                    "appendDots": ".widget-slider-wrapper",
                    "fade": false,
                    "infinite": false,
                    "slidesToShow": 4,
                    "slidesToScroll": 4,
                    "responsive": [{
                          "breakpoint": 1024,
                          "settings": {
                            "slidesToShow": 4,
                            "slidesToScroll": 4
                          }
                        },
                        {
                          "breakpoint": 1023,
                          "settings": {
                            "slidesToShow": 3,
                            "slidesToScroll": 3
                          }
                        },
                        {
                          "breakpoint": 767,
                          "settings": {
                            "slidesToShow": 2,
                            "slidesToScroll": 1
                        }
                    }],
                    "speed": 300
                }
            }
        }
    </script>
    <script>
        require([
            "jquery"
        ], function($){
            $('.widget-slider').on('init', function(event, slick, direction){
                $('.widget-slider').addClass("slick-loaded");
            });
        });
    </script>
<?php endif;?>