<?php
/**
 * @category   Fishpig
 * @package   Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author     Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="block block-blog block-blog-follow-us">
	<div class="block-title">
		<strong><span><?php echo __('Follow Us') ?></span></strong>
	</div>
	<div class="block-content">
        <div class="social-links icon-wrapper-square">
            <a title="Join us on Facebook" href="http://www.facebook.com/SoftstarShoes" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a class="first" title="Follow Softstar on Twitter" href="http://twitter.com/softstarshoes" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            <a title="Instagram" href="http://instagram.com/softstarshoes" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a title="Pinterest" href="http://www.pinterest.com/softstarelves/" target="_blank"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
        </div>
	</div>
</div>