<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="block block-blog block-blog-search">
	<div class="block-content">
		<form method="get" action="<?php echo $this->getFormActionUrl() ?>" id="blog-search-form">
			<input type="hidden" name="post_type[]" value="article"/>
			<div class="blog-search">
				<?php if ($this->getPostType()): ?>
				<div class="no-display">
					<input type="hidden" name="post_type" value="<?php echo $this->getPostType() ?>" />
				</div>
				<?php endif; ?>
				<input type="text" name="s" class="input-text" title="<?php echo __('Search Posts') ?>" value="<?php echo $this->escapeHtml($this->getSearchTerm()) ?>" placeholder="<?php echo __('Search blog posts...') ?>"/>
				<button class="button" title="<?php echo __('Search') ?>" type="submit"><span><span><?php echo __('Search') ?></span></span></button>
			</div>
		</form>
	</div>
</div>