<?php

namespace Forix\Quote\Rewrite\Block\Quote;

class Items extends \Magento\NegotiableQuote\Block\Quote\Items
{
    /**
     * @return \Magento\NegotiableQuote\Api\Data\NegotiableQuoteInterface|null
     */
    public function getNegotiableQuote()
    {
        return parent::getNegotiableQuote(); // TODO: Change the autogenerated stub
    }
}