<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
if($this->helper('Forix\Base\Helper\Data')->isModuleEnabled('Forix_CatalogSwatchWidget')) {
    $swatchBlock = $block->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable');
    $swatchHelper = $this->helper('Forix\CatalogSwatchWidget\Helper\Data');
}
$referer =  (isset($_SERVER["HTTP_REFERER"]) && $_SERVER["HTTP_REFERER"]) ? $_SERVER["HTTP_REFERER"] : $block->getUrl();
?>
<?php $_total = $block->getItems()->getSize() ?>
<?php if ($_total): ?>
    <a href="#" class="action print" title="<?php /* @escapeNotVerified */ echo __('Print This Page') ?>">
        <span><?php /* @escapeNotVerified */ echo __('Print This Page') ?></span>
    </a>
    <div class="actions-toolbar compare-toolbar">
        <div class="primary">
            <a href="<?php echo $referer ?>" class="action back" title="<?php /* @escapeNotVerified */ echo __('Back to Previous Page') ?>"><span><?php /* @escapeNotVerified */ echo __('Back to Previous Page') ?></span></a>
        </div>
        <div class="secondary">
            <a id="compare-clear-all"  href="#" class="action clear" title="<?php /* @escapeNotVerified */ echo __('Remove All Items') ?>"><span><?php /* @escapeNotVerified */ echo __('Remove All Items') ?></span></a>
        </div>
    </div>
    <div class="table-wrapper comparison">
        <div class="slider-compare inner-slider slider-loading" data-mage-init='{"forix/slidertable":{}}'>
        <table class="data table table-comparison" id="product-comparison"
            data-mage-init='{"compareList":{
                "windowPrintSelector":".action.print",
                "productsInRow":"5",
                "selectors":{
                    "productAddToCartSelector":"button.action.tocart"}
            }}'>
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Compare Products') ?></caption>
            <thead>
            <tr>
                <?php $_i = 0 ?>
                <?php foreach ($block->getItems() as $_item): ?>
                    <?php if ($_i++ == 0): ?>
                        <th scope="row" class="cell label remove"><span><?php /* @escapeNotVerified */ echo __('Remove Product') ?></span></th>
                    <?php endif; ?>
                    <td class="cell remove product">
                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataRemove($_item); ?>'
                           class="action delete" title="<?php /* @escapeNotVerified */ echo __('Remove Product') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Remove Product') ?></span>
                        </a>
                    </td>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <tr class="col product">
                <?php $_i = 0; ?>
                <?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
                <?php /** @var $_item \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($block->getItems() as $_item): ?>
                    <?php if ($_i++ == 0): ?>
                        <th scope="row" class="cell label product"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
                    <?php endif; ?>
                    <td data-th="<?php echo $block->escapeHtml(__('Product')); ?>" data-label="<?php echo $block->escapeHtml(__('Product')); ?>" class="cell product info">
                        <a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
                            <?php echo $block->getImage($_item, 'product_comparison_list')->toHtml(); ?>
                        </a>
                        <strong class="product-item-name">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item, '-compare-list-top') ?>
                        <?php echo $block->getReviewsSummaryHtml($_item, 'short') ?>
                        <div class="product-item-actions">
                            <div class="actions-primary">
                                <?php if ($_item->isSaleable()): ?>
                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_item); ?>" method="post">
                                        <?php echo $block->getBlockHtml('formkey')?>
                                        <button type="submit" class="action tocart primary">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart'); ?></span>
                                        </button>
                                    </form>
                                <?php else: ?>
                                    <?php if ($_item->getIsSalable()): ?>
                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist" data-action="add-to-wishlist">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                    </a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </td>
                <?php endforeach; ?>
            </tr>
            <?php foreach ($block->getAttributes() as $_attribute): ?>
                <tr>
                    <?php $_i = 0 ?>
                    <?php foreach ($block->getItems() as $_item): ?>
                        <?php if ($_i++ == 0): ?>
                            <th scope="row" class="cell label <?php echo $_attribute->getAttributeCode(); ?>">
                                <span class="attribute label">
                                    <?php echo $block->escapeHtml($_attribute->getStoreLabel() ? $_attribute->getStoreLabel() : __($_attribute->getFrontendLabel())) ?>
                                </span>
                            </th>
                        <?php endif; ?>
                        <td class="cell product attribute <?php echo $_attribute->getAttributeCode(); ?>" data-label="<?php echo $block->escapeHtml($_attribute->getStoreLabel() ? $_attribute->getStoreLabel() : __($_attribute->getFrontendLabel())) ?>">
                            <div class="attribute value">
                                <?php
                                if($_attribute->getAttributeCode() == 'price') {
                                    /* @escapeNotVerified */ echo $block->getProductPrice(
                                        $_item,
                                        '-compare-list-' . $_attribute->getCode()
                                    );
                                }
                                else if($_attribute->getAttributeCode() == 'small_image') {
                                    $block->getImage($_item, 'product_small_image')->toHtml();
                                }
                                else if(isset($swatchBlock) && $_item->getTypeId() == 'configurable' &&
                                        $swatchHelper->isSwatchAttribute($_attribute) &&
                                        $swatchHelper->isProductHasSwatch($_item)) {
                                    $swatchBlock->setProduct($_item);
                                    $random_entityid = $_item->getEntityId() . '_' . $_attribute->getAttributeCode() . '_' . rand();
                                    $jsonSwatchConfigForCompare = $swatchHelper->getJsonSwatchConfigForCompare($swatchBlock->getJsonSwatchConfig(), $_attribute);
                                    if($jsonSwatchConfigForCompare != '[]') {
                                ?>
                                        <div class="swatch-opt-<?php echo $random_entityid ?>"></div>
                                        <script>
                                            require(["jquery", "jquery/ui", "Magento_Swatches/js/swatch-renderer"], function ($) {
                                                $('.swatch-opt-<?php echo $random_entityid ?>').SwatchRenderer({
                                                    selectorProduct: '.product-item-details',
                                                    onlySwatches: true,
                                                    enableControlLabel: false,
                                                    numberToShow: <?php echo $swatchBlock->getNumberSwatchesPerProduct(); ?>,
                                                    jsonConfig: <?php echo $swatchBlock->getJsonConfig(); ?>,
                                                    jsonSwatchConfig: <?php echo $swatchHelper->getJsonSwatchConfigForCompare( $swatchBlock->getJsonSwatchConfig(), $_attribute ); ?>,
                                                    mediaCallback: '<?php echo $swatchBlock->getMediaCallback() ?>'
                                                });
                                            });
                                        </script>
                                        <?php
                                    }
                                    else {
                                        /* @escapeNotVerified */ echo __('N/A');
                                    }
                                }
                                else {
                                    /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $block->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode());
                                }
                                ?>
                            </div>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form]": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
    <script>
        require([
            "jquery"
        ], function($){
            $('.slider-compare').on('slidertableafterload', function(){
                $(this).removeClass("slider-loading");
            });
        });
    </script>
<?php else: ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('You have no items to compare.') ?></div></div>
<?php endif; ?>

<script type="text/x-magento-init">
        {
            "*": {
                "Forix_Compare/js/ajaxcompare": {
                    "AjaxUrl": "<?php echo  $block->getUrl('f_compare/compare/clear') ?>",
                    "BackUrl": "<?php echo $referer ?>"
                }
            }
        }
</script>