<!--
[[PageTitle]]: Cms Default
[[ContentHeading]]: Cms Default
[[Layout]]:1column
-->
<div class="default-width">
   <h1>H1 HEADLINE GOES HERE</h1>
   <h2>H2 HEADLINE GOES HERE</h2>
   <h3>H3 HEADLINE GOES HERE</h3>
   <h4>H4 HEADLINE GOES HERE</h4>
   <h5>H4 HEADLINE GOES HERE</h5>
   <p>Paragraph text. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.</p>
   <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.</p>
   <ul class="list-background">
      <li>Bullet list goes here</li>
      <li>Bullet list goes here</li>
      <li>Bullet list goes here</li>
      <li>Bullet list goes here</li>
   </ul>
   <p>Paragraph highlight.A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.</p>
   <section>
      <div class="image-full image-general">
         <div class="block-image"><img title="The Pulpit Rock" src="{{media url="wysiwyg/1115_melfred-borzall_fastback.png"}}" alt="The Pulpit Rock" width="auto" height="402" /></div>
         <small class="image-caption">Image Caption. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</small>
      </div>
   </section>
   <section>
      <div class="image-right image-general">
         <div class="block-image"><img title="The Pulpit Rock" src="{{media url="wysiwyg/1115_melfred-borzall_fastback.png"}}" alt="The Pulpit Rock" width="430" height="250" /></div>
         <small class="image-caption">Image Caption. Lorem ipsum dolor sit amet, consectetur adipisicing elit, </small>
      </div>
      <div class="box-text">
         <p>Paragraph Text. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      </div>
   </section>
   <section>
      <div class="image-table">
         <div class="image-left image-table-cell">
            <div class="block-image"><img title="The Pulpit Rock" src="{{media url="wysiwyg/download.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
         </div>
         <div class="box-text image-table-cell">
            <h2>H2 HEADLINE GOES HERE</h2>
            <p>Paragraph Text. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consecte.</p>
         </div>
      </div>
   </section>
</div>
<section>
   <div class="gird-post gird-3">
      <div class="item">
         <div class="inner">
            <div class="thumbnail"><img src="{{media url="wysiwyg/1115_melfred-borzall_fastback.png"}}" alt="" /> <a class="btn icon-media icon-popup fancybox-video" title="Play Video" href="https://www.youtube.com/embed/7aao4IBw0OI?autoplay=1&amp;rel=0" data-fancybox=""><span></span> </a></div>
            <div class="text"><a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a></div>
         </div>
      </div>
      <div class="item">
         <div class="inner">
            <div class="thumbnail"><img src="{{media url="wysiwyg/1115_melfred-borzall_fastback.png"}}" alt="" /> <a id="icon-download" class="icon-download icon-popup " href="{{media url="wysiwyg/1115_melfred-borzall_fastback.png"}}" download=""></a></div>
            <div class="text"><a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a></div>
         </div>
      </div>
      <div class="item">
         <div class="inner">
            <div class="thumbnail"><img src="{{media url="wysiwyg/1115_melfred-borzall_fastback.png"}}" alt="" /> <a class="icon-download icon-popup" href="{{media url="wysiwyg/1115_melfred-borzall_fastback.png"}}" download=""></a></div>
            <div class="text"><a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a></div>
         </div>
      </div>
   </div>
</section>
<section>
   <div class="default-width table-wrapper">
      <table class="table-order">
         <thead>
            <tr>
               <th>Order #</th>
               <th>Date</th>
               <th>Ship to</th>
               <th>Order total</th>
               <th>Status</th>
               <th>Action</th>
            </tr>
         </thead>
         <tbody>
            <tr>
               <td data-th="Column heading">89723402200</td>
               <td data-th="Column heading">01/15/16</td>
               <td data-th="Column heading">Jane Doe</td>
               <td data-th="Column heading">$60.00</td>
               <td data-th="Column heading">Pending</td>
               <td data-th="Column heading"><a class="view" href="#">View </a> | <a class="reorder" href="#">Reorder </a></td>
            </tr>
            <tr>
               <td data-th="Column heading">89723402200</td>
               <td data-th="Column heading">01/15/16</td>
               <td data-th="Column heading">Jane Doe</td>
               <td data-th="Column heading">$60.00</td>
               <td data-th="Column heading">Pending</td>
               <td data-th="Column heading"><a class="view" href="#">View </a> | <a class="reorder" href="#">Reorder </a></td>
            </tr>
            <tr>
               <td data-th="Column heading">89723402200</td>
               <td data-th="Column heading">01/15/16</td>
               <td data-th="Column heading">Jane Doe</td>
               <td data-th="Column heading">$60.00</td>
               <td data-th="Column heading">Pending</td>
               <td data-th="Column heading"><a class="view" href="#">View </a> | <a class="reorder" href="#">Reorder </a></td>
            </tr>
         </tbody>
      </table>
   </div>
</section>
<section>
   <div class="background-full-width">
      <div class="block-info">
         <div class="block-info-text">
            <h2 class="title">H2 Text Goes Here and Here</h2>
            <div>Small Body Text</div>
            <p>Paragraph lighlight text goes here, A wonderful serenity has taken possession of my entire soul, like these sweet</p>
         </div>
         <div class="block-info-button"><button type="button"><span>BUTTON TEXT HERE</span></button></div>
      </div>
      <div class="block-info">
         <div class="block-info-text">
            <h2 class="title">H2 Text Goes Here and Here</h2>
            <div>Small Body Text</div>
            <p>Paragraph lighlight text goes here, A wonderful serenity has taken possession of my entire soul, like these sweet</p>
         </div>
         <div class="block-info-button"><button type="button"><span>BUTTON TEXT HERE</span></button></div>
      </div>
   </div>
</section>
<section>
   <div class="image-right image-general"><img title="The Pulpit Rock" src="{{media url="wysiwyg/1115_melfred-borzall_fastback.png"}}" alt="The Pulpit Rock" width="430" height="250" /></div>
   <div class="box-text">
      <h2>MINI-BLADE MADNESS!</h2>
      <span class="description">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot.</span>
      <p class="font-20">This offer expires March 31st or when we run out of supplies! Learn how to get your mini-blade keychain and get the dirt on our directional blades below.</p>
      <button type="button"><span>SHOP BLADES</span></button>
   </div>
</section>
<section>
<div class="half-center">
   <h2>EXPLORE</h2>
   <div class="half-center-item w-50">
        <a href="#" class="click"></a>
        <div class="inner h-620">
            <div class="thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/big.png"}}" alt="The Pulpit Rock" width="430" height="250" /></div>
            <div class="block-text">
                <a class="title" href="#">OUR STORY</a>
                <p data-mage-init="{&quot;forix/formattext&quot;:{}}">Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
            </div>
        </div>
        
   </div>
   <div class="half-center-item w-25">
   <a href="#" class="click"></a>
      <div class="inner h-295">
         <div class="thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/half-1.png"}}" alt="The Pulpit Rock" width="430" height="250" /></div>
         <div class="block-text">
            <a class="title" href="#">Quality &amp; Innovation</a>
            <p data-mage-init="{&quot;forix/formattext&quot;:{}}">Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
         </div>
      </div>
   </div>
   <div class="half-center-item w-25">
   <a href="#" class="click"></a>
      <div class="inner h-295">
         <div class="thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/half-2.png"}}" alt="The Pulpit Rock" width="430" height="250" /></div>
         <div class="block-text">
            <a class="title" href="#">Media &amp; Press</a>
            <p data-mage-init="{&quot;forix/formattext&quot;:{}}">Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
         </div>
      </div>
   </div>
   <div class="half-center-item w-50">
       <a href="#" class="click"></a>
      <div class="inner h-295">
         <div class="thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/width.png"}}" alt="The Pulpit Rock" width="430" height="250" /></div>
         <div class="block-text">
            <a class="title" href="#">Community</a>
            <p data-mage-init="{&quot;forix/formattext&quot;:{}}">Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
         </div>
      </div>
   </div>
</div>
</section>
<section>
   <h2>WATCH: MELFRED BORZALL DIRECTIONAL BLADES IN-ACTION</h2>
   <div class="image-general-video">
      <div class="block-video"><img title="The Pulpit Rock" src="{{media url="wysiwyg/1115_melfred-borzall_fastback.png"}}" alt="The Pulpit Rock" width="430" height="250" /> <a class="btn fancybox-video" title="Play Video" href="https://www.youtube.com/embed/7aao4IBw0OI?autoplay=1&amp;rel=0" data-fancybox=""><span></span> </a></div>
      <div class="box-text">
         <p>These nearly indestructible bits and blades are built to withstand all the tough spots and rough patches Mother Nature throws in your way.</p>
         <ul>
            <li>Over 70 years of experience in manufacturing quality blades by those that pioneered the HDD industry</li>
            <li>Various types of blades for mostly every ground condition you’ll come across</li>
            <li>Fast shipping and Melfred Borzall distributors located throughout the U.S. if you need it now</li>
         </ul>
      </div>
   </div>
</section>
<div id="open-download" class="popup-download" style="display: none;">
   <div class="thumbnail item-table"><img src="{{media url="wysiwyg/popup.jpg"}}" alt="" /></div>
   <div class="form-download item-table">
      <div class="title">THE Easiest Ways to Improve Efficiency of HDD Jobs</div>
      <p>With so many years in the HDD business, we’ve seen just about every mistake that can be made on a job site.</p>
      <p>In this e-book, we share the most common mistakes drillers make, give tips on how to avoid these mistakes, and provide tips on how to improve the efficiency of your next job. Let’s dig in.</p>
      <form class="form">
         <fieldset class="fieldset info">
            <div class="field">
               <div class="control"><input id="name" class="input-text required-entry" required="required" type="text" /> <label class="label"> <span>Name</span> </label></div>
            </div>
            <div class="field">
               <div class="control"><input id="company" class="input-text required-entry" required="required" type="text" /> <label class="label"> <span>Company</span> </label></div>
            </div>
            <div class="field">
               <div class="control"><input id="email-download" class="input-text required-entry " required="required" type="text" /> <label class="label"> <span>Email</span> </label></div>
            </div>
            <button class="button-download" type="button"><span>DOWNLOAD</span></button>
         </fieldset>
      </form>
   </div>
</div>