<!--
[[PageTitle]]: Cms Guides & Case Studies
[[ContentHeading]]: Cms Guides & Case Studies
[[Layout]]:1column
-->
<div class="page-top">
   <h1>Guides &amp; Case Studies</h1>
   <span>Take your HDD game to the next level with these resources</span>
   <p>Let’s face facts: directional drills are only as functional as their transmitters. Keep yours safe and sound with our ultra-durable and secure line of transmitter housings that protect your transmitter so you can cover more ground. These smooth operators look sleek on the outside but are nearly invincible inside–where it counts.</p>
</div>
<div class="gird-post gird-4">
   <div class="item">
      <div class="inner">
         <div class="thumbnail"><img src="{{media url="wysiwyg/pdf-1.png"}}" alt="" /> <a id="icon-download" class="icon-download icon-popup " href="{{media url="wysiwyg/pdf-1.png"}}" download=""></a></div>
         <div class="text">
            <a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a>
            <p>Learn common mistakes drillers make and how you and your crew can avoid these mistakes while improving your efficiency.</p>
         </div>
      </div>
   </div>
   <div class="item">
      <div class="inner">
         <div class="thumbnail"><img src="{{media url="wysiwyg/pdf-2.png"}}" alt="" /> <a id="icon-download" class="icon-download icon-popup " href="javascript:void(0);"></a></div>
         <div class="text">
            <a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a>
            <p>Learn common mistakes drillers make and how you and your crew can avoid these mistakes while improving your efficiency.</p>
         </div>
      </div>
   </div>
   <div class="item">
      <div class="inner">
         <div class="thumbnail"><img src="{{media url="wysiwyg/pdf-3.png"}}" alt="" /> <a id="icon-download" class="icon-download icon-popup " href="javascript:void(0);"></a></div>
         <div class="text"><a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a></div>
      </div>
   </div>
   <div class="item">
      <div class="inner">
         <div class="thumbnail"><img src="{{media url="wysiwyg/pdf-4.png"}}" alt="" /> <a id="icon-download" class="icon-download icon-popup " href="javascript:void(0);"></a></div>
         <div class="text">
            <a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a>
            <p>Learn common mistakes drillers make and how you and your crew can avoid these mistakes while improving your efficiency.</p>
         </div>
      </div>
   </div>
   <div class="item">
      <div class="inner">
         <div class="thumbnail"><img src="{{media url="wysiwyg/pdf-1.png"}}" alt="" /> <a id="icon-download" class="icon-download icon-popup " href="javascript:void(0);"></a></div>
         <div class="text">
            <a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a>
            <p>Learn common mistakes drillers make and how you and your crew can avoid these mistakes while improving your efficiency.</p>
         </div>
      </div>
   </div>
   <div class="item">
      <div class="inner">
         <div class="thumbnail"><img src="{{media url="wysiwyg/pdf-2.png"}}" alt="" /> <a id="icon-download" class="icon-download icon-popup " href="javascript:void(0);"></a></div>
         <div class="text">
            <a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a>
            <p>Learn common mistakes drillers make and how you and your crew can avoid these mistakes while improving your efficiency.</p>
         </div>
      </div>
   </div>
   <div class="item">
      <div class="inner">
         <div class="thumbnail"><img src="{{media url="wysiwyg/pdf-1.png"}}" alt="" /> <a id="icon-download" class="icon-download icon-popup " href="javascript:void(0);"></a></div>
         <div class="text">
            <a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a>
            <p>Learn common mistakes drillers make and how you and your crew can avoid these mistakes while improving your efficiency.</p>
         </div>
      </div>
   </div>
   <div class="item">
      <div class="inner">
         <div class="thumbnail"><img src="{{media url="wysiwyg/pdf-3.png"}}" alt="" /> <a class="icon-download icon-popup" href="javascript:void(0);"></a></div>
         <div class="text">
            <a class="title" href="#" data-mage-init="{&quot;forix/formattext&quot;:{}}">Watch the video our interns made about their experience</a>
            <p>Learn common mistakes drillers make and how you and your crew can avoid these mistakes while improving your efficiency.</p>
         </div>
      </div>
   </div>
</div>
<div class="half-center">
   <h2>EXPLORE</h2>
   <div class="half-center-item w-50">
        <a href="#" class="click"></a>
        <div class="inner h-620">
            <div class="thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/big.png"}}" alt="The Pulpit Rock" width="430" height="250" /></div>
            <div class="block-text">
                <a class="title" href="#">OUR STORY</a>
                <p data-mage-init="{&quot;forix/formattext&quot;:{}}">Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
            </div>
        </div>
        
   </div>
   <div class="half-center-item w-25">
   <a href="#" class="click"></a>
      <div class="inner h-295">
         <div class="thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/half-1.png"}}" alt="The Pulpit Rock" width="430" height="250" /></div>
         <div class="block-text">
            <a class="title" href="#">Quality &amp; Innovation</a>
            <p data-mage-init="{&quot;forix/formattext&quot;:{}}">Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
         </div>
      </div>
   </div>
   <div class="half-center-item w-25">
   <a href="#" class="click"></a>
      <div class="inner h-295">
         <div class="thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/half-2.png"}}" alt="The Pulpit Rock" width="430" height="250" /></div>
         <div class="block-text">
            <a class="title" href="#">Media &amp; Press</a>
            <p data-mage-init="{&quot;forix/formattext&quot;:{}}">Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
         </div>
      </div>
   </div>
   <div class="half-center-item w-50">
       <a href="#" class="click"></a>
      <div class="inner h-295">
         <div class="thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/width.png"}}" alt="The Pulpit Rock" width="430" height="250" /></div>
         <div class="block-text">
            <a class="title" href="#">Community</a>
            <p data-mage-init="{&quot;forix/formattext&quot;:{}}">Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
         </div>
      </div>
   </div>
</div>
<div id="open-download" class="popup-download" style="display: none;">
   <div class="thumbnail item-table"><img src="{{media url="wysiwyg/popup.jpg"}}" alt="" /></div>
   <div class="form-download item-table">
      <div class="title">THE Easiest Ways to Improve Efficiency of HDD Jobs</div>
      <p>With so many years in the HDD business, we’ve seen just about every mistake that can be made on a job site.</p>
      <p>In this e-book, we share the most common mistakes drillers make, give tips on how to avoid these mistakes, and provide tips on how to improve the efficiency of your next job. Let’s dig in.</p>
      <form class="form">
         <fieldset class="fieldset info">
            <div class="field">
               <div class="control"><input id="name" class="input-text required-entry" required="required" type="text" /> <label class="label"> <span>Name</span> </label></div>
            </div>
            <div class="field">
               <div class="control"><input id="company" class="input-text required-entry" required="required" type="text" /> <label class="label"> <span>Company</span> </label></div>
            </div>
            <div class="field">
               <div class="control"><input id="email-download" class="input-text required-entry " required="required" type="text" /> <label class="label"> <span>Email</span> </label></div>
            </div>
            <button class="button-download" type="button"><span>DOWNLOAD</span></button>
         </fieldset>
      </form>
   </div>
</div>