<!--
[[PageTitle]]: Cms Our Story
[[ContentHeading]]: Cms Our Story
[[Layout]]:1column
-->
<p>{{block class="Magento\Framework\View\Element\Template" name="block.timeline" template="Magento_Cms::timeline.phtml"}}</p>
<div class="background-full-width">
    <div class="width-content">
        <h1>Our story</h1>
    </div>
</div>
<div class="background-full-color">
    <div class="default-width block-text">
        <h3>70 Years of Groundbreaking Drilling Solutions</h3>
        <p>When versatile designs meet quality materials, dependable HDD tools are born. We hire expert engineers who put their designs to work, right away. We know that high quality drilling solutions are only as good as the job they perform, so we take them out of the workshop and into the field to see how they hold up under pressure. By watching our tools work and watching the way drillers work with our tools, we refine our designs to pack the most punch at a reasonable price. The result: long-lasting, Earth-chomping, tough-as-nails tools that help drillers cover more ground while limiting expenses.</p>
    </div>
</div>
<div class="default-width">
    <div class="image-table">
        <div class="box-text image-table-cell">
            <h3>We’re not Out to Make a Quick Buck</h3>
            <p>We’re out to keep the drilling industry moving forward. We stand by our products because we know that they’ll stand up to the toughest conditions nature puts in your path. You can’t control what you’ll run into underground. But you can control the quality of tools you choose.</p>
        </div>
        <div class="image-right image-table-cell">
            <div class="block-image images-small"><img title="The Pulpit Rock" src="{{media url="wysiwyg/70-transparant-2 2.png"}}" alt="The Pulpit Rock" width="220" height="200" /></div>
        </div>
    </div>
</div>
<div class="background-full-width ourstore-timeline">
    <div class="width-content">
        <section class="cd-horizontal-timeline">
            <div class="timeline">
                <div class="events-wrapper">
                    <div class="events">
                        <ol>
                            <li><a class="selected" href="#0" data-date="01/01/1946">1946</a></li>
                            <li><a href="#0" data-date="01/01/1955">1955</a></li>
                            <li><a href="#0" data-date="01/01/1972">1972</a></li>
                            <li><a href="#0" data-date="01/01/1978">1978</a></li>
                            <li><a href="#0" data-date="01/01/1981">1981</a></li>
                            <li><a href="#0" data-date="01/01/1988">1988</a></li>
                            <li><a href="#0" data-date="01/01/1991">1991</a></li>
                            <li><a href="#0" data-date="01/01/2003">2003</a></li>
                            <li><a href="#0" data-date="01/01/2005">2005</a></li>
                            <li><a href="#0" data-date="01/01/2010">2010</a></li>
                            <li><a href="#0" data-date="01/01/2014">2014</a></li>
                            <li><a href="#0" data-date="01/01/2017">2017</a></li>
                            <li><a href="#0" data-date="01/01/2018">2018</a></li>
                            <li><a href="#0" data-date="01/01/2019">2019</a></li>
                            <li><a href="#0" data-date="01/01/2020">2020</a></li>
                            <li><a href="#0" data-date="01/01/2022">2022</a></li>
                        </ol><span class="filling-line"></span></div>
                </div>
                <ul class="cd-timeline-navigation">
                    <li>
                        <a class="prev inactive" href="#0"></a>
                    </li>
                    <li>
                        <a class="next" href="#0"></a>
                    </li>
                </ul>
            </div>
            <div class="events-content">
                <ol>
                    <li class="selected" data-date="01/01/1946">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>1946</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/1955">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>1955</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/1972">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>1972</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/1978">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>1978</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/1981">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>1981</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/1988">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>1988</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/1991">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>1991</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/2003">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>2003</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/2005">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>2005</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/2010">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>2010</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/2014">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>2014</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/2017">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>2017</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/2018">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>2018</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/2019">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>2019</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                    <li data-date="01/01/2020">
                        <div class="block-thumbnail"><img title="The Pulpit Rock" src="{{media url="wysiwyg/timeline.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
                        <div class="block-text"><span>2020</span>
                            <h2>Ted Melsheimer invents the successful line of Mustang pipe squeeze off.</h2>
                            <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
                        </div>
                    </li>
                </ol>
            </div>
        </section>
    </div>
</div>
<div class="background-full-color">
    <div class="default-width">
        <div class="image-table">
            <div class="image-left image-table-cell">
                <div class="block-image"><img title="The Pulpit Rock" src="{{media url="wysiwyg/solar-panelsA.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
            </div>
            <div class="box-text image-table-cell">
                <h3>Proud to Be Going Green</h3>
                <p>We don’t just protect drillers, we protect the Earth. Our Santa Maria plant houses 800 solar panels producing almost 150 kilowatts of power, enough solar electric energy to provide over 90% of the plant’s needs. We also cut our lighting energy usage in half by using skylights in offices &amp; production spaces and replacing all our metal halide plant lighting with high-efficiency T5 fluorescent lights. We recently brought on two electric cars for business use which we recharge at the two plug-in stations in our north parking lot. When you see the “Made with Solar Power” label, not only are you getting a quality tool priced for value but you know that tool is made in a clean, high-tech environmentally friendly facility.</p>
            </div>
        </div>
    </div>
</div>
<div class="media-explore-content">
<div class="title-media">Explore</div>
<div class="media-explore-inner">
    <div class="explore-item explore-item-box1">
    <a href="#" class="click"></a>
        <div class="explore-img">
            <img src="{{media url="wysiwyg/download.png"}}" alt="" />
        </div>
        <div class="explore-item-text">
            <div class="title">
                OUR STORY
            </div>
            <p data-mage-init='{"forix/formattext":{}}'>Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
        </div>
    </div>
    <div class="explore-item explore-item-box2">
    <a href="#" class="click"></a>
        <div class="explore-img">
            <img src="{{media url="wysiwyg/download.png"}}" alt="" />
        </div>
        <div class="explore-item-text">
            <div class="title">
                Quality & Innovation
            </div>
            <p data-mage-init='{"forix/formattext":{}}'>Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
        </div>
    </div>
    <div class="explore-item explore-item-box2">
    <a href="#" class="click"></a>
        <div class="explore-img">
            <img src="{{media url="wysiwyg/download.png"}}" alt="" />
        </div>
        <div class="explore-item-text">
            <div class="title">
                COMMUNITY
            </div>
            <p data-mage-init='{"forix/formattext":{}}'>Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
        </div>
    </div>
</div>
</div>