<!--
[[PageTitle]]: Cms Quality & Innovation
[[ContentHeading]]: Cms Quality & Innovation
[[Layout]]:1column
-->
<div class="background-full-width banner-title">
   <h1>Quality &amp; Innovation</h1>
   <span>Setting the standard for directional drilling tool manufacturers</span>
</div>
<div class="background-full-color">
<div class="box-introduct width-content">
   <h3>As the original directional drilling tool manufacturer, we’re serious about maintaining our spotless reputation.</h3>
   <div class="box-introduct-content">
      <div class="box-item">
         <span class="icon-left"></span>
         <p>We have a key advantage over our competitors: we actually care what happens to our products after they leave our plant and end up on the job. To us, each tool we ship is not just a new order; it’s a new relationship.</p>
      </div>
      <div class="box-item">
         <span class="icon-right"></span>
         <p>We have a key advantage over our competitors: we actually care what happens to our products after they leave our plant and end up on the job. To us, each tool we ship is not just a new order; it’s a new relationship.</p>
      </div>
   </div>
</div>
</div>
<div class="image-table background-full-width background-full-color">
   <div class="width-content">
      <div class="box-text image-table-cell">
         <h3>Moving the Drill Industry Forward</h3>
         <p>We weren’t just handed the role of industry leaders; we earned it. R&amp;D is the responsibility of every directional drilling tool manufacturer so our expert engineers invest major resources in researching and developing new tools to tackle tough jobs faster, more efficiently and more cost-effectively. Whether your job requires a tool we have in our inventory or you need us to develop an entirely new solution specifically for your dig, we can design it, create it and get it to you fast–every time.</p>
      </div>
      <div class="image-right image-table-cell">
         <div class="block-image images-small"><img title="The Pulpit Rock" src="{{media url="wysiwyg/70-transparant-2 2.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
      </div>
   </div>
</div>
<div class="image-table background-full-width">
   <div class="width-content">
      <div class="image-table-cell image-left">
         <div class="block-image"><img title="The Pulpit Rock" src="{{media url="wysiwyg/banner-img-1.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
      </div>
      <div class="box-text image-table-cell">
         <h3>Quality Control Grounded in Excellence</h3>
         <p>No rusty production warehouses for us. We engineer and manufacture all our products in our spotless, modern facility using state-of-the-art computerized machining stations. We personally inspect each tool during every stage of the manufacturing process. Tools that don’t make the cut (there aren’t many, by the way) are scrapped before even leaving the factory floor. That means you’ll receive a tool that is guaranteed to perform as expected, or better.</p>
      </div>
   </div>
</div>
<div class="image-table background-full-width background-full-color">
   <div class="width-content">
      <div class="box-text image-table-cell">
         <h3>Fast and Safe Shipping, Even off the Beaten Path</h3>
         <p>When you need a new tool, we know the clock is ticking. We won’t waste your time with incorrect orders or poorly packaged products. We double-check each and every order before it leaves our warehouse and package it all up in sturdy foam and shrink wrap, designed specifically to handle the weight and non-standard shapes of our products. Larger reamers are strapped onto custom made steel pallets which you can reuse to get your reamer to the next location in one piece. Our extensive distributor network (LINK: Find a Distributor page) can get the right tool into your hands right away so you can get back to work.</p>
      </div>
      <div class="image-right image-table-cell">
         <div class="block-image"><img title="The Pulpit Rock" src="{{media url="wysiwyg/quality-right.png"}}" alt="The Pulpit Rock" width="320" height="320" /></div>
      </div>
   </div>
</div>
<div class="media-explore-content">
<div class="title-media">Explore</div>
<div class="media-explore-inner">
    <div class="explore-item explore-item-box1">
    <a href="#" class="click"></a>
        <div class="explore-img">
            <img src="{{media url="wysiwyg/download.png"}}" alt="" />
        </div>
        <div class="explore-item-text">
            <div class="title">
                OUR STORY
            </div>
            <p data-mage-init='{"forix/formattext":{}}'>Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
        </div>
    </div>
    <div class="explore-item explore-item-box2">
    <a href="#" class="click"></a>
        <div class="explore-img">
            <img src="{{media url="wysiwyg/download.png"}}" alt="" />
        </div>
        <div class="explore-item-text">
            <div class="title">
                Quality & Innovation
            </div>
            <p data-mage-init='{"forix/formattext":{}}'>Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
        </div>
    </div>
    <div class="explore-item explore-item-box2">
    <a href="#" class="click"></a>
        <div class="explore-img">
            <img src="{{media url="wysiwyg/download.png"}}" alt="" />
        </div>
        <div class="explore-item-text">
            <div class="title">
                COMMUNITY
            </div>
            <p data-mage-init='{"forix/formattext":{}}'>Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
        </div>
    </div>
</div>
</div>