<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <div class="page-title-wrapper">
        <div class="page-title" id="page-title-heading">
            <span class="base"><?php echo __( 'Thanks For Your Purchase!' ) ?></span>
        </div>
    </div>
    <?php if ($block->getOrderId()):?>
        <div class="order-notification">
        <?php if ($block->getCanViewOrder()) :?>
           <p><?= __('Your order # is: %1', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?= __('Your order # is: <span>%1</span>', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?= /* @escapeNotVerified */ __('You will receive an order confirmation with the details') ?></p>
            <p><?= /* @escapeNotVerified */ __('of your order and a link to track it\'s  progress.') ?></p>
        </div>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
