<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php echo $block->getGridHtml(); ?>
<input type="hidden" name="product_id" id="product_id" data-form-part="forix_media_video_form" value=""/>
<script type="text/x-magento-init">
    {
        "*": {
            "Forix_Media/video/assign-products": {
                "selectedProducts": <?php /* @escapeNotVerified */
    echo $block->getProductsJsonCustom(); ?>,
                "gridJsObjectName": <?php /* @escapeNotVerified */
    echo '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }

</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
<script>
    require([
        "jquery"
    ], function ($) {
        $(document).ajaxComplete(function (event, xhr, settings) {
            $('#product_id').val('');
        });
    });
</script>
