<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Forix\ProductWizard\Block\Adminhtml\Group\Item\Option\Edit\OptionGrid $block */

/** @var \Forix\ProductWizard\Block\Adminhtml\Group\Item\Option\Edit\Option $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<?php if(!$block->getGroupItem()):?>
    <input type="hidden" name="selected_products" id="in_wizard_products" data-form-part="forix_productwizard_group_item_form" value="" />
    <script type="text/x-magento-init">
        {
            "*": {
                "Forix_ProductWizard/js/assign-products": {
                    "selectedProducts": <?= /* @escapeNotVerified */ $block->getProductsJson() ?>,
                    "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
                }
            }
        }
    </script>
    <!-- @todo remove when "UI components" will support such initialization -->
    <script>
        require('mage/apply/main').apply();
    </script>
<?php endif;?>