<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Forix\ProductWizard\Block\Adminhtml\Group\Item\Option\Edit\WizardOptionGridBestOn $block */

/** @var \Forix\ProductWizard\Block\Adminhtml\Group\Item\Option\Edit\WizardOptionBestOn $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="best_on" id="in_wizard_options_best_on"
       data-form-part="forix_productwizard_group_item_option_form" value=""/>
<script type="text/x-magento-init">
        {
            "*": {
                "Forix_ProductWizard/js/assign-options": {
                    "target_element_id": "in_wizard_options_best_on",
                    "target_element_name": "best_on[]",
                    "selectedProducts": <?= /* @escapeNotVerified */
    $block->getProductsJson() ?>,
                    "gridJsObjectName": <?= /* @escapeNotVerified */
    '"' . $gridJsObjectName . '"' ?: '{}' ?>
                }
            }
        }

</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>