<?php
/** @var \Mirasvit\Credit\Block\Customer\Account $block */
$balance = $block->getBalance();

/** @var \Magento\Framework\Pricing\Helper\Data $pricingHelper */
$pricingHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>

<div class="block credit__account-balance">
    <div class="block-title">
        <strong><?= __('Balance') ?></strong>
    </div>
    <div class="block-content">

        <?= __('Current credit balance: <b>%1</b>', $pricingHelper->currency($balance->getAmount())) ?>

        <div class="credit__account-subscription">
            <form action="<?= $block->getUrl('credit/account/subscribe') ?>" method="post" id="form-validate">
                <div>
                    <input type="checkbox" id="credit_subscription" class="checkbox" name="is_subscribed" value="1"
                           <?php if ($balance->getIsSubscribed()): ?>checked="checked"<?php endif ?>>

                    <label for="credit_subscription">
                        <?= __('Subscribe to email notifications') ?>
                    </label>

                    &nbsp;&nbsp;
                    <button id="subscribe_button" type="submit" class="button" style="display: none;">
                        <span><?= __('Save') ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>