<?php
$_productCollection = $block->getCollection();
$image = 'new_products_content_widget_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
?>
<!--https://softstarshoes.local/pub/static/frontend/Forix/softstarshoes/en_US/Magento_Catalog/images/product/placeholder/small_image.jpg-->
<h4>Some of our most loved styles</h4>
<div id="homepage-product" class="products wrapper grid products-grid">
    <div class="owl-homepage-product owl-carousel products list items product-items">
        <?php $iterator = 1; ?>
        <?php foreach ($_productCollection as $_item): ?>
            <div class="item">
                <?php $available = ''; ?>
                <div class="product-outer">
                    <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                        <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                        <?php
                        $productImage = $block->getImage($_item, $image);
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                        ?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo $block->escapeHtml($_item->getName()) ?>" class="product photo product-item-photo">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                    <?php echo $block->escapeHtml($_item->getName()) ?></a>
                            </strong>
                            <?php if($_item->getTypeId() == 'configurable'): ?>
                                <?php if($this->countColorProduct($_item->getId())): ?>
                                    <?php if($this->countColorProduct($_item->getId()) == '1'): ?>
                                        <?php echo $this->countColorProduct($_item->getId()) . ' ' . __('Color') ?>
                                        <?php if($block->isCustomize($_item->getId())): ?>
                                            <?php echo ' + '?>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php echo $this->countColorProduct($_item->getId()) . ' ' . __('Colors') ?>
                                        <?php if($block->isCustomize($_item->getId())): ?>
                                            <?php echo ' + '?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if($block->isCustomize($_item->getId())): ?>
                                    <?php echo __('Customizable') ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                            <div class="price-wrapper">
                                <?php if($_item->getTypeId() == 'aw_giftcard' || $_item->getAwGcOpenAmountMin()): ?>
                                    <span><?php echo __('From '); ?></span><span class="price old-price"><?php echo $priceHelper->currency($block->getMinPriceGiftCard($_item, $_item->getAwGcOpenAmountMin()), true, false); ?></span>
                                <?php else: ?>
                                    <span><?php if(($_item->getPriceInfo()->getPrice('final_price')->getValue() && $_item->getPriceInfo()->getPrice('regular_price')->getValue() != $_item->getPriceInfo()->getPrice('final_price')->getValue()) || $block->isCustomOption($_item->getId())) echo __('From'); ?></span>
                                    <?php if($_item->getPriceInfo()->getPrice('final_price')->getValue() && $_item->getPriceInfo()->getPrice('regular_price')->getValue() != $_item->getPriceInfo()->getPrice('final_price')->getValue()): ?>
                                        <span class="price old-price price-final_price"><?php echo $priceHelper->currency($_item->getPriceInfo()->getPrice('regular_price')->getValue(), true, false); ?></span>
                                        <span class="price"><?php echo $priceHelper->currency($_item->getPriceInfo()->getPrice('final_price')->getValue(), true, false);?></span>
                                    <?php else: ?>
                                        <span class="price old-price"><?php echo $priceHelper->currency($_item->getPriceInfo()->getPrice('regular_price')->getValue(), true, false); ?></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    <script>
        require([
            "jquery"
        ], function($){
            $('.block-slider').on('init', function(event, slick, direction){
                $('.block-slider').addClass("slick-loaded");
            });
        });
    </script>
</div>
</div>