<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Listing\Configurable */ ?>
<div class="swatch-opt-<?= /* @escapeNotVerified */ $block->getProduct()->getId() ?>"></div>
<script>
    require([
        'jquery',
        'jquery/ui',
        'Magento_Swatches/js/swatch-renderer',
        'Magento_Swatches/js/catalog-add-to-cart',
        'priceBox'
    ], function ($) {
        var jsonConfig = <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>;
        var swatch<?= /* @escapeNotVerified */ $block->getProduct()->getId() ?> =  $('.swatch-opt-<?= /* @escapeNotVerified */ $block->getProduct()->getId() ?>');
        if(swatch<?= /* @escapeNotVerified */ $block->getProduct()->getId() ?>.find('div').length < 1) {
            swatch<?= /* @escapeNotVerified */ $block->getProduct()->getId() ?>.SwatchRenderer({
                selectorProduct: '.product-item-details',
                onlySwatches: true,
                enableControlLabel: false,
                numberToShow: <?= /* @escapeNotVerified */ 4;?>,
                jsonConfig: jsonConfig,
                moreButtonUrl: '<?php echo $block->getProduct()->getProductUrl(); ?>',
                moreButtonText: '<?php echo __( '+%count more %label' )?>',
                jsonSwatchConfig: <?= /* @escapeNotVerified */ $block->getJsonSwatchConfig() ?>,
                mediaCallback: '<?= /* @escapeNotVerified */ $block->getMediaCallback() ?>'
            });
        }

        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($block->getProduct()->getId()) ?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes.priceBox({
            'priceConfig': {
                priceFormat: jsonConfig.priceFormat,
                prices: jsonConfig.prices
            }
        });
    });
</script>
