<?php


namespace Forix\ProductWizard\Model\ResourceModel\GroupItemOption;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{

    /**
     * Define resource model
     *
     * @return void
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    protected function _construct()
    {
        $this->_init(
            'Forix\ProductWizard\Model\GroupItemOption',
            'Forix\ProductWizard\Model\ResourceModel\GroupItemOption'
        );
        $this->_setIdFieldName($this->getResource()->getIdFieldName());
    }

    /**
     * @return array
     */
    public function toOptionHash()
    {
        return $this->_toOptionHash('group_item_option_id', 'title');
    }

    /**
     * @param int $groupItemId
     * @return $this
     */
    public function addGroupItemIdToFilter($groupItemId)
    {
        $this->addFieldToFilter('item_id', $groupItemId);
        return $this;
    }

    protected function _beforeLoad()
    {

        $this->setOrder('sort_order', self::SORT_ORDER_ASC);
        return parent::_beforeLoad(); // TODO: Change the autogenerated stub
    }
}
