
<!--[[Header]]: [Media] media-explore -->
<div class="title-media">Explore</div>
<div class="media-explore-inner">
    <div class="explore-item explore-item-box1">
    <a href="#" class="click"></a>
        <div class="explore-img">
            <img src="{{media url="wysiwyg/download.png"}}" alt="" />
        </div>
        <div class="explore-item-text">
            <div class="title">
                OUR STORY
            </div>
            <p data-mage-init='{"forix/formattext":{}}'>Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
        </div>
    </div>
    <div class="explore-item explore-item-box2">
    <a href="#" class="click"></a>
        <div class="explore-img">
            <img src="{{media url="wysiwyg/download.png"}}" alt="" />
        </div>
        <div class="explore-item-text">
            <div class="title">
                Quality & Innovation
            </div>
            <p data-mage-init='{"forix/formattext":{}}'>Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
        </div>
    </div>
    <div class="explore-item explore-item-box2">
    <a href="#" class="click"></a>
        <div class="explore-img">
            <img src="{{media url="wysiwyg/download.png"}}" alt="" />
        </div>
        <div class="explore-item-text">
            <div class="title">
                COMMUNITY
            </div>
            <p data-mage-init='{"forix/formattext":{}}'>Nunc porta sit amet tortor sed interdum. Quisque pulvinar volutpat ex, sit amet suscipit nibh cursus sit amet...</p>
        </div>
    </div>
</div>