<!--[[Header]]: [Media] media-press -->
<div class="media-press">
<div class="title-media">Press</div>
<div class="media-press-content">
    <div class="item">
        <div class="date">10/24/2017</div>
        <a href="#">FASTREAM FASTBACK HDD: OVERALL LIGHTER CONSTRUCTION SITE PRESENCE</a>
    </div>
    <div class="item">
        <div class="date">10/24/2017</div>
        <a href="#">FASTREAM FASTBACK HDD: OVERALL LIGHTER CONSTRUCTION SITE PRESENCE</a>
    </div>
    <div class="item">
        <div class="date">10/24/2017</div>
        <a href="#">FASTREAM FASTBACK HDD: OVERALL LIGHTER CONSTRUCTION SITE PRESENCE</a>
    </div>
    <div class="item">
        <div class="date">10/24/2017</div>
        <a href="#">FASTREAM FASTBACK HDD: OVERALL LIGHTER CONSTRUCTION SITE PRESENCE</a>
    </div>
    <div class="item">
        <div class="date">10/24/2017</div>
        <a href="#">FASTREAM FASTBACK HDD: OVERALL LIGHTER CONSTRUCTION SITE PRESENCE</a>
    </div>
</div>
</div>