<!--[[Header]]: [Contact] right-contact-location-block -->
<div class="talkhdd">
   <div class="title"><strong>TALK TO AN HDD EXPERT</strong></div>
   <ul class="address-phone">
      <li><span>Toll free</span> <span>800.558.7500</span></li>
      <li><span>International</span> <span>805.739.0118</span></li>
      <li>
         <p>Mon-Fri: 7-5PM PT</p>
         <p></p>
         <p>Sat: 8-2PM PT</p>
      </li>
   </ul>
   <span class="m-email"><i class="fa fa-envelope"></i> MAIL@MELFREDBORZALL.COM</span>
   <div class="btn-chatnow" onclick="parent.LC_API.open_chat_window({source:'minimized'})"><img src="{{media url="wysiwyg/LiveChat-Online.png"}}" width="428" height="70" /></div>
</div>
<div class="comevisit">
   <div class="title"><strong>COME VISIT US</strong></div>
   <p>Do you like wine, tri-tip BBQ and state-of-the-art manufacturing? If the answer is yes to any of these questions, come by for a visit. We have them all right here in Santa Maria.</p>
   <div class="address">
      <div class="inner">
         <div>2712 Airpark Drive Santa Maria, CA 93455</div>
         <span>Directions</span>
      </div>
   </div>
</div>