<?php
/**
 * @category   Fishpig
 * @package   Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author     Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="block block-blog block-blog-follow-us">
	<div class="block-title">
		<strong><span><?php echo __('Follow Us') ?></span></strong>
	</div>
	<div class="block-content">
        <ul class="box-socials social-links icon-wrapper-square">
            <li class="ico-facebook"><a title="Join us on Facebook" href="http://www.facebook.com/SoftstarShoes" target="_blank"></a></li>
            <li class="ico-twitter"><a class="first" title="Follow Softstar on Twitter" href="http://twitter.com/softstarshoes" target="_blank"></a></li>
            <li class="ico-instagram"><a title="Instagram" href="http://instagram.com/softstarshoes" target="_blank"></a></li>
            <li class="ico-pinit"><a title="Pinterest" href="http://www.pinterest.com/softstarelves/" target="_blank"></a></li>
        </ul>
	</div>
</div>