<?php
/**
 * Created by Mercurial
 * Job Title: Magento Developer
 * Project Name: M2.2.3-EE - Melfredborzall
 */
?>
<div id="is-domestic" class="no-display is-domestic" data-bind="scope: 'customer-info'">
    <div class="is-domestic-content">
        <p class="locate"><?php echo __('Choose Your Location:');?></p>
        <button class="international-order" data-bind="click: chooseDomestic"><?php echo __('Domestic (US)');?></button>
        <button class="international-order" data-bind="click: chooseInternational"><?php echo __('International');?></button>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#is-domestic": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer-info": {
                        "component": "Forix_InternationalOrders/js/customer-info",
                        "config": {
                            "url": "<?php echo $block->getUrl('domestic/ajax/cookie'); ?>",
                            "isBackOrder": "<?php echo $block->isBackOrder() ?>"
                        }
                    }
                }
            }
        }
    }
</script>
<script>
    require([
        'jquery',
        'Magento_Customer/js/customer-data',
        'jquery/jquery.cookie'
    ], function ($, customerData) {
        $(document).on('ajaxComplete', function (event, xhr, settings) {
            var loadAjaxFilter = 'shopbyAjax=1';
            if(settings.url.indexOf(loadAjaxFilter) != -1) {
                loadPrice();
            }
        });

        $(window).on("contentUpdatedProductSuccess", function () {
            loadPrice();
        });
        $(window).on("contentUpdatedSuccess", function () {
            loadPrice();
        });
        function loadPrice() {
            var customerInfo = customerData.get('customer-info');
            var check_cookie = $.cookie('domestic-cookie');
            var result = customerInfo().is_domestic == 1 || check_cookie == 1;
            if (result) {
                $('.price-box').removeClass("no-display");
                $('.price-container').removeClass("no-display");
            } else {
                $('.price-box').addClass("no-display");
                $('.price-container').addClass("no-display");
            }
        }
    });
</script>

